### ISSUE TITLE
Investigate effect of symlinks on Windows build

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#10216]
Our current bazel config for Windows symlinks doesn’t actually work. `config:windows` is not valid (configs are loaded too early to depend on the platform). What we can do is to write it to `bazelrc.local` instead. However that fails because apparently our CI machines do not activate symlinks after all. We should test if this is a worthwile improvement.

**Comment by aherrmann-da** [comment]
> However that fails because apparently our CI machines do not activate symlinks after all.

I tested this on an ad-hoc machine and in that case the machine was not configured to [enable developer mode](https://docs.microsoft.com/en-us/windows/apps/get-started/developer-mode-features-and-debugging#use-group-policies-or-registry-keys-to-enable-a-device) and creating symlinks was not allowed. I had to
1. Add the following registry entry
    ```
    New-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock' -Name AllowDevelopmentWithoutDevLicense -Type DWord -Value 1 -Force
    ```
2. And restart the machine

After this I could use `mklink` to create a symlink
```
PS C:\Users\u> cmd /c mklink link demo.txt
symbolic link created for link <<===>> demo.txt
```

However, I had to restart. Logging out and back in was not sufficient.
Perhaps a restart could be avoided if [the registry entry is set before the user is created](https://github.com/digital-asset/daml/commit/4847ce906f7446ec6dce6dd7aa481c1b516d423f).

---

> Our current bazel config for Windows symlinks doesn’t actually work. `config:windows` is not valid (configs are loaded too early to depend on the platform).

To clarify, `--config` is not related to platform resolution, it's just that this feature is [not supported for `startup` options](https://docs.bazel.build/versions/main/guide.html#--config):

> This syntax does not extend to the use of startup to set startup options, e.g. setting startup:config-name --some_startup_option in the .bazelrc will be ignored.

**Comment by cocreature** [comment]
@aherrmann-da Is the adhoc machine sufficient to investigate if it brings benefits wtr to performance before we figure out how to apply it to our CI machines?

**Comment by aherrmann-da** [comment]
@cocreature Yes, for that it should be sufficient. I'll run some builds for comparison and see what comes out.l

**Comment by aherrmann-da** [comment]
While manually creating symlinks with `mklink` works, Bazel fails to create symlinks 
```
Error in download_and_extract: java.io.IOException: Error extracting C:/users/u/_bazel_
/temp12784058608108350362/60ed30aab00e9ffa2e2fe19e59f7de885f029556.tar.gz to C:/users/u
_haskell/temp12784058608108350362: Cannot create symlink (name=C:\users\u\_bazel_u\w3d6
les\.bazelrc, target=C:\users\u\_bazel_u\w3d6ug6o\external\rules_haskell\.bazelrc): ERR
jni.cc(117): nativeCreateSymlink(\\?\C:\users\u\_bazel_u\w3d6ug6o\external\rules_haskel
\u\_bazel_u\w3d6ug6o\external\rules_haskell\.bazelrc): ERROR: src/main/native/windows/f
\users\u\_bazel_u\w3d6ug6o\external\rules_haskell\.bazelrc): createSymbolicLinkW failed
```
It seems that on-top of developer mode we [also need "Windows Creators Update (1703)"](https://github.com/bazelbuild/bazel/blob/ad7a17f46f96b636ceadb4c5f241c74c051550ef/src/main/tools/build-runfiles-windows.cc#L352-L353). However, our machines only run "Anniversary Update (1607)".

**Comment by aherrmann-da** [comment]
I ran test builds comparing Windows without symlinks to Windows with symlinks enabled. The results are as follows:

- full uncached build
  - no symlinks:   Elapsed time: 5321.939s, Critical Path: 2346.76s
  - with symlinks: Elapsed time: 5663.711s, Critical Path: 2409.10s
- full uncached test
  - no symlinks:   Elapsed time: 2340.508s, Critical Path: 299.03s
  - with symlinks: Elapsed time: 2574.946s, Critical Path: 301.13s
    (one test failure in `//daml-script/export:integration-tests` - no such file error)
- incremental build after minor change (to `compiler/damlc/daml-compiler/src/DA/Daml/Compiler/Repl.hs`)
  - no symlinks:   Elapsed time: 1031.746s, Critical Path: 407.54s
  - with symlinks: Elapsed time: 1089.490s, Critical Path: 391.06s
- incremental test after minor change (to `compiler/damlc/daml-compiler/src/DA/Daml/Compiler/Repl.hs`)
  - no symlinks:   Elapsed time: 902.098s, Critical Path: 311.96s
  - with symlinks: Elapsed time: 931.320s, Critical Path: 322.02s
    (one test failure in `//daml-script/export:integration-tests` - no such file error)

This shows that, if anything, enabling symlinks makes the overall build and test slightly slower.
This only tested `--windows_enable_symlinks`.

Setting `--enable_runfiles` as well, which enables symlink based runfiles tree construction instead of manifest files, fails the build with
```
ERROR: C:/users/u/_bazel_u/w3d6ug6o/external/stackage/BUILD.bazel:490:22: HaskellCabalLibrary @stackage//:base64-bytestring failed: (Exit 1): cabal_wrapper.exe failed: error executing command
  cd C:/users/u/_bazel_u/w3d6ug6o/execroot/com_github_digital_asset_daml
  SET CC_WRAPPER_CC_PATH=external/rules_haskell_ghc_windows_amd64/mingw/bin/gcc
    SET CC_WRAPPER_CPU=x64_windows
    SET CC_WRAPPER_PLATFORM=windows
    SET LANG=C.UTF-8
    SET PATH=C:/Users/u/dadew/scoop/apps/msys2/current/usr/bin
  bazel-out/x64_windows-opt/bin/external/rules_haskell/haskell/cabal_wrapper.exe bazel-out/x64_windows-opt/bin/external/stackage/base64-bytestring_cabal_wrapper_args.json
Execution platform: @local_config_platform//:host
realgcc.exe: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
compilation terminated.
`cc_wrapper-bash.exe' failed in phase `C Compiler'. (Exit code: 1)
```
I have not further debugged this build failure.

Given that the timings above suggest that enabling symlinks causes an overall slow-down and that the Bazel documentation warns

> Note: Creating symlinks on Windows is an expensive operation. The --enable_runfiles flag can potentially create a large amount of file symlinks. Only enable this feature when you need it.

It seems like it's not worth pursuing this further.
