### ISSUE TITLE
handle concurrent-update race condition for DB-backed websocket queries

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#10334]
@S11001001 suspects/knows that we currently do not work correctly at read-committed level which is the default in both Oracle & PostgreSQL. I don’t quite remember the problematic case so @S11001001 please leave a comment :)

We should either change the serialization level (probably acceptable at least short term) or fix our code to handle read-committed.

**Comment by S11001001** [comment]
We'll have to do a little more than changing the serialization level.

The race condition is introduced by #8226, and slightly exacerbated by #9895 (because the below-described scenario becomes slightly more likely under read-committed).

It doesn't affect non-WS queries _because we don't return the offset_, so those can remain under read-committed just fine. However, with a websocket query:

1. Request Alpha starts.
2. Request Beta starts.
3. Alpha fetches and persists, and does compare-and-swap to save offset X. (This works under read-committed just fine.)
4. Alpha commits (#9895).
5. Beta fetches and persists, and does compare-and-swap to save offset Y. (Again, contention is solved by replay if C&S fails, and replay will start at offset X if Alpha won.)
6. Beta commits.
7. Alpha queries the database, which is caught up to offset Y.
8. Alpha reports its liveness as beginning at X, and starts the transaction stream at X.

One solution is as follows.

1. Start a transaction in tx level read-committed.
2. Discard the offset we wrote while persisting, and read all the offsets for all queried template-ID/party pairs.
    1. If they do not match, rerun fetch-and-persist with usual max-tries. (We already iterate _during_ fetch and persist to make sure they match, but it is possible that Beta breaks this invariant by persisting fewer offsets.)
    1. This is probably the messiest part; we currently neatly separate persisting from querying, but this interleaves them.
3. Query as normal.
4. Check the offsets _again_; if they don't match what we read in (2), restart from (1).
5. Report the query results.
6. Report the offset we read in (2) as the liveness marker. (By contrast, we currently report the one we persisted back in (3) of the race condition description.)
7. Start tx stream at liveness marker offset.

We can skip (4) if we run all the above in tx level serializable. (Again, there is no reason to change how we do fetch-and-persist.) I don't think it's worth it, though; most of the extra complexity is in step (2), and we'd _still_ have to handle tx conflicts in exactly the same way if we ran serializable.

**Comment by cocreature** [comment]
So in summary, the problem is that we report the live offset that we got while updating the database but then we do another query to return the result and the query in between could have changed.

And simply using the offset we get from querying doesn’t work because the other query (Beta in your example) could have updated only parts of the templates that we queried for so it’s not a consistent ACS offset.

So it seems like there are roughly two solutions:
1. The one you proposed which basically boils down to "retry until offsets are a consistent acs snapshot"
2. Switching things around, I think we could also do the following:
    1. Query the ACS and the offset for that ACS and keep the result in memory.
    2. Stream transactions and persist them and update the in-memory copy
    3. Return the in-memory copy and stream from that offset

While I think you might be able to make 2 work, it seems like a mess and keeping the whole acs in memory sounds like a bad idea so definitely in favor of your solution.

And I agree changing the serialization level doesn’t seem all that useful.

**Comment by S11001001** [comment]
> Check the offsets _again_; if they don't match what we read in (2), restart from (1).

There's a caveat to this: we _also_ have to check every offset for the same tpid but _different_ party; the ones for different parties don't have to be the same, but they can't be _newer_.

In case this test fails (party Bar has offset Y, we are querying for Foo which reached offset X, and Y > X), we should catch up to Y rather than latest. That's because of this sequence of events:

1. Alpha advances party Foo to X.
2. Beta advances party Bar to Y.
3. Alpha queries.
4. The ledger advances to Z.
5. Alpha discovers that party Bar on the same tpid has advanced past its expectations and needs to requery for Foo.
6. Alpha advances Foo to (Y or Z).
7. Beta queries.
8. Beta (finds Bar still on Y, Foo on Y) or (finds Bar still on Y, Foo on Z so must requery).

In fact we should generally be as conservative with the contention-triggered updates as possible, to reduce this form of contention. We already do this in one case with the `newAbsEndTarget`.

Tx level serializable obviates this scenario as well, though I believe it does it via failing at the query step. As with before, I think it is probably better to just do the extra offset checks ourselves, but that position is weaker now.
