### ISSUE TITLE
reach consensus on the semantics of maximum record time

### ISSUE THREAD

**Issue by bitonic** [digital-asset/daml#1068]
On issue #987 , it was highlighted that there are some disagreement on how the maximum record time mechanism should work.

As far as I can tell, there are two "camps":

1. The user can rely on the MRT putting a hard upper bound of that the transaction. Or in other words, the record time of the transaction will never be greater than MRT.
2. The user should use the MRT to implement its retry logic, but there is no hard guarantee that the transaction won't be committed later.

I think we all agree that number 1 is more desirable, and also more in line with what we have been advertising.

However @gaboraranyossy-da mentioned that there are corner cases where respecting 1 is difficult.

We should reach consensus and record the outcome here.

cc @meiersi-da @gerolf-da @gaboraranyossy-da

**Comment by gaboraranyossy-da** [comment]
The corner cases I was referring to originates from the Apollo/GSL architecture and they were inherited by the sandbox. In the latter it's fairly trivial to guarantee 1., which we now actually do.  Not sure if similar problems exist in Canton making it hard though.

**Comment by meiersi-da** [comment]
@francesco-da : why `never be greater than LET + MRT`? I would expect record time of transaction to be always lesser or equal to MRT. 

@gerolf-da: you mention in #987 that `max_ttl <= MRT - LET`. Can you explain (or point to an explanation) of why that should hold? 

@gaboraranyossy-da @gerolf-da : do we have a write-up on the time-model that we can use as a basis for this discussion? It would probably be helpful to paste that here in the conversation so that we have a shared foundation for the conversation.

**Comment by bitonic** [comment]
@meiersi-da you're right, edited.

**Comment by gerolf-da** [comment]
@meiersi-da: That invariant holds because that is what the sandbox explicitly checks. `max_ttl` is a configuration parameter that dictates that the difference between the user provided MRT and the user provided LET. See:
https://github.com/digital-asset/daml/blob/05e691f55852fbb207f0e43cf23bb95b95866ba3/ledger/ledger-api-common/src/main/scala/com/digitalasset/platform/services/time/TimeModel.scala#L46-L49

**Comment by gerolf-da** [comment]
Closing this because maximum record time has now been removed.
