### ISSUE TITLE
Extracting the contents of the `agreement` field of a contract instance through the Sandbox API

### ISSUE THREAD

**Issue by gyorgybalazsi** [digital-asset/daml#1110]
The `agreement` field of templates and contracts is what makes a DAML contract really useful in legal settings.

Would be nice to have the option to extract the contents of the `agreement` field through the Sandbox API and the Navigator UI.

**Comment by gerolf-da** [comment]
While adding a new field `agreementText` to the protobuf `CreatedEvent` is trivial, adding the field to the data types in the java bindings would be a breaking change. In particular:
* [`data.CreatedEvent`](https://github.com/digital-asset/daml/blob/8158269b7dde7d4995d5e0701725fdb97cef1e82/language-support/java/bindings/src/main/java/com/daml/ledger/javaapi/data/CreatedEvent.java) in the Java Bindings
  * new field of type `String`, requiring an additional constructor parameter => BREAKING CHANGE
* the [`Decoder`](https://docs.daml.com/app-dev/bindings-java/codegen.html#generate-the-decoder-utility-class) class generated by the Java Codegen
  * change decoder from `BiFunction<String, Record, Contract>` to `Function<CreatedEvent, Contract>` => BREAKING CHANGE
* the [`SomeTemplate.Contract`](https://docs.daml.com/app-dev/bindings-java/codegen.html#templates) class generated by the Java Codegen
  * change static method `fromIdAndRecord(String, Record)` to `fromCreatedEvent(CreatedEvent)` => BREAKING CHANGE

We *could* make the change backwards compatible by: 
* making the `Contract#agreementText` field `Optional[String]` instead of `String`.
* keeping and deprecating the existing methods mentioned above, always setting the agreement text to `None` (even if in fact there is an agreement text) or alternatively just an empty string, if we stick with the type `String`

Looking at `Template.daml`, the default `agreement` is an empty String. We could treat this as the `None` case for the `Optional`?
https://github.com/digital-asset/daml/blob/a244579470c948be1819b8bb70996a31a071d751/daml-foundations/daml-ghc/daml-stdlib-src/DA/Internal/Template.daml#L97-L98

I'd like to avoid that we set the agreement text of a contract to `None` or an empty string, simply because the user was using a deprecated method (i.e. `fromIdAndRecord` instead of `fromCreatedEvent`). Or is it enough to highlight this in the documentation?

**Comment by bitonic** [comment]
@gerolf-da I think the changes need not to be breaking if we keep everything optional, as you say.

However, we cannot just stick an empty string in: we must distinguish the case where we do not have the agreement text because the Ledger API didn't give it to us (or in any case because "we don't have it"), and the case where the agreement text is empty.

**Comment by gerolf-da** [comment]
> the case where we do not have the agreement text because the Ledger API didn't give it to us (or in any case because "we don't have it")

@bitonic: This would only be the case when using newer bindings with an older sandbox. I guess we want to cover this use case?

**Comment by gerolf-da** [comment]
Although, from a client binding perspective, we cannot distinguish between an empty string and "agreement" not set (because protobuf `string` is a primitive), unless we use something like the [`StringValue` wrapper](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto#L112).

**Comment by bitonic** [comment]
@gerolf-da that's solved by adding

```
bool hasAgreement = X;
bool agreement = string;
```

rather than just `agreement`.

**Comment by gerolf-da** [comment]
Meh, that's super ugly. Also, the `hasAgreement` will get accessor methods like `isHasAgreement`. I'd rather prefer the StringWrapper in that case or a dedicated message `message OptionalAgreement { string agreement = 1; }`

**Comment by bitonic** [comment]
@gerolf-da the boolean + field is a "pattern" of sorts in protobuf. i think it is the most idiomatic way of doing that. the wrapper is quite a bit more awkward, imo.

**Comment by gerolf-da** [comment]
We haven't yet employed that pattern in the Ledger API though. I guess there's always a first at some point :)

**Comment by bitonic** [comment]
@gerolf-da as far as I can tell we have never added a required string to the ledger API. so I don't think this pattern was ever relevant, unless I'm misunderstanding.

**Comment by gerolf-da** [comment]
The point is to make it **not required** / optional to support the use case of newer client + older sandbox.

I've quickly run through the change locally, and I think this pattern is worse than the `StringValue` wrapper. Why? Because the separate flag is easily overlooked, whereas accessing a field of a message type means it **must** be checked for presence first. Granted, this can also be "forgotten", but I think it's more clear from the type alone.

**Comment by bitonic** [comment]
@gerolf-da yes, my wording was poor.

Feel free to go ahead with the wrapper, but I'd call it `AgreementText` rather than `StringValue`. I'd wait for a few more instances before establishing this as a pattern and giving it a generic name.

**Comment by gerolf-da** [comment]
`StringValue` would come from the google's [wrappers.proto](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto#L112). But I don't mind using a dedicated message for this.

**Comment by bitonic** [comment]
@gerolf-da sorry, I completely missed that Google provides this wrapper already. In that case, using that seems like the sensible thing to do. Sorry about the back and forth. I should have clicked your previous link.

**Comment by gerolf-da** [comment]
My current proposal on how the `agreement` is displayed in Navigator:
![image](https://user-images.githubusercontent.com/29121423/57782385-68153f00-772c-11e9-91a4-230b59c71d0f.png)
