### ISSUE TITLE
Navigator should not die silently on the first run

### ISSUE THREAD

**Issue by moritzkiefer-da** [digital-asset/daml#112]
Currently navigator will search for the configuration file called `ui-backend.conf` (side note: This should probably not end up relative to PWD but somewhere in ~/.da, we should make sure that all tools agree on where they get their config file from) on the first run. If that file does not exist, navigator will create it but exit silently which is pretty confusing.

Navigator does technically write a note about this to the log file but it never tells users about the log file so this isn’t particularly helpful. I would also argue that information that users have to act upon should end up in stderr and not only in a log file.

In this particular case, I think it makes the most sense to have navigator create the config file but still start automatically. Forcing users to start it twice doesn’t result in a great UX.

**Comment by cocreature** [comment]
We just had another user in the public Slack that got confused by this and I also got confused by a very similar issue where navigator couldn’t connect to the sandbox. @rautenrieth-da It would be great if you could improve the UX here a bit by also showing fatal errors (no config file, no sandbox, …) on stderr instead of only writing them to a log file.
