### ISSUE TITLE
Support for explicit party specifications on WS endpoints

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#11200]
Currently, the JSON API does not support specifying parties explicitly. Instead it always infers them from the token.

This is convenient in a lot of circumstances but it causes issues in others. E.g., for Daml script if you have a token with `actAs = [Alice], readAs = [Public]` you always need to use `submitMulti [Alice] [Public]` because Daml Script cannot restrict the claims available for a submission to a subset of the token.

Adding optional parameters to the JSON API to specify `actAs` and `readAs` would solve this nicely while keeping the convenience.

**Comment by stefanobaghino-da** [comment]
@S11001001 can you have a look at this? Do you think there are reasons of concern for this ticket with regards to fitting this in the current design and/or cause regressions due to some edge case? The idea is not to override a token, but only to optionally restrict the parties that would issue a command to a subset of those contained in the token (with the HTTP JSON API to return an error if the intersection is empty).

**Comment by stefanobaghino-da** [comment]
@S11001001 I believe #11454 closes this, right? I don't think we want to add this to streaming endpoints fro the time being; if we do, we can track it in a separate ticket.

**Comment by S11001001** [comment]
I left it open specifically because #11454 excludes streaming endpoints.

**Comment by ray-roestenburg-da** [comment]
Split off https://github.com/digital-asset/daml/issues/15002 from this issue specific to the streaming endpoints.
