### ISSUE TITLE
PoC for interface hierarchies

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#11978]

**Comment by sofiafaro-da** [comment]
Idea is to have interfaces declare that other interfaces that are required, e.g.

  ```
  interface B requires A where
    ...
```
 
So that when a template `T` implements interface `B`, the template `T` must also implement interface `A`:


  ```
  template T
    with ...
    where
      ...
      implements A where ...
      implements B where ...
  ```

In LF, this means adding a repeated "requires" field in the interface definition, and checking that the required interface is correctly. 

Additionally, we want to change `EToInterface` and `EFromInterface` to also allow converting between the interface `B` and its superinterface `A`, or introduce new expression forms that allow converting between interfaces and their super-interface:

```
     A, B are typecons, 
     (A & B are interfaces and A is a superinterface of B),
     or (A is an interface and B is a template that implements it)     // current case
     Γ  ⊢  e : B
   -------------------------------
      Γ  ⊢  EToInterface @A @B e : A 

     A, B are typecons, 
     (A & B are interfaces and A is a superinterface of B),
     or (A is an interface and B is a template that implements it)
     Γ  ⊢  e : A
   -------------------------------
      Γ  ⊢  EFromInterface @A @B e : Optional B 
``` 

Then in daml we expose everything as nicely as we can via typeclasses. E.g. we make sure that `Implements B A` is satisfied, so you can treat `B` as if it were a template that implements `A`.

**Comment by sofiafaro-da** [comment]
This proof-of-concept has been implemented.
