### ISSUE TITLE
define custom surface syntax for contract keys

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#120]
@martin-drhu-da have we decided if we want to do this?

**Comment by martin-drhu-da** [comment]
For every chain `this.f1.f2.....fn` (`n >= 0`) of record projections on `this` appearing in the `key`, we compute a chain `key.g1.....gm` (`m >= 0`) of projections leading to the first chain. (This works because key expressions are restricted to trees of record constructors with chains of record projections on `this` at the leaves.) We store all of these chain pairs in a map. Then we go through the `maintainer` expression and replace all chains `this.f1.f2.....fn` by the corresponding `key.g1.....gm` chain. When the `this.f1.f2.....fn` is not found in the map, we throw an error. The case `n = 0` covers references to a plain `this` without any projections.

**Comment by martin-drhu-da** [comment]
I would qualify the approach above as robust and predictable. We need to make sure though, we throw understandable error messages when the maintainers expression refers to a projection on `this` not contained in the key expression.

**Comment by martin-drhu-da** [comment]
@neil-da I think we should use an associated type family for the `TemplateKey` class instead of a functional dependency, i.e.
```
class Template c => TemplateKey c where
  type Key c
  key : c -> Key c
  maintainer : c -> [Party]
```
This will give us a better user experience in many regards. It might be a bit more work to get this done, but I think the user experience will be worth it. What do you think?

@shayne-fletcher-da If we do it this way, the desugaring would change slightly but not too much. I'll write an explanation once we've reached an agreement.

**Comment by neil-da** [comment]
Associated types are represented in System-F as coerces which are a nightmare to wrap/unwrap since we don't have FC. I don't disagree with the user experience angle, if you want get it to work. Do make sure you sort it out for polymorphic things in TemplateKey too so we can keep the power to abstract.

**Comment by shayne-fletcher-da** [comment]
Discussed on #temp-contract-keys, we decided to make `maintainer` symmetric with `signatory`, `observer`. That is, in `maintainer e` we parse `e` not as a general expression, but rather a party sequence. So, `maintainer x, y` desugars to `maintainer @T{..} = concat [toParties x, toParties y]`. Also equivalent to `maintainer x; maintainer y`.

**Comment by martin-drhu-da** [comment]
Implementation is finished via https://github.com/digital-asset/daml/pull/343.
@akalburgi is working on the syntax highlighting.

**Comment by hurryabit** [comment]
All of this has been implemented. The rough edges that still need to be evened out are tracked in https://github.com/digital-asset/daml/milestone/9.
