### ISSUE TITLE
rename sandbox to "ledger"

### ISSUE THREAD

**Issue by bitonic** [digital-asset/daml#1253]
as we start using the SQL backend in production use cases, it doesn't make much sense to call it `sandbox`. we've agreed to simply call it `ledger` instead. the binary itself should be `daml-ledger`, and on the assistant it should look like `daml ledger`.

cc @associahedron

**Comment by bitonic** [comment]
people brought up that "ledger" might be confusing as opposed to ledgers distributed outside the SDK. i don't have any better ideas, but adding the discussion label to make it clear that the name is not set in stone.

**Comment by garyverhaegen-da** [comment]
Whatever the new name end up being, we should have at least one release that accepts both the new and old ways/names of running things (and prints appropriate upgrade instructions on using the old ones).

Is the SQL backend replacing the existing sandbox? Otherwise I'd suggest something like `daml ledger --backend postgres --postgres-uri postgres://username:password@host:port/db` and `daml ledger --backend mem`.

**Comment by bethaitman** [comment]
I think the name `ledger` is a bit confusing: it's pretty generic, and won't make sense in a lot of existing stuff in the docs. For example, in the quickstart guide: `To run the sandbox (a lightweight local version of the ledger)`.

on the other hand, it _is_ simple, and I do like straightforward things...

**Comment by associahedron** [comment]
@bitonic I like `daml sandbox` for the current behavior. We can always add more commands if we have more behavior, like calling `daml ledger` for a more general interface. (We can have the same executable/JAR be invoked w/ different commands names and passing different arguments, just need to add it in `releases/sdk-config.yaml.tmpl` )

**Comment by associahedron** [comment]
But in any case I don't have a strong opinion. If you feel renaming it to `daml ledger` is better, we can do that. We can hide the command `daml sandbox` and eventually remove it.

**Comment by bitonic** [comment]
> Whatever the new name end up being, we should have at least one release that accepts both the new and old ways/names of running things (and prints appropriate upgrade instructions on using the old ones).

absolutely -- I think the sandbox naming should work forever as a legacy name. much like the `--jdbcurl` flag.

> I think the name ledger is a bit confusing: it's pretty generic, and won't make sense in a lot of existing stuff in the docs. For example, in the quickstart guide: To run the sandbox (a lightweight local version of the ledger).

we've resolved to calling it `ledger-postgres` and `ledger-inmemory`. that should be less confusing, i think.

**Comment by associahedron** [comment]
> absolutely -- I think the sandbox naming should work forever as a legacy name. much like the `--jdbcurl` flag.
> 
> we've resolved to calling it `ledger-postgres` and `ledger-inmemory`. that should be less confusing, i think.

Ok, please update `release/sdk-config.yaml` as you see fit. You can hide the `sandbox` command by deleting its description, and it will still work on the command-line. Once you make the change we need to update `daml-helper` so that `daml start` still works (it needs to know where the sandbox jar is).

**Comment by gerolf-da** [comment]
We'll take care of the branding of sandbox as part of another work stream.
