### ISSUE TITLE
[BUG] JSON API does not handle tokens without a ledger id properly

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#13127]
# Affected Daml version

2.0.0

# Bug description

The JSON API misinterprets tokens without a ledger id as being user tokens and then the ledger fails because the token does not have admin rights when the JSON API tries to call listUserRights. The more worrying part is that the JSON API tries to have its own mechanism for distingushing tokens in the first place instead of relying on the same one used by the ledger.

```
{"https://daml.com/ledger-api": {"actAs": ["Alice"], "applicationId": "daml-script"}}
```

# To reproduce

`curl -X POST localhost:7500/v1/create -d '{"templateId": "Main:Asset", "payload": {"issuer": "Alice", "owner": "Alice", "name": "foobar"}}' -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwczovL2RhbWwuY29tL2xlZGdlci1hcGkiOnsiYWN0QXMiOlsiQWxpY2UiXSwiYXBwbGljYXRpb25JZCI6ImZvb2JhciJ9fQ.kTH9Q-M_gT8DAsy6x6IpgNVnDreDPpqrCl5_GO7myk0"`

# Expected behavior

The JSON API accepts this just like the ledger.

**Comment by stefanobaghino-da** [comment]
As mentioned off-band by @cocreature: the cause is probably the use of custom parsing functions (e.g. https://github.com/digital-asset/daml/blob/7fc1cd24417fccdd6234d19a685580616809cac2/ledger-service/http-json/src/main/scala/com/digitalasset/http/EndpointsCompanion.scala#L359) over the main library to handle this (e.g. https://github.com/digital-asset/daml/blob/7fc1cd24417fccdd6234d19a685580616809cac2/ledger-service/http-json/src/main/scala/com/digitalasset/http/EndpointsCompanion.scala#L214)

**Comment by realvictorprm** [comment]
This assumption most likely correct and I noticed myself that it maybe is possible to just replace the whole custom parsing we still have in there with just using the provided one from the ledger code. However I also noticed today before this issue appeared that we made some adjustments to the user tokens to make them securely distinguishable from custom claim tokens which I was not aware of so far.

**Comment by realvictorprm** [comment]
I would like to take care of this, but need to finish a different task first.

**Comment by S11001001** [comment]
The json-api implementation does need to know e.g. what actAs, readAs claims a token satisfies. Can the user management service tell us this for claim tokens?
