### ISSUE TITLE
Deprecation of da-assistant.

### ISSUE THREAD

**Issue by associahedron** [digital-asset/daml#1327]
Now that daml-assistant is public and has a signed windows installer, it's time to have a plan in place for the deprecation of the old assistant (da-assistant). Here is my proposal:

1. We maintain a brief period where we keep making SDK releases for both assistants, let's say until mid-June.

2. After this period, we only release new versions of the SDK for the new assistant, and we stop uploading the SDK to Bintray. (We don't remove what is already there, so users can still use the da-assistant for previous SDK versions.)

3. To mark this change, we increase the version number. The first daml-assistant-only release would be 0.13.0 (or perhaps we skip 13 and go straight to 0.14.0 in case of triskaidekaphobia).

4. Make a public announcement of the new assistant.

5. Release a final update to the old assistant that adds a warning on use, saying that the old assistant will not receive updates, and asking users to upgrade to the new assistant, by linking the users to the docs and to the announcement.

I think this gives a nice blend of backward compatibility (people can continue using da-assistant for older versions) and an impetus to upgrade (want newer features / an updated SDK? upgrade to the new assistant).

Once we move to 0.13.0, the SDK can move forward without da-assistant support, which should lead to simplifications all around. (And we already don't support it on Windows.)

**Comment by cocreature** [comment]
Sounds like a great plan, thanks for writing it up! My only question is about the timing of 4 and 5. I would suggest that we make the public announcement immediately and possibly also immediately release an update to the old assistant suggesting the new assistant and adding a warning that it will be deprecated soon since the announcement will probably not reach everyone. That way we should get more users for the new assistant during the migration period and can fix any issues or missing features in the new assistant before we then go to 1 and stop publishing to bintray and release a second update to the assistant that tells users that they now have to use the new assistant if they ever want to get an upgrade again.

**Comment by hurryabit** [comment]
I like the refined proposal. I suppose updating the old assistant the second time is very cheap.

**Comment by dasormeter** [comment]
We need to also include a final decision on whether we are including dockerised daml assistant in this migration plan as well -- at present the docker image is only getting `da` updates, but not `daml`

**Comment by cocreature** [comment]
The old assistant is dead :fire:
