### ISSUE TITLE
da-ghci always tries to build the target before opening GHCi

### ISSUE THREAD

**Issue by moritzkiefer-da** [digital-asset/daml#133]
It looks like the new `da-ghci` always tries to build the target if runfiles are enabled before it loads it in GHCi. This makes sense for `damlc` which has a bootstrapping process that actually causes it to depend on itself but it seems to happen for all targets even if they do not have any runfiles declared, e.g. `da-ghci //daml-assistant:daml`.

As a workaround you can use `da-ghci --data no //daml-assistant:daml`.

**Comment by associahedron** [comment]
Can we change the default be `--data no` or alternatively to depend on the target being built? I'd like to get rid of custom da-ghci scripts working around this issue.

**Comment by associahedron** [comment]
cc @cocreature @aherrmann-da

**Comment by aherrmann** [comment]
@associahedron Sure, we can change the default to `--data no`. 

> or alternatively to depend on the target being built

Can you elaborate? I don't understand what you mean by this.

**Comment by associahedron** [comment]
I meant that we keep a list of targets that require `--data yes`, so when you evoke `da-ghci` with those it does `--data yes` by default for those.

**Comment by aherrmann-da** [comment]
@associahedron Gotcha. Yes, that is possible. We could add an optional boolean attribute to `da_haskell_*`, say, `ghci_data`. If it's specified it defines the default behavior wrt. including runfiles in ghci, if not we default to `False`. In `da-ghci` we could then override that attribute if `--data` is passed by the user, and otherwise just do what the `ghci_data` attribute says. So, in the BUILD file you'd define the default behavior for a given target, and at the command line you can override it. What do you think of that approach?

**Comment by associahedron** [comment]
I just tested the latest master and it works perfectly! Thanks @aherrmann-da
