### ISSUE TITLE
Java-codegen only types that are actually referred to by templates/interface choices

### ISSUE THREAD

**Issue by S11001001** [digital-asset/daml#13324]
Considering #13308 it became apparent that the Java codegen generates every type [marked serializable] in the LF's signature. Instead, it might be better to only generate types that are referred to by a template [or interface choice], as the Scala codegen does.

Might find [re]use in the type-recursion-safe utilities in the `com.daml.codegen.dependencygraph` package in Scala codegen.

Would preclude (i.e. hide) #13308, as the type in question could not occur within a template payload or choice type.

**Comment by stefanobaghino-da** [comment]
> Would preclude (i.e. hide)

It wouldn't really because there's a similar problem on a serializable type there, but it could make sense to do this.

On the other end, I'm not entirely sure we _can_ really do this. Should we rather support generating code for a library that only contains data definitions but no templates? With interfaces coming along it could be that one might want to generate code for their own generic library and maybe build a Java library around it.

Would it make sense to maybe limit the code generation to data referenced in templates _but also_ allow to generate code for all other serializable data? I'm thinking of maybe preserving the current behavior for backward compatibility but adding a `--restricted` flag or something like that that restricts code generation to anything referred in a template in the DAR. Otherwise we can think about making a breaking change and only generate code that refers to a template and add an `--unrestricted` flag (giving a migration path for those who want to generate code for everything).

In any case, I'll have a better look at the underlying issue because I think it would be better if we could solve it.

**Comment by S11001001** [comment]
> Should we rather support generating code for a library that only contains data definitions but no templates? With interfaces coming along it could be that one might want to generate code for their own generic library and maybe build a Java library around it.

Thinking reductively, the reason that people want to generate code is to interact with ledger data. There is no cause for any data types outside those used in template payloads and interface choice signatures, in that case. Interfaces don't change this equation, because to be used at all in an interface, a data type must still concretely be referred to by the interface's signature.

Empirically, no one has requested the reverse of this feature for Scala codegen, which seems to bear out the above. Of course, people are more motivated to compile less Scala code :)

> only generate code that refers to a template and add an `--unrestricted` flag

I think this is likely enough to be what everyone wants that we could immediately deprecate such a flag, were it introduced. Having everyone include `--restricted` in their getting-started boilerplate that does who-knows-what works too, but seems a bit unhygienic.
