### ISSUE TITLE
[FEATURE REQUEST] Filter out Canton default packages from Navigator

### ISSUE THREAD

**Issue by shaul-da** [digital-asset/daml#13402]
### What is the problem you want to solve?

When I view templates and contracts in Navigator, typically I want to see those contracts that deal with my business workflow. Starting with Daml 2.0 the Navigator template and contract views get cluttered with Canton default contracts

### What is the solution you would propose?

Add a toggle that will hide default Canton contracts and only show user-defined contracts and templates. Alternatively, provide some mechanism to filter contracts by the template.

**Comment by stefanobaghino-da** [comment]
I would prefer if we could avoid having an ad-hoc definition of what a "default package" is so that those can evolve over time without us having to maintain some sort of list of default packages across team boundaries (which is prone to errors).

> Alternatively, provide some mechanism to filter contracts by the template.

The search box in the upper right corner allows you to do that. If that's enough for you, consider closing this ticket.

**Comment by ray-roestenburg-da** [comment]
Hi @shaul-da just checking in, does:

> The search box in the upper right corner allows you to do that. If that's enough for you, consider closing this ticket.

work as a solution for you?

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
