### ISSUE TITLE
[Engine] Benchmark for type checking

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#13411]
Before modifying extensively the type checking for #13410 we need to be sure we do not introduce significant overhead. For this purpose we need to benchmark the different phase of type checking (ideally separately)

**Comment by nickchapman-da** [comment]
It turns out we already have a good benchmark for type checking:

```
$ bazel run //daml-lf/validation:typechecking-benchmark -- -f 2 -i 10 -wi 10 -bm avgt -p darPath=<prod.dar>
```

```
# Run complete. Total time: 00:03:35
Benchmark                 (darPath)  (moduleName)  Mode  Cnt  Score   Error  Units
TypecheckingBench.bench  <prod.dar>                avgt   20  4.746 ± 0.116   s/op
```


This benchmark runs not only the `Typing` checks, but all static checks including `Collision`, `Recursion`, `DependencyVersion` and `Serializability`, however `Typing` is by far the dominant cost, which can be shown by duplicating the `Typing` check:

```
    Typing.checkModule(interface, pkgId, mod)
    Typing.checkModule(interface, pkgId, mod)
```

and re-running the numbers:

```
# Run complete. Total time: 00:03:35
Benchmark                 (darPath)  (moduleName)  Mode  Cnt  Score   Error  Units
TypecheckingBench.bench  <prod.dar>                avgt   20  7.459 ± 0.089   s/op
```

We calculate: `(7.459 - 4.746) / 4.746` --> 57%

**Comment by remyhaemmerle-da** [comment]
@nickchapman-da Thanks for double checking.
