### ISSUE TITLE
conformance test for interface

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#13655]
We need to add test for interface in the Ledger API conformance test (probably in ledger/ledger-api-tests/suites/src/main/scala/com/daml/ledger/api/testtool/suites/v1_8/SemanticTests.scala).

**Comment by stefanobaghino-da** [comment]
Asked in a face-to-face conversation, asking here for record-keeping to clarify: do we need interface support in the Scala codegen for this? /cc @S11001001 @ray-roestenburg-da

**Comment by S11001001** [comment]
@stefanobaghino-da Yes. (#13349 for reference)

**Comment by stefanobaghino-da** [comment]
@S11001001 I wanted to give @remyhaemmerle-da a chance to share his reply. To the best of my understanding, interface support is not a strict requirement. Happy to be told otherwise, of course. What I would like to understand is the impact of choosing not to support interfaces in the Scala codegen. How complex would it be to add tests without explicit Scala codegen support for interfaces?

**Comment by S11001001** [comment]
@stefanobaghino-da Honestly I would be happier to tell you that we don't need it 😅 

Under current interfaces, as long we invoked `resolveChoices` and the #13349 `TODO` in `packageInterfaceToScalaCode` is fixed, Scala codegen doesn't need "real" interface support to exercise choices. Because it will treat inherited choices exactly as if they were directly defined on the template. Under the #13653 proposal, this will stop working, since exercise commands will need interface IDs in them.

I suppose that if you did the above fixes, and the test tool assumed the exercises were invalid and patched in the interface ID in place of the template ID, it would be possible to get away with only making those fixes. Is this reasonable for the test tool? I'm not sure.

I don't see how the current codegen _with no changes_ could test interface exercise, though, but I don't know what @remyhaemmerle-da has in mind.

**Comment by remyhaemmerle-da** [comment]
There is another fix to be done in the codegen. 
The Exercise command should be called with the interfaceId where the choice is defined instead of the templateId. 
Currently the engine infer the interfaceId from the choiceName, but the plan is to disable this in #13653.

> I don't see how the current codegen with no changes could test interface exercise, though, but I don't know what @remyhaemmerle-da has in mind.

Theoretically, in the conformance tests we could write ledger API proto message directly by hand. 
I should have a look to see if it is possible in practice. 

If the "#13349 `TODO` in `packageInterfaceToScalaCode`"  is easy to fix I will, I would be pleased we did it sooner than later.

**Comment by S11001001** [comment]
Hopefully #13858 is enough to unblock this.
