### ISSUE TITLE
Allow JSON API to use a config file when run via `daml start`

### ISSUE THREAD

**Issue by georg-da** [digital-asset/daml#13943]
### What is the problem you want to solve?

I use `daml start` to start up the JSON API server and I'm using the following option in `daml.yaml`:

```
json-api-options:
  - --config=json-api.conf
```

This leads to the following error:
```
Error: Found both config file and cli opts for the app, please provide only one of them
```

This is likely due to `daml start` automatically setting other command line options.

### What is the solution you would propose?

I'd like to be able to use a config file for the JSON API when using `daml start`. Either the config file options are merged with the command line ones (and take priority), or command line arguments are ignored when a config file is provided.

### Describe alternatives you've considered

The workaround is to add the options explicitly as command line arguments, but this gets unwieldly when wanting to set many options.

**Comment by stefanobaghino-da** [comment]
Important: use the "command line arguments are ignored when a config file is provided" approach. The CLI options are deprecated and the error is there by design. Of course this should not happen. A possible solution is to ensure that the HTTP JSON API Service is launched by default using a reference configuration file for its default instead of CLI options.
