### ISSUE TITLE
Give the reason for failure on `mustFail` nodes in scenarios

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#1410]
For failing `submit` statements in scenarios, I get interesting error messages:

```
template Token
  with
    owner : Party
  where
    signatory owner

failing_test_1 = do
  alice <- getParty "Alice"
  bob <- getParty "Bob"
  submit alice do
    create Token with owner = bob
```
gives
```
Scenario execution failed on commit at Intro_2_Scenario:69:3:
  #0: create of Intro_2_Scenario:Token at DA.Internal.Prelude:377:26
      failed due to a missing authorization from 'Bob'

Last source location: DA.Internal.Prelude:377:26

Ledger time: 1970-01-01T00:00:00Z

Partial transaction:
  Sub-transactions:
     #0
     └─> create Intro_2_Scenario:Token
         with
           owner = 'Bob'
```

However, with a `submitMustFail`, the reason for failure is lost:

```
failing_test_2 = do
  alice <- getParty "Alice"
  bob <- getParty "Bob"
  submitMustFail alice do
    create Token with owner = bob
```
gives
```
Transactions: 
  TX #0 1970-01-01T00:00:00Z
     mustFailAt 'Alice' (Intro_2_Scenario:69:3)

Active contracts: 

Return value: {}
```

I would like the `mustFailAt` node to contain the reason for failure and, if possible, the partial sub-transaction up to the failure. According to @francesco-da , `submitMustFail` should not return any of this to the `Scenario` context, though so its purely for visual inspection.

**Comment by bame-da** [comment]
@mjstewart has proposed to contribute a very similar feature:

> Given a choice performing many validations using `assertMsg`, I want the ability to write a test to assert that the expected validation clause triggers. Currently, `submitMustFail` provides a simple yes/no (did this fail or not) without being able to determine the exact cause of the failure. This may be misleading and hide potential validation logic bugs.
> 
> This proof of concept introduces a new keyword `submitMustFailMsg` which enables the developer to supply the exact string of the expected failure message. When the `Update` fails, the text provided to the corresponding `assertMsg` is inspected and compared to the expectation. Given the above snippet, the user will receive feedback to pin point the issue should the expected error message not match what was actually thrown.
> 
> ```
> Scenario execution failed:
>   A must-fail commit aborted due to an unexpected failure message
>   expected: "must be over 18"
>   actual: "loan value must be at least 120.00"
> ```
> 
> # Discussion
> Before submitting the implementation for review or creating an issue.
> 
> ### 1. Does this feature have potential or is it fundamentally a bad idea?
> See comments in `SExpr.scala`
> 
> > this is on purpose very limited, with no mechanism to inspect the exception, nor a way to access the value returned from 'body'.
> 
> This implementation provides a way "around this".
> 
> ### 2. syntax and naming
> Many unit testing libraries have the ability to perform string comparisons on the failure message. Besides exact equality, `startsWith` is often useful. Some proposed options
> 
> `submitMustFailWithMsg` (alternative to submitMustFailMsg but may be clearer wording on what it does)
> `submitMustFailWithEqMsg` (be clear that its Eq rather than just Msg)
> `submitMustFailStartsWithMsg`
> 
> Alternatively, to increase flexibility in use cases, a predicate could be provided.
> 
> `submitMustFailMsg alice (== "must be over 18") ...`
> 
> However this may complicate implementation and reduce the readability of error messages in daml studio.
> For example, if any predicate is accepted, the best you could do is report that the assertion failed due to the predicate not holding, whereas if the scope is reduced to string equality and `startsWith` then precise reasons could be communicated.

After a bit of back-and-forth, I think we should change the LF-inbuilt behind `submitMustFail` to return a string error message, and then implement the current `submitMustFail`, a version that returns a `Text`, and the concise "submit and compare" helpers that @mjstewart suggested.

@hurryabit @gerolf-da , please confirm whether this seems sensible to you, as you will ultimately need to review and approve PRs.
@mjstewart your contribution on this would be more than welcome. Once @hurryabit and @gerolf-da agree on design, just follow https://github.com/digital-asset/daml#contributing-to-daml and assign a PR for @hurryabit and @gerolf-da to review.

**Comment by hurryabit** [comment]
I generally agree with adding this feature and the approach how to add it. We should however _add_ a new builtin to DAML-LF which acts like `submitMustFail` but also returns the error message. The old builtin backing `submitMustFail` must stay in place without changing its type for compatibility reasons. Regarding the surface syntax, I'm in favour of exposing
```
submitMustFailMsg : Party -> Update a -> Scenario Text
```
and
```
submitMustFailWith : Party -> (Text -> Bool) -> Update a -> Scenario ()
```
The final names of these functions are still debatable from my end.

**Comment by gerolf-da** [comment]
Hey @mjstewart, great initiative and a very welcome contribution. No objections from my side and I'm looking forward to reviewing the PR. Let us know if we can be of any help or assistance along the way.

**Comment by mjstewart** [comment]
Hey @gerolf-da, @hurryabit

Before a potential PR, I'd like to discuss if my implementation looks feasible before continuing.

1. I have modified DAML-LF to introduce.

`submitMustFailMsg : Party -> Update a -> Scenario Text`

It will return the text message of a user initiated error via `abort or assert` captured in a `DamlEUserError`.

2. Added `assertPrefix` to `DA.Assert`

Its common for error messages to begin with an actual message followed by a dump of the record payload which
isn't really needed for the purpose of identifying the test failure reason.

Combined with `assertEq`, I imagine these 2 assertions will handle 99% of use cases. Any other assertion can be manually
implemented since this new feature extracts the error message.

## usage examples

I find the reverse bind syntax nice to represent this compactly by feeding in the actual error message
into the assertion.

```
  scenario do
    ...

    assertEq "age must be over 18" =<<
      submitMustFailMsg owner do
        exercise _helper TestHelper_Run with age = 18
```

Alternatively, the long hand form looks like this for flexibility.

```
scenario do
  ...

  actual <- submitMustFailMsg owner do
    exercise _helper TestHelper_Run with age = 18

  assertMsg "must end in over 18" $ Text.isSuffixOf "over 18" actual
```

## How to add tests?

Id like to add a couple of tests in `compiler/damlc/tests/daml-test-files`.
Is this the best place to add them? if so how can I get these tests to pickup the new keyword and assertPrefix?
```

Variable not in scope:
    submitMustFailMsg
  Perhaps you meant ‘submitMustFail’ (imported from Prelude)
```

Thanks for your feedback

**Comment by hurryabit** [comment]
Hi @mjstewart,

your branch looks already great. Thank you so much. I've left a few comments on things we'd need to improve before merging this.

Regarding the tests: We should definitely add a test in `compiler/damlc/tests/daml-test-files`. You need to add a `@SINCE_LF 1.dev` pragma to the top of your `.daml` files, as in https://github.com/digital-asset/daml/blob/77c8c7ce776cfc2fd13f1269758845ca37035bdb/compiler/damlc/tests/daml-test-files/Map.daml#L4. The addition of `submitMustFailMsg` should be automatically picked up then.

There are also be other places where we should add tests. @gerolf-da or @remyhaemmerle-da can tell you where.

**Comment by hurryabit** [comment]
FYI @cocreature.

**Comment by remyhaemmerle-da** [comment]
@mjstewart 

The branch looks very good. As explained by @hurryabit, you need to handle the versioning of this new feature. I let extra comments about that.  

Thank you very much

**Comment by mjstewart** [comment]
@hurryabit @remyhaemmerle-da. I have applied your feedback and the changes can be seen in https://github.com/digital-asset/daml/compare/a212966..cb64eff#diff-e259efac0238c8c88ae4633872aef024R39

Now these feature flags are in, I get the following error in daml studio when I point to local 0.0.0 daml-sdk-head. Is this what should happen now?

```
ScenarioBackendException {scenarioNote = "Failed to create scenario context", ... "Scenario.mustFailAtMsg" is not supported by DAML-LF 1.Stable(7)".
```

2 other outstanding questions

1. The recommended change for this section
https://github.com/mjstewart/daml/commit/a2129665a2ad9176c589f3531722064e3d31fe2b#r37208283

2. Are adding docs with examples a welcome inclusion to the PR?
I assume submitMustFailMsg wont show up in the search bar unless the feature flag is enabled?

**Comment by hurryabit** [comment]
@mjstewart The error message should go away if you put
```
build-options:
- --targert=1.dev
```
into your `daml.yaml`. However, I'm surprised you could use your new functions without doing that. Are they already hidden behind the feature flag?

I've replied to the comment referenced in 1.

Adding docs would be a welcome inclusion. Adding damldoc comments would be great, everything beyond that would be icing on the cake.

**Comment by hurryabit** [comment]
@mjstewart I've just been made aware that I had a typo in the snippet you need to put it your `daml.yaml` in the comment above. I've fixed it inline. Apologies for that.

**Comment by mjstewart** [comment]
I think we are almost good to progress this to the next phase of raising PR. Should I merge in latest upstream master before doing so? I'll then add the special change log tags to the squashed commit.

Regarding the docs, I have tested via `docs/scripts/preview.sh --gen` and `--pdf` and all looks good except for the search bar. 

I suspect this is because the localhost doc server search bar is still using all the function definitions in `base.html` from `https://docs.daml.com/daml/reference/base.html` rather than localhost which contains the new function. I change it myself to localhost and `submitMustFailMsg` is in there which would imply the search bar would see this new function when deployed.

**Comment by cocreature** [comment]
Hi @mjstewart,  thank you so much for your work on this! I’ve left a couple of comments on your PR but I think it’s best if you open a PR at this stage. That allows us to comment on the current state of your PR rather than trying to find the commit that introduced a change and commenting on that. We do need to rebase on master and ime that’s usually easier if you do it regularly rather than trying to do it all at the end. However, we can do that after you’ve opened the PR and I’m happy to help you with that or just take care of it whatever you prepare.

With regards to the docs, I think your diagnosis is correct. I wouldn’t worry about this.

**Comment by bame-da** [comment]
Hey @mjstewart I don't think you ever opened a PR for this. It would be a shame not to get your valuable work into the SDK. Is there any way we can help you to get this over the finish line?

**Comment by mjstewart** [comment]
hey @bame-da and daml team, my apologies for the delay. Id still love to progress this work further. 

I'll perform the rebase and create a PR so its easier to track and discuss.

**Comment by hurryabit** [comment]
We won't add any new features to scenarios anymore but it might be a good idea to add something similar to DAML Script. cc @cocreature
