### ISSUE TITLE
Drop warning for divulged contracts for contracts that have been disclosed on submission.

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#14168]
We currently get the warning `Tried to fetch or exercise ${contract.templateId} on contract ${cid.coid} but none of the reading parties [${readers}] are contract stakeholders [${stakeholders}` for contracts that have been disclosed on submission.` This should be dropped.

**Comment by cocreature** [comment]
> we can get rid of the warning, when we add readAs rights to the respective party and do a submitMultiDisclosing. This makes sense to me, but we might want to change the warning message.

I might be misunderstanding your proposal but we cannot just add parties to `readAs`. Explicit disclosure works at a contract level not as a party level. We only want to disable the warning for contracts passed via explicit disclosure not for all contracts visible to an additional party.

I think this might be another thing that is relatively easy to solve if we move disclosed contracts into speedy since then it becomes easy to distinguish whether a lookup is against a disclosed contract or not.
