### ISSUE TITLE
Contract Visualization from DAR/DALF

### ISSUE THREAD

**Issue by akalburgi** [digital-asset/daml#1438]
Input: Dalf file
Output: Text Document

Reading from DALF can done using existing tools from `daml-lf-ast` in combination with Rules in `daml-foundations`.

From AST process all choices, and if a choice is resulting in a new contract with TemplateType (Identifier) we recursively continue, and a way to avoid processing the same template identifer again. (Q. how do i know which template to start with ?)

Like that we should be having all the possible templates a given template can give rise to, we capture this information and produce a tree-like structure (something similar to the transaction tree we have in vs code now). And write that to a file as the first pass. 

The next step would be to produce a text document (some markup like language which can be embedded in docs or produce images) like plantuml (http://plantuml.com). I choose this because I have used it before, but open to suggestions, please let me know if they're better once (Plant UML does have a haskell library https://github.com/elongeau/plantuml).  Probably this might be complicated, not sure of a way yet. 

Interface:
`damlc generate visual` possible options `--image --text`

**Comment by garyverhaegen-da** [comment]
I've never had a reason to use it myself, but a lot of people seem to choose the [DOT](https://www.graphviz.org/doc/info/lang.html) language for graph representations ([Haskell bindings](http://hackage.haskell.org/package/graphviz)). I've also had some success using the Tikz language myself, though that does imply bringing along the entire TeX toolchain.

I would expect contracts to form full graphs (as opposed to trees) since we have non-consuming choices.

**Comment by akalburgi** [comment]
We have this working now. as of version `0.13.5`
