### ISSUE TITLE
ResetService is not protected against concurrent calls

### ISSUE THREAD

**Issue by gabor-aranyossy** [digital-asset/daml#1491]
Reset can be called multiple times concurrently resulting in undefined behaviour. See: 
https://github.com/digital-asset/daml/blob/be0a8110a9b9025a528b01b462552f9c2a889cb0/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/services/SandboxResetService.scala#L43

The logic should be protected by some kind of semaphoring to avoid this.

**Comment by gaboraranyossy-da** [comment]
@bitonic fyi

**Comment by stefanobaghino-da** [comment]
@SamirTalwar-DA I believe you greatly improved how we handle this. When you have two minutes, if applicable, can you close this and possibly reference the PR that fixed this.

**Comment by SamirTalwar-DA** [comment]
Sandbox (Sadbonx) now uses the `ResettableResourceOwner`, which uses an `AtomicReference[Option[Promise[Unit]]]` both as a semaphore and as an excuse to nest types far more than you would think would be reasonable.

The code is here, and hasn't changed since at least v1.0.0:

https://github.com/digital-asset/daml/blob/a2d785e3ee29c56b2b06780897fc7407666767f8/libs-scala/resources/src/main/scala/com/digitalasset/resources/ResettableResourceOwner.scala#L33-L55

Sandbox Classic is still prone to this kind of issue, but I think we can ignore that.
