### ISSUE TITLE
JS bindings: error with interface contract id choice return value

### ISSUE THREAD

**Issue by GeorgSchneider** [digital-asset/daml#15042]
# Affected Daml version

SDK snapshot `2.4.0-snapshot.20220909.10591.0.33f2ea59`

# Bug description

When calling a choice using the JS bindings @daml/react library I get an error if the choice is returning a contract id for an interface, suggesting that it's looking for the implementing template rather. The error is:
```
Uncaught (in promise) Error: Failed to look up template 05c9e15562ce6a84d76bdd5a97c38830ff949f4195a46b0e13fed2ba6b42461e:Daml.Finance.Instrument.Base.Instrument:Instrument. Make sure your @daml/types version agrees with the used Daml SDK version.
    at lookupTemplate (index.js:253:1)
    at index.js:310:1
    at index.es5.js:430:1
    at andThen (index.es5.js:135:1)
    at Decoder.decode (index.es5.js:429:1)
    at Decoder.decode (index.es5.js:517:1)
    at Decoder.decode (index.es5.js:746:1)
    at decodeValue_1 (index.es5.js:551:1)
    at index.es5.js:557:1
    at Array.reduce (<anonymous>)
```

My `@daml/types` version definitely agrees with the SDK being used, so the error is a bit misleading.

The calling line in the below repro steps is this one: https://github.com/digital-asset/daml-finance-app/blob/92f3869eac2773029d989f3c3952eff2007d9bf6/ui/src/pages/structuring/other/NewBase.tsx#L48
The choice being called is this one: https://github.com/digital-asset/daml-finance-app/blob/92f3869eac2773029d989f3c3952eff2007d9bf6/src/daml/Daml/Finance/App/Structuring/Auto/Service.daml#L25

You can see it returns an interface contract id `ContractId Instrument.I`, but the error refers to the actual template being instantiated (which is this one: https://github.com/digital-asset/daml-finance/blob/5663dd105dbb324bc7ae1e96c90f7ddbd9625266/src/main/daml/Daml/Finance/Instrument/Base/Instrument.daml#L17 ). Since the UI only depends on interface packages, it should not require the implementing template to be known.

Note that the actual choice call succeeds, the error seems to be coming from off-ledger components (ie. JSON API or JS bindings).

# To reproduce

```
git clone git@github.com:digital-asset/daml-finance-app.git
cd daml-finance-app
git co ui-decoupling
make
daml start
```

Once the sandbox has started up, run in a separate console:
```
cd ui
npm install && npm start
```

1. A browser should open with a scenario selection screen.
2. Select the "Default" scenario, and a page showing the parties and relationship should appear.
3. Click the `Issuer` box and you should get to the `/apps` page showing different modules.
4. Select the `Structuring` module and choose `New` -> `Other` -> `Base Instrument` on the next page.
5. Enter any `id` and `description` and hit `Create Instrument`
6. Open the Chrome dev console and observe the error

# Expected behavior

I expect no error to be thrown and the choice call to not require any reference to the implementation package.

**Comment by GeorgSchneider** [comment]
In another case I got back an additional error (before the one described above appeared):
```
{
    "kind": "DecoderError",
    "input": [
        {
            "archived": {
                "contractId": "00bf7f99faacb2c8d609b7cc02189555325f9878fbcadc28ac19dfd04fd2fba2f4ca00122093fdada3b2c8e1c3c9135c20414fe31a9d270e66cbc83a426906399c33cb8e82",
                "templateId": "8e0e4f359d0f65be65883ff8bd047511f33b97b0ead9d6b47e10a681879e95f7:Daml.Finance.Holding.Fungible:Fungible"
            }
        },
        {
            "created": {
                "agreementText": "",
                "contractId": "00dbbf3c9188932c341c4d1b641f2b9fa151b4ffaf9af1f28e5898eb29ef36d35eca0012205afea1c6d87b07055e0e5df9e30f2e38bcbc875d87befaef2b85ea498fb67774",
                "observers": [],
                "payload": {},
                "signatories": [
                    "Alice-Default::1220f56ddee7582972abae5f5ae1d1749d91df0501a9ec5ba85fbb2b86b2e81d956b",
                    "CentralBank-Default::1220f56ddee7582972abae5f5ae1d1749d91df0501a9ec5ba85fbb2b86b2e81d956b"
                ],
                "templateId": "80730c99080e1324ebc6bfce5b5df66e6bbfc05858631852ae971c4f623bf41f:Daml.Finance.Interface.Holding.Transferable:Transferable"
            },
            "matchedQueries": [
                0
            ]
        },
        {
            "created": {
                "agreementText": "",
                "contractId": "00c20cedbd9fcee0b691a49ef5a1698215ec2c023cbcba5853c15a88ffd8f19084ca001220594615aefeccde84eb259aa498066d591021ea356ab7b7022faad890a5537476",
                "observers": [],
                "payload": {},
                "signatories": [
                    "Alice-Default::1220f56ddee7582972abae5f5ae1d1749d91df0501a9ec5ba85fbb2b86b2e81d956b",
                    "CentralBank-Default::1220f56ddee7582972abae5f5ae1d1749d91df0501a9ec5ba85fbb2b86b2e81d956b"
                ],
                "templateId": "80730c99080e1324ebc6bfce5b5df66e6bbfc05858631852ae971c4f623bf41f:Daml.Finance.Interface.Holding.Transferable:Transferable"
            },
            "matchedQueries": [
                0
            ]
        }
    ],
    "at": "input[0]",
    "message": "expected a value matching one of the decoders, got the errors [\"at error: the key 'created' is required but was not present\", \"at error: the key 'created' is required but was not present\", \"at error.archived.templateId: expected \"80730c99080e1324ebc6bfce5b5df66e6bbfc05858631852ae971c4f623bf41f:Daml.Finance.Interface.Holding.Transferable:Transferable\", got \"8e0e4f359d0f65be65883ff8bd047511f33b97b0ead9d6b47e10a681879e95f7:Daml.Finance.Holding.Fungible:Fungible\"\"]"
}
```

The interesting bit here is that the `archive` event contains the concrete implementing template, not the interface value (which my UI doesn't recognize, only depending on interface packages). I suppose this is related to the fact that there is no archive on interfaces?

**Comment by S11001001** [comment]
@ray-roestenburg-da In the case of such a choice exercise, the `payload` (and `key` if present) are in an invalid format, and there is no way to correct that fact. No _static_ contradictions arise from this format mismatch. However, dynamically speaking, if:

1. this choice exercise happens
2. another module loads with a dependency on the concrete codegenned template
3. it makes the dynamic mapping of `templateId` to an assumption about the payload structure (i.e. `x.templateId = Instrument` ==> cast `x.payload` to `Instrument`)

This latter assumption may fail for some templates, and there is no way to detect this in advance. We can:

1. emit the bad payload anyway
2. replace the payload with `{}` (this invalidates the assumption in a different, but possibly less insidious way)
3. discard the whole `{created: ...}` for that contract. Therefore there is no wrongly structured data, just...missing data

What makes the most sense to you? (The same applies to the key.)

**Comment by S11001001** [comment]
> git co ui-decoupling

@GeorgSchneider Could you restore this or another named branch to a commit that reproduces this?

**Comment by GeorgSchneider** [comment]
@S11001001 Yes, sorry I didn't think about it when merging.

The branch is now restored, check out commit `92f3869eac2773029d989f3c3952eff2007d9bf6` on it to reproduce.

**Comment by S11001001** [comment]
> In another case I got back an additional error

@GeorgSchneider This error is unrelated; I have spun it off to #15055.

**Comment by S11001001** [comment]
> What makes the most sense to you? (The same applies to the key.)

In discussion with @ray-roestenburg-da we loosely settled on option (2).

Related to #2925.

**Comment by S11001001** [comment]
@da-tanabe As a factor of #2925, any constraints on options 1-3 that come to mind?

**Comment by da-tanabe** [comment]
In #2925, I merely point out that collapsing an arbitrary number of events into one singular event (that may or may not have been the one the user cared about) seemed odd, given all the possible things that could happen when a choice gets exercised. I think #2925 may have also predated the TypeScript APIs (certainly the issue doesn't consider it at all), and if I understand _this_ issue correctly, this is focused on a decoding problem in TypeScript _after_ reading from the websocket query stream.

It's not clear to me whether this issue contemplates a wire format change or not. If we _are_ talking about potentially changing the over-the-wire API:

1. Least surprising, particularly for users that are using the Websocket API directly instead of using codegen, and presumably since these users are not using codegen, they are probably not doing anything where distinguishing between ambiguous values is relevant.

2. Makes it obvious to codegen that its attempts to parse a `CreateEvent` are likely to fail, but it may appear buggy to users that are using the websocket API directly. I can't imagine anyone is _really_ using these events besides indirectly through `.archive()` and `.archiveByKey()`, and of course in this case, the payload format of a `CreateEvent` is irrelevant)

3. Would be fine as solution consistent with the concern I raised in #2925. But I have no idea how you would then handle `.archive()` and `.archiveByKey()`, since in these cases you _do_ care more about the event than the choice return value; this alone probably makes (3) unworkable. (Changing the API to _only_ return `ArchiveEvent`'s _purely_ to support these archive calls seems unpalatable too.)

If we _aren't_ talking about changing the websocket API, and this is merely a question of what the TypeScript bindings should do, then (2) is probably the most "correct" thing to do, but (1) is probably more closely aligned with the spirit of JavaScript. (And again, I think (3) is actually unworkable because of `.archive()`.)

Either way, it seems like the `CreateEvent` object returned over the query stream is no longer going to be the same kind of `CreateEvent` as returned in a choice exercise (`CreateMetadataOnlyEvent`?); if they are fundamentally different things, then they should probably have different decoders, which I think sidesteps this issue.

**Comment by S11001001** [comment]
> if I understand _this_ issue correctly, this is focused on a decoding problem in TypeScript

@da-tanabe Correct.

> _after_ reading from the websocket query stream

Not quite, only the exercise response events.

> It's not clear to me whether this issue contemplates a wire format change or not. If we _are_ talking about potentially changing the over-the-wire API

We are not. But most of the same considerations apply.

> I can't imagine anyone is _really_ using these events

I agree. But I didn't even consider the `archive()` question (though since you brought it up I address it below), so wouldn't be surprised if there were other more-or-less obvious considerations to JS users that I can't see at all.

> But I have no idea how you would then handle `.archive()` and `.archiveByKey()`, since in these cases you _do_ care more about the event

We are only considering transforming/eliding `CreateEvent`s, so the archive events relevant to these methods would not be affected.

> (1) is probably more closely aligned with the spirit of JavaScript

In the sense of "unpredictably wrong data sometimes appears in weird situations", absolutely. But maybe users would be happier with this? 😕 

> if they are fundamentally different things

I don't see them as so different, because the _type_ of `payload` in events returned from `exercise` _et al_ is `object`. This really is about dynamic expectations.

**Comment by S11001001** [comment]
> 2\. replace the payload with `{}` (this invalidates the assumption in a different, but possibly less insidious way)

As of ada2af8807945bc869feba01194cac540268b4e8 this is what #15050 will do.
