### ISSUE TITLE
DotRecordSyntax should work on SrcLoc

### ISSUE THREAD

**Issue by kpinter-da** [digital-asset/daml#15142]
# Affected Daml version

1.18.0, 2.4.0

# Bug description

Daml can't find HasField instances for SrcLoc fields.

# To reproduce

1. load this snippet in Daml Studio:
```
module Main where

import DA.Stack

f : SrcLoc -> Text
f SrcLoc{..} = srcLocFile -- works fine

g : SrcLoc -> Text
g s = s.srcLocFile
```
2. produces error:
```
/.../Main.daml:9:7: error:
    • No instance for (DA.Internal.Record.HasField
                         "srcLocFile" SrcLoc Text)
        arising from a use of ‘getField’
    • In the expression: (getField @"srcLocFile" s)
      In an equation for ‘g’: g s = (getField @"srcLocFile" s) typecheck
```

# Expected behavior

DotRecordSyntax should work on SrcLoc.

**Comment by stefanobaghino-da** [comment]
@moisesackerman-da Your thoughts?

**Comment by akrmn** [comment]
@stefanobaghino-da it turned out to be way easier than I expected, PR #15163 should do it.
@kpinter-da thank you for raising this!

**Comment by kpinter-da** [comment]
@akrmn is it known why SrcLoc doesn't get HasField instances generated by Daml? I saw that the PR adds them manually, and it made me wonder why the compiler can't do this for us.

**Comment by akrmn** [comment]
@kpinter-da that's a good question, let me break down the answer:

* The `HasField` instances are generated by the [`recordDotPreprocessor`](https://github.com/digital-asset/daml/blob/main/compiler/damlc/daml-preprocessor/src/DA/Daml/Preprocessor/Records.hs#L8) step
* Another preprocessor step [`checkImports`](https://github.com/digital-asset/daml/blob/main/compiler/damlc/daml-preprocessor/src/DA/Daml/Preprocessor.hs#L168-L170) checks that a module doesn't import any internal modules
* Currently, for each module, we either [run all preprocessor steps or none](https://github.com/digital-asset/daml/blob/main/compiler/damlc/daml-preprocessor/src/DA/Daml/Preprocessor.hs#L96-L99)

Since `DA.Stack` does import an internal module (`GHC.Stack.Types`), we [explicitly disable the preprocessor for it](https://github.com/digital-asset/daml/blob/main/compiler/damlc/daml-preprocessor/src/DA/Daml/Preprocessor.hs#L57-L68). We could instead be more clever about which modules use which preprocessor steps, but the simple approach has worked so far and adding a few instances manually here and there isn't that painful.
