### ISSUE TITLE
Show doesn't escape Text

### ISSUE THREAD

**Issue by kpinter-da** [digital-asset/daml#15177]
# Affected Daml version

2.4.0

# Bug description

`Show` doesn't escape `Text`. [The docs say that](https://docs.daml.com/daml/stdlib/Prelude.html#class-ghc-show-show-65360):
> The result of show is a syntactically correct expression

The lack of escaping leads to syntactically incorrect expressions.

# To reproduce

1. run following Daml script in Daml Studio:
```
module Main where

import Daml.Script

data A = A { a : Text } deriving Show

main : Script ()
main = script do
  debug A {a = "hello \"world"}
```
2. script result shows:
```
Trace: 
  A {a = "hello "world"}
```
Which is obviously syntactically incorrect as there is an unterminated string literal.
# Expected behavior

The above snippet should print:
```
Trace: 
  A {a = "hello \"world"}
```

**Comment by stefanobaghino-da** [comment]
@akrmn your thoughts? (doesn't mean we need a fix right now, I only want to understand the issue -- if it's a 5 minutes fix and you want to have you or the team work on that on the side, that's fine with me of course 🙂 )

**Comment by akrmn** [comment]
@stefanobaghino-da, it's not too hard to fix, we can adapt `instance Show Char where { showList }` from GHC. There are two tricky parts though: Daml doesn't have a `Char` data type, so our version will need to use either `Int`s or `Text`s of length=1 to represent individual characters. The other one is performance, since lazy algorithms don't always translate to strict languages, but the GHC code doesn't do anything too magical, and arguably we should care about correctness first, performance second.
