### ISSUE TITLE
Improve interpretation error consistency

### ISSUE THREAD

**Issue by basvangijzel-DA** [digital-asset/daml#15529]

**Comment by dylant-da** [comment]
A bit of context on this issue:

There are some error handlers in GHC typechecker, Haskell-side LF typechecker, and Scala-side LF-typechecker that ultimately implement the same checks.

This is intentional, in order to be certain that errors will be detected, even in the presence of malformed Daml-LF or regressions.

However, some error-conditions which are essentially identical are detected and reported differently. This tries to bring the errors in line with one another, to the extent possible.
