### ISSUE TITLE
Projection: use transactionFilter in test BatchSource

### ISSUE THREAD

**Issue by ray-roestenburg-da** [digital-asset/daml#15658]
The test BatchSource can take `E => Option[Identifier]` to get an identifier  and `E => Seq[String]` to get stakeholders. The filter logic can then use these to apply the Projection it's transactionFilter. For `CreatedEvent` and `_ <: Contract[_,_]` these could be provided automatically (fromCreatedEvents, fromContracts)

**Comment by chunlokling-da** [comment]
Is it correct to say:

- Only batch source for testing purpose will use transaction filter to filter the batch?  We don’t filter with transactionFilter for those non testing batch source because the ledger api should filter the event with trasactionFilter already

 - When we say Test batch source, we meant the first 3 create / apply defs in the object BatchSource right?

**Comment by chunlokling-da** [comment]
Discussed with @ray-roestenburg-da , 
Yes to below

> Only batch source for testing purposes will use transaction filter to filter the batch?
> When we say Test batch source, we meant the first 3 create / apply defs in the object BatchSource right?

Not exactly right to

> We don’t filter with transactionFilter for those non testing batch source creation because the ledger api should filter the events with trasactionFilter already

We currently also do filtering with transactionFilter for those non testing batch source
