### ISSUE TITLE
Projection: Improve design of handling `setX` on preparedStatement in BindValue

### ISSUE THREAD

**Issue by ray-roestenburg-da** [digital-asset/daml#15705]
From @S11001001: 

https://github.com/DACH-NY/projection/pull/82/files/3f2f0d58c7ac9bbed1cc36fb0a08c2b625a531ac#diff-c1421f884df4067660f885f334c1e38f5a723d12f63fe58fd4f8f410368807c5R148-R167

Could the valid domain be described with a typeclass?

1. `setObject` and other pitfalls like `java.sql.Date`
2. I think line 166 you want induction; the typeclass style makes this obvious
3. if we want this at the surface of the API we can do a map like `(value: T): PSSet[_ >: T]` so Java users can have the exciting runtime lookup behavior

**Comment by S11001001** [comment]
@ray-roestenburg-da Since we might not do this, some questions that arose that I thought we would address with the typeclass:

https://github.com/digital-asset/custom-views/blob/a8ed1f4cd93e2fe3efe3a8691376221ebd728ec0/src/main/scala/com/daml/projection/javadsl/JdbcAction.scala#L182-L183

Does `Types.NULL` always work here, or is this argument supposed to be the underlying (nullable) type? (The typeclass could just get the "right" int statically to deal with the `None` case, but there is no way to do that in Java without an explicit argument. _Well_, we could specially handle `ju.OptionalInt` _et al_, but these are just some corner cases.)

https://github.com/digital-asset/custom-views/blob/a8ed1f4cd93e2fe3efe3a8691376221ebd728ec0/src/main/scala/com/daml/projection/javadsl/JdbcAction.scala#L184

Shouldn't this be recursive, e.g. call `setInt` on an Int, `setString` on a string, &c, rather than unconditionally using `setObject`?

**Comment by ray-roestenburg-da** [comment]
@S11001001 
> Does Types.NULL always work here, or is this argument supposed to be the underlying (nullable) type? (

This can depend on the JDCB driver, so far I've seen it work with PostgreSQL but we can add more tests to make sure.

> Shouldn't this be recursive, e.g. call setInt on an Int, setString on a string, &c, rather than unconditionally using setObject?

Yes, though I left that for now. setObject should work, but it is a lot better to call the right method. Again this is dependent on the JDBC driver, AFAIK the PostgreSQL driver supports this.
