### ISSUE TITLE
Investigate structured error messages in GHC 9.6

### ISSUE THREAD

**Issue by basvangijzel-DA** [digital-asset/daml#15899]

**Comment by dylant-da** [comment]
It appears that the new errors have an existentially-qualified variant which allows us to emit custom formatted errors at any stage. This is useful because it means errors from different stages are actually expressed as a datatype, which means future tooling should be able to consume them more easily.

However, the constraint error system still segments constraints into several groups (by severity & by source location) before running error detectors over them, and those detectors tend to ignore the latter constraints, which makes looking for errors that match our criteria difficult, since they may end up ignored somewhere in the pipeline in favour of others.

The silver lining is that this means it hasn't changed from 8.8.1, so at least our workarounds for the error detector should be relatively easy to port to 9.6.
