### ISSUE TITLE
Investigate functionality for using Daml Script in IDE and command line

### ISSUE THREAD

**Issue by basvangijzel-DA** [digital-asset/daml#15900]
- Being able to stop a Daml script run
- Being able to run a single test

Have a look at https://github.com/digital-asset/daml/labels/developer-experience

This is to make sure we can push this with the GHC team, when re-forking a future GHC.

**Comment by basvangijzel-DA** [comment]
Daml gas (as in the cost of running programs) might interact with when we want to stop a test, possibly automatically.

**Comment by basvangijzel-DA** [comment]
@dylant-da 
What would be some reasonable requirements/features we want?

**Comment by dylant-da** [comment]
The new work with bidirectional and cancellable Scripts has laid the groundwork for later having gas, resumable scripts, and others.

Regarding difficulties, the conclusion I've drawn over the last weeks reading & modifying our code is that our current approach for running scripts inside the IDE is problematically intertwined with Shake - the main entry point for running a script is to dispatch to Shake actions, and the way our testing system runs tests is to call out to Shake. The reason for this is running a script needs build artifacts in order to actually run. However, the test run itself is not a build artifact.

I would prefer to call to Shake to provide the build artifacts we need to run a test, and then provide those artifacts to the actual script running system. This won't take too much time, I expect, because most of our script running is already in its own modules, and there is a relatively thin wrapper for running them in Shake. There are a few questions to be answered around how the IDE should be modified to call out to the script system and bypass Shake, but these are mostly technical and not too hard.

**Comment by dylant-da** [comment]
Closing now that #16588  is merged - work on spinning out script runner will continue in #16772 .
