### ISSUE TITLE
DAML Nanobot design

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#1615]
There is a desire from people like @bame-da to have "Rainfall style" DAML Nanobots - ones that don't call out to web servers, parse JSON etc, but just prod a few contracts. Below is a straw man design for them, at the LF layer. We would then sugar them in DAML.

### Dynamic type

```
data Dynamic
mkDynamic : a -> Dynamic
fromDynamic : Dynamic -> Maybe a
```

### Nanobots

```
data Message r1 r2
    = Create Time Dynamic -- the contractid and contract being created
    | Archive Time Dynamic -- the contractid and contract being archived
    | Completed Time r1 (Maybe r2)

nanobot
    : (Message r1 r2 -> s -> (Maybe (r1, Update r2), Maybe s))
    -> s
    -> Nanobot
```

A left-fold over the ACS nanobot that processes creates/archives and returns an optional update (what to run) and an optional state (next step). It observes all creates/exercises and whether a requested update succeeds/fails.

### Scenarios

```
runNanobot :: Party -> Nanobot -> Scenario ()
dump :: IsContract c => Party -> Scenario [c]
```

A way to run a nanobot within the scenario, and dump all the active contracts.

@bame-da - we think this is feasible, and not a huge amount of work. You wouldn't be able to do IO, read a file, parse JSON or anything else "interesting". Is that still useful? What percentage of nanobots would it cover? Is that percentage high enough?

**Comment by bame-da** [comment]
I've discussed Georg, Thomas and Andrae. All agree that it would replace 100% of nanobots as they define nanobots to be those pieces of automation that purely introspect ledger state. Regarding volume of total app code:

Thomas and Georg say

> at least 50%, for some applications you might not even need other bots anymore

Andrae gave me an overview of the Spider code, on which I did an analysis. Their `app` has 23000 lines of Scala. Of those, 5400 are the nanobot framework and some 3000 pure nanobots. So 35% is a lower bound. However Andrae says there are some nanobot-like things elsewhere so the actual number may be a bit higher.

Thomas and Georg further pointed out that it's not just about the volume, but

> I’d argue that writing as much as possible in a single language is superior.

**Comment by bame-da** [comment]
Given the above numbers, I think this is well worth doing. With a nice DAML surface syntax and the Application API the runtime team is working on, this will open the door to applications consisting of just DAML + UI.

**Comment by neil-da** [comment]
I'd like to get a considered opinion from @hurryabit and @bitonic before proceeding.

**Comment by bame-da** [comment]
Further confirmation from the refapps team:
Gergely:
> I think this could replace most of the bots we have. The contractkeys would replace the lookup bots and this one could replace the "if you see this contract do that" types. 

Gabor:
> I agree [...] - for the supply chain ref app, this would surely make all the bots obsolete

**Comment by hurryabit** [comment]
I think writing NanoBots in DAML is a great idea. Building a NanoBot executor based on our DAML-LF interpreter seems feasible. I'm tempted to say it's the quickest way to start experimenting with a UX for DAML NanoBots. My only concern is execution speed, particularly when the state the NanoBot amasses gets quite big. But I'm confident this is something we can solve over time.

**Comment by bitonic** [comment]
@neil-da what would you like me to opine on?

1. The specific API for nanobots you proposed here;
2. The `Dynamic` type that would need to be added in DAML-LF;
3. Whether I think that DAML Nanobots are a good idea at all?

**Comment by ndmitchell** [comment]
All three, with 3 then 2 the most important.

**Comment by bitonic** [comment]
OK, I'll try to keep it as concise as possible, from most high level to least.

## Are DAML nanobots a good idea?

I think they're **not**. Two main reasons:

### One language, but not really

We would be heading towards a DAML split-brain scenario of two languages that look the same but are not the same at all. One is the DAML we know which compiles to DAML-LF. The other would be bona-fide Haskell.

These languages would appear side-by-side _in the same file_, with DAML being incompatible with the Haskell ecosystem, with the Haskell optimizer, cabal, and so on. They would take completely different compilation paths. This would be particularly subtle if we allow code reuse (which as far as I understand is a major goal of this proposal). Code will be compiled twice with subtly different semantics.

Moreover, we would be controlling one compilation path, which is messy but fairly well behaved (the one through DAML-LF), while for the other compilation path we'd be at the mercy of GHC, which is even messier (no disrespect!) and outside our control.

### We need integration anyway

The other problem with this proposal is that it pushes the challenges posed by integration further down the roadmap. We absolutely _need_ a smooth way to integrate DAML contracts and workflow with existing programming languages. We currently have decent solution, and are working on others (e.g. the JSON / HTTP API), but we're clearly not there yet.

Empowering people with DAML nanobots will do a lot of good for the first few weeks of development, since application development will be easier, but will not help very much in the long run, when inevitably the workflows become more integrated with the real world.

## Is the proposed API good?

I would need to write a few programs in it before passing judgement. I'm not sure I'm a big fan of using types to identify nanobots though.

## Is `Dynamic` for DAML-LF a good idea?

**Yes**. It will take a bit of care though.

In your example, I presume that doing something like

```
foo : \/(a : *) -> Dynamic -> Maybe a = /\(a : *). \(x : Dynamic). fromDynamic @a x
```

Is legal. However, this requires us to carry type evidence around a lot more than we'd like, or at least a lot more than I'd like.

I think we have two ways of doing this in a "nice" way. The first one is to go the `Typeable` route:

```
TypeRep : * -> *
typeRep : \/(a : *) -> TypeRep a -- `a` must be a closed type.
mkDynamic : \/(a : *) -> TypeRep a -> a -> Dynamic
fromDynamic : \/(a : *) -> TypeRep a -> Dynamic -> Maybe a
```

This keeps this mechanism somewhat composable. The alternative is to just say

```
mkDynamic : \/(a : *) -> a -> Dynamic -- `a` must be a closed type.
fromDynamic : \/(a : *) -> Dynamic -> Maybe a -- `a` must be a closed type.
```

Note that proposal 2 is implementable in terms of proposal 1.

In either case, this is a _bit_ of work. Not a huge amount, but it's work: we need to come up with the `TypeRep` in question and take care that things are nice and sound.

**Comment by bame-da** [comment]
@gerolf-da , discussion on DAML Nonobots here.

**Comment by bame-da** [comment]
I have evolved the initial design into an implementation using the Haskell Bindings. It's somewhat different to @neil-da 's original proposal in that the ACS is maintained in DAML, not the runtime.

The code, with a simple example can be found here: https://github.com/bame-da/hs-bot

**Comment by cocreature** [comment]
Closing in favor of more specific issues now that we actually started implementing it.
