### ISSUE TITLE
Allow Contract IDs in Contract Keys

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#1645]
We currently have two issues highlighted by @nickchapman-da :

1) Relative Contract Ids aren't allowed in contract keys:

```
template K
  with
    p : Party
  where
    signatory p

template T
  with
    p : Party
    c : ContractId K
  where
    signatory p

    key this : T
    maintainer key.p

t = scenario do
  a <- getParty "A"

  submit a do
    k <- create K with p = a
    create T with p = a; c = k
```

raises

```
  CRASH: Trying to create contract key with relative contract id RelativeContractId(NodeId(0))
```

2) Contract keys aren't allowed in `lookupByKey` and `fetchByKey`:

```
t = scenario do
  a <- getParty "A"
  
  c <- submit a do
    create K with p = a

  tc <- submit a do
    create T with p = a; c

  submit a do
    t <- fetch tc
    fetchByKey @T t
```

raises

```
  CRASH: Unexpected contract id in key: AbsoluteContractId(0:0)
```

All in all, this is pretty poor UX. Either we allow cids in keys, or not. I'm in favour of supporting it.

**Comment by oggy-** [comment]
We'd need to be careful with allowing relative contract IDs as parts of keys:
1. in Canton, transactions are chopped up into several parts, and each part is represented by the DAML expression generating its action. A participant may get to see only a portion of a transaction. If the generated relative contract IDs are stored anywhere, then the different participants need to generate the same relative contract ID. Actually, this might be a general problem with Canton and contract keys
2. since relative contract IDs are not unique, this might lead to unintuitive key uniqueness violations

**Comment by gerolf-da** [comment]
Superseded by #3634.
