### ISSUE TITLE
Unbounded in-memory intermediate decimals in calculations

### ISSUE THREAD

**Issue by drewharding-da** [digital-asset/daml#1729]
Multiply/divide: we have problems with intermediate decimals being bounded. amount = round(price * quantity, 2). We really need to do this with a specified rounding method, rather than calculate an invalid mantissa - and use multiply/round/divide involving more potential overflow states. We really can't use scientific form for financials.

**Comment by bitonic** [comment]
@drewharding-da do you mean something like `A * B / C`, where `A * B` overflows, and `A * B / C` does not?

In any case, there are two ways to solve this problem: either we allow users to express multiple operations at once -- i.e. we define an expression language for decimal's algebra -- or we increase the precision. Not entirely sure what's best.

Also see #1706

**Comment by filmackay** [comment]
> do you mean something like A * B / C, where A * B overflows, and A * B / C does not?

Yes exactly.

> In any case, there are two ways to solve this problem: either we allow users to express multiple operations at once -- i.e. we define an expression language for decimal's algebra -- or we increase the precision. Not entirely sure what's best.

Is increasing the precision? How did you arrive at the specification for Decimals - was it driven by SQL dbs?

Could we have two types: one persisted (SQL friendly) and an unbounded version that can't be, but is produced by math operations? Just spit-balling here..

**Comment by bitonic** [comment]
@filmackay yes, having two types is a valid option. However I fear it would be fairly subtle / unpleasant to users...

@gerolf-da what do you think about this?

**Comment by gerolf-da** [comment]
@filmackay: is this what you are thinking about?
`Decimal`: bounded, serializable, usable in templates
`UnboundedDecimal`: unbounded, **not** serializable, **not** usable in templates

Users who want to make use of `UnboundedDecimal` first have to convert a `Decimal` to it, do the calculations, and then later convert back to `Decimal` with a well defined or user provided rounding method for using the value as a template field, choice parameter, exercise return value.

**Comment by bitonic** [comment]
@gerolf-da that's one idea that's been floated in the past. I think it's appealing on paper, but it would be quite a bother. It would especially be a bother if we decide to be OK with unbounded `Decimal`s everywhere.

If we do we're basically pushing the responsibility of storing those decimals correctly onto third parties. Note that contract authors can make sure that `Decimal`s in their contracts are within certain bounds manually, although of course that'd be tricky.

**Comment by gerolf-da** [comment]
> It would especially be a bother if we decide to be OK with unbounded Decimals everywhere.
Does "if we decide" refer to a potential decision down the line sometime in the future?

**Comment by bitonic** [comment]
@gerolf-da sorry, that was a poorly phrased sentence.

What I meant is: compared to how smooth / pleasant the experience would be if we just made all `Decimal`s unbounded, the "two types" option seems pretty unattractive.

There's also the option of silently converting back and forth `Decimal` to `UnboundedDecimal`, but that's unpleasant for other reasons, imo...

**Comment by gerolf-da** [comment]
Yes, a single unbounded decimal type is the preferred option with respect to user experience.

I'm relatively strongly against silently converting back and forward. These are just subtle bugs waiting to bite us and more importantly our users.

So the problem with unbounded decimals everywhere is that it is harder to implement tools like extractor correctly?

**Comment by bitonic** [comment]
Me and @gerolf-da talked a bit more about this, I'll write a summary of our discussion here.

### Why is `Decimal` bounded anyway?

When me and @hurryabit specified DAML-LF we assumed that us or third-parties were going to store `Decimal`s in databases, and we wanted to make sure that all contracts could be stored unconditionally. Then we picked the gcd for the precision that's supported in `NUMERIC` -- MSSQL supports a precision up to 38 digits, most likely because it fits in 128bits ( https://docs.microsoft.com/en-us/sql/t-sql/data-types/decimal-and-numeric-transact-sql?view=sql-server-2017 ).

Once we had the max precision, we didn't want to specify a type-level scale, mostly because Java / Scala would have a hard time representing that. So we analyzed a few currencies and other similar quantities that are relevant to the financial world and picked a scale of 10 as a decent compromise.

However this is proving problematic, as witnessed by this issue and #1706.

### Possible solutions

#### Introduce an unserializable `UnboundedDecimal`

This is proposed by @gerolf-da in https://github.com/digital-asset/daml/issues/1729#issuecomment-504976935 . It solves this issue but not #1706, so it's not an option.

#### Change the scale of `Decimal`

This does not really work because for issues like #1706 we'd have to make the the scale huge (17 in that case), leaving us with a fairly restrictive integral part.

#### Introduce a serializable `UnboundedDecimal`

This would work, but then we're taking on the risk of people not being able to store contracts in their database in a sane way -- they'd have to store numbers as string, or most likely they'd store them as `NUMERIC` while losing data.

Note that now that the extractor works with a single JSON column this scenario is a bit less concerning, but if possible I'd still like to make it easy to store DAML contracts on a wide range of databases.

Also note that we could simply turn `Decimal` into `UnboundedDecimal`, as follows:

* Before introducing this change, we can safely assume that all `Decimal`s that were ever serialized were of at most precision `38`, scale `10`.
* We change the range of the `Decimal` type to be unbounded;
* We keep all the old `Decimal` primitives working as before, with an additional check to make sure that the inputs are at most precision `38`, and scale `10`, and keeping the rounding of the outputs. This way all the old code keeps working.
* We introduce new primitives that works in an unbounded way.

I believe the above plan would be safe, but I'd have to double check with @remyhaemmerle-da and @S11001001.

#### Parametrize `Decimal` over the scale

Essentially, we'd have

```
Decimal : (s : Nat) -> * -- s <= 38
```

instead of

```
Decimal : *
```

This would basically be equivalent to the `NUMERIC` type in SQL, but with a fixed precision. I believe that in this case, too, we could get away with "upgrading" the existing `Decimal` type rather adding a new one.

I've come to believe that that's the most desirable option as of today. We cannot represent the type faithfully in Java / Scala, but we can set them up correctly at runtime by setting the scale and precision in the constructors, and I think that would be perfectly fine for the overwhelming majority of users (in fact I'd bet most users would not even notice).

It would require a bit of work on the DAML-LF spec and DAML-LF compiler, but IMO it gives the best outcome.

**Comment by bitonic** [comment]
@remyhaemmerle-da pointed out that "upgrading" the existing decimal without persisting the type-level scale would be a significant departure from what we've been doing things up to now.

For example, for records and variants we serialize the type constructor even if we do not need it. Along the same lines one would expect for the scale to be serialized.

**Comment by S11001001** [comment]
> We cannot represent the type faithfully in Java / Scala

We can do nats with singletons, Scala 2.13 literal types, or zero/succ in Scala, including arithmetic if we want scaled operations. That's not necessary, though; at minimum we can just derive the scale check (e.g. when constructing a record with a specific scale set in its decimals) implicitly.

> I believe the above plan would be safe

Yes.

**Comment by gerolf-da** [comment]
@drewharding-da: @remyhaemmerle-da is working on introducing a new numeric type with fixed precision of `38` and a user definable scale.

**Comment by cocreature** [comment]
We have BigNumeric now
