### ISSUE TITLE
UP-20 Review error messages that can occur at runtime upgrade

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#17647]
We should review all the error that can be triggers by upgrading contract.

Here are some non exhaustive list of issue that may be necessary to tackle.
- In case of change of ensure clause definition the system fail, but do not make it clear it is because of the upgrade that it fails (Note that in general case we cannot if it really a problem of  upgrade as we may not have the original package)

**Comment by basvangijzel-DA** [comment]
See https://github.com/digital-asset/daml/pull/17610#issuecomment-1790949941.

We should handle the error better for dropping/adding non-optional fields.

**Comment by basvangijzel-DA** [comment]
Can use https://docs.google.com/document/d/1qsWtp9rdrGhYn_yER3aDwvUtvPyqw66LFJR3hlRR3rE/edit as a base.

**Comment by samuel-williams-da** [comment]
@carlpulley-da Given we now force the source package to be vetted in 2x (or, with tristate vetting, we force it to be accessible)
It may now be possible to tell the difference between a failed variant/enum downgrade, and an actual lookup failure, by looking up the missing variant in the source package.
Please look into this before plumbing all lookup failures. If this turns out to be possible/reasonable, it would be best to implement new Upgrade errors for both types of these failed downgrades (variant/enum), and push them through.

**Comment by samuel-williams-da** [comment]
We will have to rethink this in 3x.

**Comment by samuel-williams-da** [comment]
Remy has informed us that errors thrown from the engine must always assume data is well formed, and thus those lookup errors are always upgrade failures. In that case, we should add the error types and always use them in import value

For preprocessing, its unknown, it would be best to simply send back a lookup error there, with some subtext saying "This might be a failed downgrade"
