### ISSUE TITLE
Check that all deps are either 1.16 to upgrade or must remain identical for <=1.15

### ISSUE THREAD

**Issue by dylant-da** [digital-asset/daml#19704]
@paulbrauner-da This came up in the Upgrades task list. We're not sure if this is already implemented, do you happen to know if the participant already does this?

**Comment by dylant-da** [comment]
HERE YOU GO SAM!

**Comment by samuel-williams-da** [comment]
Discussed this with Paul, we have logic that checks that dependencies don't change in LF1.15 at use site (not at upload), since this is where the actual issue would arise, i.e. being used in a template.
This means that one _could_ add another LF1.15 package with the same name and version in an upgrade as a dep, but this is acceptable.

**Comment by samuel-williams-da** [comment]
Relevant links:
https://github.com/digital-asset/daml/blob/2fc45b862c6a53f502e10942902aa6b127e46888/sdk/daml-lf/validation/src/main/scala/com/digitalasset/daml/lf/validation/Upgrading.scala#L519
https://github.com/digital-asset/daml/blob/639655f568bcee217c5848730ad8037789a79882/sdk/canton/community/participant/src/main/scala/com/digitalasset/canton/participant/admin/PackageUpgradeValidator.scala#L102
