### ISSUE TITLE
Include damlc version in generated DAML-LF

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#2167]
This will help validating the generated DAML-LF in the future.

**Comment by cocreature** [comment]
We do already include the SDK version in the manifest file in the DAR, see https://github.com/digital-asset/daml/blob/623e641ec9742a6b5f7f8245fa486839ad5ba4e9/compiler/damlc/daml-compiler/src/DA/Daml/Compiler/Dar.hs#L175. Not quite what this issue is asking for but depending on the usecase it might be sufficient.

**Comment by hurryabit** [comment]
I consider this sufficient until people ask for having it in the DALF as well.
