### ISSUE TITLE
`damlc docs` rst format generates invalid links when using `--template`

### ISSUE THREAD

**Issue by jberthold-da** [digital-asset/daml#2468]
```
$ daml damlc docs --combine -f rst -o test.rst DamldocLinks/A.daml 
$ more test.rst 
.. _module-damldoclinks-a-74126:

Module DamldocLinks.A
---------------------

Data Types
^^^^^^^^^^

.. _type-damldoclinks-a-k-98362:

**data** `K <type-damldoclinks-a-k-98362_>`_

  This is K in A, containing ``Text``
  
  .. _constr-damldoclinks-a-k-55127:
  
  `K <constr-damldoclinks-a-k-55127_>`_ Text
  
$ echo '{{body}}' > fubar
$ daml damlc docs --combine -f rst -o test.rst DamldocLinks/A.daml -t fubar
$ more test.rst 
.. _module-damldoclinks-a-74126:

Module DamldocLinks.A
---------------------

Data Types
^^^^^^^^^^

.. _type-damldoclinks-a-k-98362:

**data** `K &lt;type-damldoclinks-a-k-98362_&gt;`_

  This is K in A, containing ``Text``
  
  .. _constr-damldoclinks-a-k-55127:
  
  `K &lt;constr-damldoclinks-a-k-55127_&gt;`_ Text
  

$ 
```

**Comment by associahedron** [comment]
HTML-escaping is really a *built-in feature* of mustache templates (see [the manual](https://mustache.github.io/mustache.5.html)). You can avoid it by using `{{{body}}}` or `{{& body}}` in the template instead of `{{body}}`, which should solve your problem.

There's no way to disable automatic escaping short of modifying templates ourselves, which is probably not something we should do, but it's probably worth doing.

**Comment by associahedron** [comment]
Closing for now since this isn't a bug and we shouldn't fix it.

If we run into the problem of users repeatedly using `{{body}}` instead of `{{{body}}}` in spite of damldocs docs (which don't yet exist), we can revisit this.
