### ISSUE TITLE
HTTP JSON API use SSL/TLS for connection to ledger

### ISSUE THREAD

**Issue by leo-da** [digital-asset/daml#2540]
We should not allow sending credentials (JWT) on unecrypted channels (HTTP).

Sandbox supports TLS and there supposed to be examples how to use Ledger API to connect to Sandbox over SSL/TLS.

## ACs:
- All communication between HTTP JSON API gateway and Ledger has to go over SSL/TLS,

**Comment by garyverhaegen-da** [comment]
Note that a lot of web deployments do not handle TLS at the app level, but rather use a TLS termination endpoint as some sort of proxy or load balancer in front of the app itself, with the connection between the proxy and the app going through plain HTTP (typically with an `X-Forwarded-For` header so the app can still check the connection was made over HTTPS, assuming it trusts the proxy).

Also note that not allowing credentials over unencrypted channels means no testing of browser apps in local development (browsers don't trust self-signed certs and CAs generally don't deliver certs for localhost), or at least a much higher bar for initial setup (e.g. installing an additional CA and/or a DNS redirect from a more reputable hostname to localhost).

So, assuming direct access from a browser client to a ledger server is something we want to support, I think we really should support:
1. A CLI flag to accept credentials over plain HTTP; this could have a scary name if required, such as `--leak-passwords-firesheep-style`.
2. A "behind proxy" mode where the app requires HTTP requests to have an `X-Forwarded-For` header that specifies an HTTPS scheme.
3. A "direct connection" mode where the app requires HTTPS at the protocol level.

If we do not want to support direct client access and expect people to write their own server-side app connecting to the ledger as a backend, then I suppose supporting only 3 can make sense.

**Comment by da-tanabe** [comment]
Some of these problems are also going to have be solved for the gRPC API because gRPC mandates HTTPS when dealing with credentials, which may imply TLS needs to either be terminated at the app level or terminated and re-established at the load balancer, then terminated again at the app.

Given the constraints with gRPC and the eventual need to authenticate that as well, I see having a local CA or self-signed cert as an unavoidable hurdle that users must go through if they wish to use authentication locally (which they should). It's not _too_ difficult to install a CA cert locally, so I think the daml assistant should have some mechanism for generating the appropriate files, and possibly a command for installing the CA for environments where this is allowed, and a command to at least show the CA cert or a path to it where users need to install it manually.

**Comment by leo-da** [comment]
@moritzkiefer-da Your thoughts on this? DAML Assistance feature proposal in the form of github issue?
> so I think the daml assistant should have some mechanism for generating the appropriate files, and possibly a command for installing the CA for environments where this is allowed, and a command to at least show the CA cert or a path to it where users need to install it manually.

**Comment by S11001001** [comment]
Split @garyverhaegen-da 's ideas on connecting to json-api as a client to #5572; this issue will focus on json-api ↔️ ledger API connection.
