### ISSUE TITLE
Enum with single value not supported as LF enum

### ISSUE THREAD

**Issue by tweber-da** [digital-asset/daml#2818]
It's not possible to use an enum with a single value in DAML that would translate to a LF enum, e.g. `data myEnum = myEnumA`. The recommended workaround is to write `data myEnum = myEnumA ()`, but this translates to a variant.

**Comment by cocreature** [comment]
Given that the original restriction was imposed since it was unclear whether `data X = X` should desugar to a record or a variant before we had enums, it seems sensible to lift that restriction now since (at least to me) it is clear that this will desugar to an enum.

What do you think @hurryabit, @bame-da?

**Comment by bame-da** [comment]
👍

**Comment by cocreature** [comment]
This sadly appears to be a bit more tricky than I expected:
Afaict in GHC Core `data X = X {}` and `data X = X` end up looking exactly the same and I definitely don’t want to desugar the former into an `Enum`. We could track which types were declared as records at the source and then use that but that seems a bit ugly.

**Comment by jberthold-da** [comment]
I am currently looking into this single-constructor Enum question for our project, just discussed it with @filmackay again.
A possible workaround is to add a second `DONOTUSETHIS` constructor but that looks pretty poor - it would show up in generated code and get in the way of any pattern matching in DAML.

> Afaict in GHC Core `data X = X {}` and `data X = X` end up looking exactly the same and I definitely don’t want to desugar the former into an `Enum`.

@hurryabit @cocreature I'd like to understand what would be the drawback of treating `data X = X {}` as an enum.
Obviously the resulting java and scala code generated from such data would show this decision, but I struggle to see the utility of an empty record over a singleton enum.
Even if there is a valid use case for empty records, I believe the Enum case is far more common.

**Comment by cocreature** [comment]
I think we absolutely should support single-constructor enums generated from `data X = X` and afaik @associahedron has started to work on this already or will soon. I don’t think we should change `data X = X {}` for two reasons:

1. It will break a lot of ledger API clients.
2. If I explicitly use record syntax in my data type definition, I expect to get a record. It seems much more confusing to me to have `data X = X {}` produce an enum.

**Comment by jberthold-da** [comment]
I understand there might be code that breaks - that is usually the case when the compiler changes.
But why would anyone _want_ an empty record in the code? I struggle to see how that would be important. 
Overall it seems like an accidental artefact not really worth keeping.

**Comment by jberthold-da** [comment]
This is somewhat circular: "Why would anyone _want_ ..." answered by "Why would anyone _write ... if they did not want ...".

**Comment by cocreature** [comment]
Fair enough, so let me try to give a better explanation:

I don’t think a record with no fields is less useful than a singleton enum. Both are isomorphic to unit so you could argue that both are useless but as you noticed yourself, singleton enums can be useful for autogenerated code since you can treat values uniformly. The same is true for records with no fields if you autogenerate the record based on field names coming from somewhere else. 

I’d much rather give the user the choice to choose if they want an empty record or a singleton enum and avoid a fairly pervasive breaking change than break a ton of code and remove choice from users.

**Comment by jberthold-da** [comment]
My current situation is that I _am_ generating DAML code, and I need to add `()` or `{}` if there is only one constructor in a generated `data` declaration.
What I want is an `Enum` in that case, and I cannot imagine any use of a record in that position (which is why I cannot imagine a lot of code breakage caused by the proposed change).

Of course there would be a way to distinguish the `data X = X {}` from `data X = X` during compilation (preprocess the syntax to add something that gets removed in core-to-lf - but it will show in type error messages). Just trying to argue for a simpler solution that does not require heroic efforts.

**Comment by cocreature** [comment]
I think the effort for distinguishing the two shouldn’t be too complex and if I understand you correctly, that would give you what you want?

**Comment by jberthold-da** [comment]
Correct. What I would like is that 
* `data X = X` compiles to a singleton LF `Enum`
It _won't be a problem_ if 
* `data X = X ()` compiles to a variant, and
* `data X = X {}` compiles to an empty record
although I struggle to see the utility of the two latter ones.

**Comment by hurryabit** [comment]
@associahedron That's the issue we talked about two weeks ago. Can you please have a look how hard it would be to support this?
