### ISSUE TITLE
SDK versions and channels (re: daml-assistant).

### ISSUE THREAD

**Issue by fmota-da** [digital-asset/daml#283]
We need to decide how we're going to version SDK releases going forward with head-based development and the new daml-assistant. Here's my wishlist for any new scheme we employ:

* ease of migration / compatibility with old system
* limited manual intervention in release process
* ability to have different channels: e.g.
    * stable releases that are well-tested, meant for end users
    * nightly releases that are released from HEAD regularly and automatically
    * "head releases", for local testing

The current system, as far as I can surmise, is that we have:

* a fixed semantic version for "head releases" `0.0.0`
* a semantic version for all other releases, e.g. `0.12.1`, that does not distinguish between whether this is a public release, or a release made for testing purposes, or a 
* a separate `da-assistant` version number, e.g. `114-7582c1a0bd`

We can eliminate the latter, because `daml-assistant` is packaged and versioned with the rest of the SDK. For "head releases", we should decide whether to keep it the way it is (0.0.0) or incorporate it into whatever scheme we come up with for other releases.

For the rest of the releases, we *should really* create a solid separation between publicly released versions and internal / testing versions. There have been issues before with parts of DA using failed internal releases that were never meant for the public, because the version number was misleading. The current system uses tagging on Bintray to distinguish between public & internal versions, but this isn't captured in the version number itself and has led to many problems in the past.

Here's my proposal:

* We keep definitive/stable releases as we have in the past, as a plain semantic version without annotations. So we have version `0.12.1` and so forth, as we already do, considered to be stable and ready for public consumption. The "semantic" part of "semantic version" is mostly aspirational at this point -- when we get to version `1.0` we need to seriously consider stability. ([See this post from the Rust team about their 1.0 version and the steps taken to ensure stability.](https://blog.rust-lang.org/2014/10/30/Stability.html))

    * Stable versions are made from nightly versions after manual testing, every couple of weeks or so. (Rust does this every six weeks, but we should do this more often since we're still evolving. Rust also has a multi-stage process for making stable releases, and doesn't release unfinished features of nightly into stable, but this isn't a distinction we want to make at this point.)

* We introduce nightly versions, which are built automatically and regularly (every night!), as annotated semantic versions based on the *next* stable version number we wish to release. So, if `0.12.1` is the last released stable version, the nightly versions would be generated automatically as `0.12.2-nightly.YYYYMMDD`.

    * The ordering defined on semantic versions (see [here](https://semver.org)), means that `0.12.1 < 0.12.2-nightly.YYYYMMDD < 0.12.2`, with nightly versions sorted lexicographically.

    * Following the semantic versioning standard, these nightly releases are considered "release candidates" for the stable version. As such we need to set up some system to prevent a nightly release from following a stable release with the same MAJOR.MINOR.PATCH version number. One easy approach is to automatically increase the PATCH number every week (or however often we want stable releases).

* We leave head versions as `0.0.0`. The ordering & preservation of head releases doesn't matter. (There is a suggestion of including the git revision & dirty state in the sdk config file, so telemetry can pick that up. That's a separate and easy thing to do.)

Any improvements / suggestions / dissent?

**Comment by neil-da** [comment]
Sounds good, with the notes that I'd like to make stable releases more frequently (weekly perhaps), and that semantic versioning etc is useful to end users (which Rust has lots of, and we have very few of) - it can wait a few years probably.

**Comment by fmota-da** [comment]
> Sounds good, with the notes that I'd like to make stable releases more frequently (weekly perhaps)

Makes sense to me.

> and that semantic versioning etc is useful to end users (which Rust has lots of, and we have very few of) - it can wait a few years probably.

We can technically be following the semantic version standard without worrying about backwards compatibility until we release version 1.0.0, and from then on we need to consider stability & backwards compatibility.

**Comment by fmota-da** [comment]
> We can technically be following the semantic version standard without worrying about backwards compatibility until we release version 1.0.0, and from then on we need to consider stability & backwards compatibility. That is part of the standard.

Here's the relevant wording from the standard ([link](https://semver.org/#spec-item-4)):

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by garyverhaegen-da** [comment]
Thanks @fmota-da for starting this conversation.

How much overhead is there in making a release? I am not familiar enough with the current release process to know what the current hurdles are, but here is the ideal end point I would have in mind:

1. Any (successfully-built) merge to master creates a release, with a "nightly" version tag.
1. Officially supported releases are created by simply tagging an existing (nightly) release with a stable version number.

Assuming we plan to automate the nightly release process (which we really should), and assuming the overhead of creating a release after having built the repo is not too high (it really should be as simple as uploading the tarball created by the top-level build invocation), I do not see any reason to not create a release for every commit. (If storage costs are an issue, we can consider GC'ing old ones.)

I think it is very important that supported releases are created by renaming/aliasing an existing release: this supports a process where we test a specific artifact, then bless that specific artifact as a release. Having a completely new artifact created for a supported release is really asking for trouble, and is the root cause for the confusing state we're currently in, where not all releases are "good". This requires **not** having a `VERSION` file in the repo, or at least not with its current semantics.

The assistant should, when asked to list versions, only list the supported ones, but when choosing a version, also accept the nightly ones. There may be a flag to list the nightly versions, but that should then be an ugly one (à la `dangerouslySetInnerHTML`).

I'm not too fussed about version formatting myself, but I think they should have the following properties:

- Nightly releases should be lexicographically ordered, and allow easy reference to the corresponding commit.
- Stable releases should be marketing-driven.

I do not see a strong need for the ordering to carry over between "nightly" and "supported" releases, as it conflicts with the requirement that supported releases are tested nightly artifacts, which I believe to be more useful. I also think having a separate naming scheme provides better clarity, and that conflicts with having a common prefix (which would be required for mixed lexicographic ordering).

> Ignoring my objections, one way to obtain combined lexicographic ordering with releases as tested nightlies would be to have a `VERSION` file in the repo that only counts up to the minor version and does not, in itself, represent a release. Changing that file would be akin to starting a new development cycle, and releases would be triggered separately. The major and minor numbers would be taken from the `VERSION` file, and the patch would be the number of commits since the last change to the `VERSION` file.

In terms of specific formats, my (weak) preference would be for:
- Purely marketing-based versioning for stable, supported releases. Whether or not those follow semantic versioning (or even a three-numbers scheme) should in my opinion be a marketing decision.
- `<day>-<minutes>-<sha8>` for "nightly" releases, e.g. `20190404-1610-a7b282b3`. This does not guarantee lexicographic ordering should two commits be merged into master in the same minute, but I believe that is good enough.

**Comment by fmota-da** [comment]
Thanks @garyverhaegen-da for the thoughtful suggestion.

1. We can do nightly releases per master commit/merged PR as you say, this should be possible regardless of version numbering & release process considerations.

2. The sdk release tarball contains an embedded version inside the sdk config file. I'm opposed to removing this, because then we have to manage a separate mapping of "sdk versions to sdk tarballs" in the assistant, and I can see this becoming a nightmare when something goes wrong. It's particularly bad because we want to be able to have users behind corporate firewalls or offline users, meaning there would be offline versions of these mappings, which could become outdated or just wrong/mismanaged by the user / organization. It's easier to just have one tarball that specifies an sdk release, including its version (whether it be nightly or stable).

3. @moritzkiefer-da  suggested that the SDK release process be triggered by a tagging of a nightly release. The process would automatically unpack the tarball, update the version number in the config file to the new stable version, then repack the tarball and release it as a separate artifact. I think this strikes a good balance without losing the versioned tarballs.

In the latter case it may be easier to just decouple the semantic version scheme (that we already use for public releases) from the nightly versions, as you suggested.

I don't care too much if versions are lexicographically ordered, or use semantic version ordering, as long as the ordering is well defined and stable within one channel (stable vs nightly). [We probably don't want lexicographic ordering for public versions.]

**Comment by garyverhaegen-da** [comment]
I just had a chat with @fmota-da and here is our conclusion. The repo should have a file called `VERSION` containing `MAJOR.MINOR` versions. Regular "nightly" releases (may be as often as every commit to master) will be tagged with the content of that file, followed by the number of commits since that file was changed, followed by an as-yet-unspecified suffix indicating untestedness.

Stable, official release will be created by taking a "nightly" release, un`tar`ring it, changing just the embedded version file to remove the suffix, and re-`tar`ring it.

**Comment by fmota-da** [comment]
Thanks @garyverhaegen-da for the productive discussion. :)

So to summarize, the updated proposal is for (non-HEAD) versions is:

- the `MAJOR.MINOR` version is stored in the repo and updated for marketing purposes / etc
- the `PATCH` version is derived automatically from the git history e.g. number of commits to master since version
- the automatic release will be tagged with something (we're leaning toward `-unstable`)
- a stable release process is triggered manually but all it does is change the version number in the tarball to remove the `-unstable` tag.

**Comment by fmota-da** [comment]
For now we've settled on something slightly different from the above, so let me document it.

We are piggybacking on the existing release process:

* We trigger the release process manually by updating `VERSION` file.
* CI prepares the release of build artifacts which includes SDK tarballs for all of our target platforms.
* CI makes the release on GitHub and marks it as a pre-release.
* After manual testing a pre-release can be manually upgraded to a full release.
  * We do not change the version number or the build artifact at all between pre-release and release.
* In daml assistant, when you perform `daml install latest` it will fetch the latest full release.
  * The daml assistant ignores pre-releases unless you give its version number explicitly, for example by running `daml install 0.12.5` or by specifying it in the project config.

The main change is we don't mark pre-releases as `-unstable` or anything like that. This simplifies the release process a lot because we don't need to, say, repackage the build between pre-release and release to change a version number. This is also consistent with how da-assistant treats SDK versions on bintray (they have to be marked as public in a separate step).

We may revisit this in the future after we move away from da-assistant, but I'm perfectly happy with this system for now. I'm closing this issue for now.
