### ISSUE TITLE
navigator console: add a 'list contracts' command

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#2880]
The navigator console doesn't have a command to list active contracts, instead one needs to run a sql query. I think the console really should have a command to quickly list all active contracts.

**Comment by rautenrieth-da** [comment]
We deliberately did not add such a command.

Our assumption was that listing all active contracts with all of their data is too much information to display, so most use cases that list active contracts would filter and/or project the data. Since we did not want to invent some SQL-like syntax to `list contracts`, we ask users to run SQL queries instead.

For a better user experience, the idea was to allow users to define command shortcuts, such that running `list_my_acs "CHF"` would actually run `sql select * from contract where argument.currency="CHF"`.

Given the above, do you still think it makes sense to add a command to list active contracts? If yes, what data should it display? Only the contract IDs, or also all of their data?

**Comment by robin-da** [comment]
I see. I think it would be nice to still have a `list contracts` command with a parameter that limits the number of shown contracts with a default set to say 10 that shows the 10 newest contracts. This would allow for quickly checking a new workflow, while the sql queries shortcuts are useful for more involved setups. The command should output the ids together with the data. What do you think?

**Comment by cocreature** [comment]
Closing, you can query active contracts via DAML REPL and we are not actively encouraging the use of navigator console atm.
