### ISSUE TITLE
Error: Conflicting definitions for ‘arg’

### ISSUE THREAD

**Issue by tweber-da** [digital-asset/daml#3017]
The following snippet
```
template Foo
  with
    p : Party
  where
    signatory p

    controller p can
      FooC: ()
        with
          arg : Decimal
        do
          return ()
```
fails with 
```
 • Conflicting definitions for ‘arg’
      Bound at: ...
                <no location info>
    • In an equation for ‘_actionFooFooC’
```

**Comment by hurryabit** [comment]
The problem is that the choice argument is implicitly bound to an variable called `arg`. That's why we have a conflict. The error message is pretty bad. Unfortunately, I don't see how to easily improve the error message.

The workaround for now is to not call your choice fields `arg`.

In the long term, we could change the template desugaring such that we don't bind the choice argument to `arg` if there's a field called `arg`. Given the simplicity of the workaround, I won't give this high priority.

**Comment by cocreature** [comment]
Closing since I don’t see this getting fixed.

**Comment by hurryabit** [comment]
I would like to keep this one open since it's something we should consider if and when we change the compiler architecture.

**Comment by cocreature** [comment]
Fair enough although I expect that changing the compiler architecture will change so much that very specific issues like this one are useless.

**Comment by akrmn** [comment]
Closing in favor of https://github.com/digital-asset/daml/issues/13811
