### ISSUE TITLE
Large heap and long compilation when using multiple packages

### ISSUE THREAD

**Issue by jberthold-da** [digital-asset/daml#3150]
I tried to split a large DAML codebase into several (four) packages that depend on each other.
However, the resulting code suffers from long compilation times, considerably longer than when putting all files into a single package.

The code is too large to share, and proprietary, but here are some characteristics. The four packages are
1)  a very small (stdlib extensions) package 
2) a package with ~800 (generated) modules, 
3) another package of ~800 modules that imports many files from package 2,
4) a (smaller, ~160 module) test package that only imports selected interface modules.

It is package 3 (the one that imports many of the generated files) which takes very long to compile. Also, I am compiling with a 16-fold parallelism, but I observe single-core activity for long periods during that compilation. 
This hopefully provides some ideas for investigation.

**Comment by cocreature** [comment]
I’ve started looking into this.
On a smaller test setup, I am able to get significant performance improvements from packaging so in general it does seem to work.

I am still investigating why it doesn’t help on the project you tested on. Part of it seems to be that the part that you have split off is relatively small (in terms of single-threaded compilation time) compared to the whole project (seems to be at most 1/10) so even if all of that drops away there isn’t that much to be gained. I’ll continue investigating.

**Comment by cocreature** [comment]
I finally managed to isolate it to a small example at https://gist.github.com/cocreature/5242ef435c4ae794abd5bf3fb9998fbf.

The pattern match checker in `Main` takes several seconds with 500 constructors and 500 types for this example and you can get it to blow up fairly quickly by tweaking one of the following points:

1. Add more `Cl` instances.
2. Add more constructors  to `ADT`.
3. Add more constraints to `f`.

There are a few crucial points here:
1. The instances are in a separate package. This is the actual bug here. I see no sensible reason why this should cause a significant slow down apart from some initial constant time to load the interface file. Moving `Dep.daml` into `main` makes desugaring take < 100ms.
2. `Cl` has a functional dependency. What seems to be happening (from looking a bit at the pattern match checker code) is that GHC tries to unify the constrains that are in scope (the redundant constraints on `f`) with the left side of functional dependencies so that it can use the right side to deduce more information that might make cases inaccessible.
3. `f` has redundant constraints. See 2 for why this is important.
4. The constructors of `ADT` have an argument. I get a slow down even when that argument is `()` but it is significantly smaller than when the argument is the one in the example (which corresponds to DAML’s `Text` type). Note that the type is not a type parameter of `ADT` so I don’t see how the information from the functional dep could influence it.

I’m currently trying to reproduce the issue with plain GHC which might make this easier to debug.

**Comment by cocreature** [comment]
I have a repro using GHC https://gist.github.com/cocreature/b8dd81cbdd204bb64a8810189485fcbb
