### ISSUE TITLE
Bad error when passing empty string for Party in JSON API

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#3247]
When I pass an empty string for a `Party` in DABL, I get an error simply saying `Missing field: value`, which is rather uninformative. I think this comes from deep down, somewhere in the gRPC API Server.

**Comment by gerolf-da** [comment]
Weeeeeellll, one could argue that the client side validation for party fields shouldn't rely on feedback from the grpc api server, but already check that the field is not empty.

**Comment by bame-da** [comment]
I could be convinced that the client of the gRPC API should, fair enough. In my case that'd be the JSON API, I think.

**Comment by gerolf-da** [comment]
Sorry, I misread. This is not in the DABL UI, but via the json api?

**Comment by bame-da** [comment]
The JSON API as exposed by DABL, yes.

**Comment by gerolf-da** [comment]
okay. in general I'd rather work on improving the error message from the engine rather than add magic validation sprinkles to the json api. although this case is a pretty easy one, as empty party strings are never allowed, and this could fairly easily be detected as part of the json -> ledger api conversion.

**Comment by leo-da** [comment]
@gerolf-da it is easy to change (improve the error message) in the json-api... however gRPC API users will not benefit from this. Happy to make the change in the gRPC API.
