### ISSUE TITLE
Expose LF generic equality  

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#3766]
As part of the Generic Map implementation (#2256) we defined an generic equality (#3074).

We need to expose this equality from DAML-LF. 

The following built-in should be replaced by generic equality starting from LF 1.dev:
 * 'EQUAL_INT64'
 * 'EQUAL_TEXT'
 * 'EQUAL_TIMESTAMP'
 * 'EQUAL_DATE'
 * 'EQUAL_PARTY'
 * 'EQUAL_BOOL'
 * 'EQUAL_TYPE_REP'

**Comment by remyhaemmerle-da** [comment]
@associahedron @cocreature @hurryabit I let you decide if (and how) we need to expose from the surface language.

**Comment by cocreature** [comment]
Adding a bit more context after discussing this with @associahedron:

1. The generic map already gives you an equality operation that you can technically use by inserting into a map and seeing if the size increases. Therefore there is little reason not to expose this directly in DAML-LF.
2. Exposing it also allows us to get rid of a bunch of type-specific equality primitives which is always nice.
3. We need to make sure that the spec also defines what happens outside of the PER that defines equality.
4. Short-term this changes little in DAML as we do not plan to expose an unconstrained `a -> a -> Bool` operation corresponding to generic equality. However, it does allow us to provide (total) `Eq` instances for some new types, in particular, `AnyTemplate`. For templates equality is derived automatically so there is a low chance of a mismatch with `Eq` (technically still possible since `Eq` on the fields of a template could be user-defined).
5. Long-term it would be nice to ban user-defined `Eq` instances and always use the builtin equality. That should improve, compilation performance (no need to typecheck and compile the instance body), DALF size (trivial code for the instance body) and runtime performance. However, that’s not super urgent and we should do some investigation on how many codebases have (useful) user-defined `Eq` instances.

@associahedron if I forgot something let me know!

**Comment by remyhaemmerle-da** [comment]
Done.

**Comment by remyhaemmerle-da** [comment]
still need to drop the usage of EQUAL_INT64 EQUAL_STRING etc primitives in the compiler
