### ISSUE TITLE
Transaction stream with explicit end offset doesn't always terminate

### ISSUE THREAD

**Issue by lima-da** [digital-asset/daml#3984]
There is a possibility for transaction streams with an explicit end offset not to terminate but hang indefinitely.
Steps to reproduce:

1. Start sandbox in static time mode with the postgres backend
1. Send a create command with the following command parameters:
    1. `applicationId=myApplicationId`
    1. `commandId=myCommandId`
    1. `party=Alice`
1. Confirm that the command was executed successfully (e.g. in navigator)
1. Send another command with the same command parameters as above
    1. This will cause the command to be silently dropped (because it is a duplicate submission), but the ledger end to be increased.
    1. There is now a larger `ledger_end` value in the `parameters` table than there are entries in `ledger_entries`.
1. Get the ledger end via `TransactionService#GetLedgerEnd`
1. Send a `TransactionService#GetTransactions` request with `begin=LEDGER_BEGIN` and `end` as the previously received ledger end.
1. This request will "hang" until another ledger entry has been stored.

**Comment by gerolf-da** [comment]
Some notes:

- The ledger entries stream termination condition requires a ledger entry at least AT the end offset (or later) https://github.com/digital-asset/daml/blob/6bc00da1e2ddb80e51232327d70591478f99edf9/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/SandboxIndexAndWriteService.scala#L280-L291
- A duplicate submission results in the command being dropped. The ledger end pointer is being increased, but there is no accompanying ledger entry: https://github.com/digital-asset/daml/blob/6bc00da1e2ddb80e51232327d70591478f99edf9/ledger/sandbox/src/main/scala/com/digitalasset/platform/sandbox/stores/ledger/sql/dao/JdbcLedgerDao.scala#L1005-L1012
- This bug doesn't occur in wall-clock time mode, because every second a new `checkpoint` ledger entry is being written, thus always providing a newer ledger entry to eventually satisfy the termination condition.
