### ISSUE TITLE
daml2ts `build-and-lint` test should not hardcode ports

### ISSUE THREAD

**Issue by shayne-fletcher** [digital-asset/daml#4477]
`bazel run //language-support/ts/codegen/tests:build-and-lint` can go wrong if there's already a json-api running so for this reason, it's now marked "exclusive".

Better though is if we don't hardcode port numbers in this script at all.

**Comment by hurryabit** [comment]
This issue does not only arise for the JSON API but also for the ledger server we start in that test.

**Comment by cocreature** [comment]
To add some more context based on what I said elsewhere: The general idea is to just bind to port 0. For sandbox this is pretty convenient since it has a `--port-file` flag where it will write the port to. The JSON API doesn’t have that flag so you would have to scrape it out of stdout or something like that. I would suggest to just add this flag to the JSON API to simplify the test usecase. cc @S11001001 @leo-da

**Comment by hurryabit** [comment]
I've added a ticket for the `--port-file` flag: https://github.com/digital-asset/daml/issues/4483.

**Comment by shayne-fletcher** [comment]
Duplicated in https://github.com/digital-asset/daml/issues/5551. Closed via https://github.com/digital-asset/daml/pull/5553.
