### ISSUE TITLE
daml2ts: Support multiple DARs as input

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#4585]
Since we want to continue using the main package name from each DAR for the directory where the `.ts` files for its main DALF end up, we need to be careful about three corner cases:

1. **There are a DAR whose main package is named `Xyz` and has hash `abc` as well as a DAR which contains a dependency whose hash is `abc`:** There are two ways to handle this issue:
  a. We create two directories, one named `Xyz` and one named `abc` containing the same `.ts` files and don't change any of the import logic.
  b. We only create a directory named `Xyz` and change the import logic such that `Xyz` gets imported instead of `abc`.
  I'm in favor of the former approach since it is more robust regarding under change to the input DARs.
2. **There are two DARs whose main DALF has hash `abc` but is named `Xyz` in one of them and `Pqr` in the other:** There's no way around creating directories named `Xyz` and `Pqr` and having all the `.ts` files twice. This could also come in combination with case 1, where we might end up with three copies of each file. I'm fine with this for now.
3. **There are two DARs whose main package is named `Xyz` but the main DALF has hash `abc` in of them and `def` in the other:** There's nothing sensible we can do now and need to error out. In the future, we might address this by also feeding a mapping from package hashes to package names or something similar into `daml2ts`.

**Comment by cocreature** [comment]
1. This one should be addressed or at least simplified by #4412 since you always have a name and version in that case. For now, I would recommend to just infer the name and version based on the filename like we do in `damlc`.
2. I don’t really see a usecase for having two DARs with the same main dalf but different names. At least for now, I would recommend just erroring out here.
3. I don’t think we gain much by making the typescript codegen more flexible than `damlc` here. If this is something that we want/need to support we should first fix it in `damlc` but for now, I think it’s fine to just say that this is not suppported.

**Comment by cocreature** [comment]
Can we close this @shayne-fletcher-da?

**Comment by shayne-fletcher** [comment]
Yes, all good.
