### ISSUE TITLE
Change terminology to follower/direct message

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#5015]
Instead of the friend/message terminology here. We need to make it clear that our model is not the regular bidirectional friendship model but more like Twitter where following a person also means opening your inbox for their direct messages (that's at least what @bame-da told me).

**Comment by nemanja-da** [comment]
@hurryabit Does it make sense to change the messaging in the UI as well? Would make the explanation a bit easier. So it would be something like this:

- Instead of "Me and my friends" you would have "Me and my followers"
- Instead of "Others and their friends" you would have "Others and their followers"
- Instead of "Send a message to a friend" you would have "Send a direct message to a follower"

This way it would be really like twitter, where it makes sense to see the whole network and connections.

**Comment by hurryabit** [comment]
@nemanja-da Yes, it would make sense to change the UI accordingly. As I already said elsewhere, we need to change subject and object of the following relationship in some of these labels (in that order):
* "People I am following"
* "My followers"
* "Send a message to follower"
* "Follow somebody"
* same

**Comment by nemanja-da** [comment]
Will need to make appropriate changes in the daml model as well (changing form friend to follower etc.)
