### ISSUE TITLE
Make snapshot releases discoverable in the assistant

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#5198]
While the assistant will happily install a snapshot release if you specify the version explicitly, snapshot releases are currently hidden completely. While this is the right behavior by default, it would be nice if users could opt in to using snapshot releases. In particular, I’d like to have the following two:

1. Similarly to how we have the magic `latest` version that you can pass to `daml install latest`, add something like `daml install latest-snapshot`.
2. Extend `daml version` with a `--shapshot` flag that also lists available snapshot releases.

**Comment by associahedron** [comment]
Both of these are actually somewhat hard to implement, since figuring out what snapshot releases are available (or even, what snapshot releases is the latest) involves either using the GitHub API (which has known problems with restrictive rate-limiting) or scraping data from the releases page.

Both of these could be solved by hosting a `snapshot-versions.json` on `docs.daml.com`, like how we already have a `versions.json` for stable releases.

**Comment by cocreature** [comment]
> That could be solved by hosting a `snapshot-versions.json` on `docs.daml.com`, like how we already have a `versions.json` for stable releases.

We already have that, see https://docs.daml.com/snapshots.json so I don’t think it should be too hard.
