### ISSUE TITLE
Include changelog in SDK release

### ISSUE THREAD

**Issue by martin-drhu-da** [digital-asset/daml#53]
We should put some form of changelog in the `sdk.tar.gz`.

**Comment by hurryabit** [comment]
@moritzkiefer-da Do you agree that I can close this?

**Comment by cocreature** [comment]
We don’t include the changelog in the SDK tarball at the moment so I don’t think it can be closed unless we no longer plan to do this.

**Comment by associahedron** [comment]
I think we can close this. There is little reason to distribute the changelog inside the SDK, because we already release it as part of the source tarball that is in any release, and we release it via Github notes, and docs.daml.com, and the separate release announcement blog. I think that's more than plenty. 

Having said that, I think it would be easy to add a bazel rule that just copies the Rst release notes over into the release tarball (leaving a CHANGELOG.rst). But I still don't see a good reason to do this -- the release notes are available in so many places *including* being inside one of the release artifacts (the source tarball).

Closing the issue.
