### ISSUE TITLE
kvutils: LookupByKey validation

### ISSUE THREAD

**Issue by gerolf-da** [digital-asset/daml#5554]
When transactions are validated in kvutils, the [key lookup](https://github.com/digital-asset/daml/blob/7b52823b60048f5a6ff3bd3b79294f5ce49cc910/ledger/participant-state/kvutils/src/main/scala/com/daml/ledger/participant/state/kvutils/committing/ProcessTransactionSubmission.scala#L478) is not restrictive enough.

Furthermore, the expected result of `LookupByKey` is not checked against the global state of the ledger. If the lookup with submitter restriction differs from the lookup without submitter restriction, the transaction should fail.
## Expected
`LookupByKey` should only return a contract if the submitter is a stakeholder on the contract.

## Observed
`LookupByKey` returns a contract if the contract has been locally or globally divulged to the submitter.

**Comment by bame-da** [comment]
@gerolf-da I don't fully agree with this:

> LookupByKey should only return a contract if the submitter is a stakeholder on the contract.

In my opinion, the "Submitter is Stakeholder" is a pure interpretation time restriction. At validation time, the validators, in this case key maintainers, should merely check that authorisation and lookup are correct. Higher level, I see interpretation and validation as having two completely different purposes: 

- Interpretation translates a command into a transaction that _probably_ conforms to the Ledger Model. _Probably_ because the submitter has imperfect information.
- Validation checks that transactions _actually_ conform to the ledger model

For key lookups, that means that at interpretation time, the submitter does lookups "best effort" using whatever information they have available. At validation time, the lookups are checked for correctness.

Currently, "best effort" means looking at contracts the party is a stakeholder on, meaning we are biased towards false negatives. However, we could improve this "best effort" heuristic. For example, we could say that if Alice submits a transaction in which a contract with Bob as only stakeholder gets created, and then immediately looked up by key, that should also succeed as Alice has perfect information about the state of that contract at the time of lookup. Such a change does not change the Ledger Model so it should not need to touch validation. It's merely an interpretation time change, making transactions more likely to be valid.

**Comment by gerolf-da** [comment]
@bame-da: into which category falls "transaction re-interpretation during commiter validation"? If I don't care about visibility during transaction re-interpretation, I can leak the actual contractId in form of an error message, return value of a choice, etc.

**Comment by gerolf-da** [comment]
Let's go with #5562.
