### ISSUE TITLE
MacOS Builder will not auto-update due to permissions issue

### ISSUE THREAD

**Issue by nycnewman** [digital-asset/daml#5678]
Agent install on macOS builder leaves the /Users/vsts/agent directory with some files owned by Root. This blocks agent upgrade from Azure console as update process fails to switch version correctly and agent dies.

Fix is to ensure agent directory is owned by vsts:staff

**Comment by nycnewman** [comment]
Looks like this is related to the hardening part of the script which resets file ownership. Will discuss offline.

**Comment by garyverhaegen-da** [comment]
That was taken from the Linux nodes. It's meant to prevent changing the Azure files, so it's sort-of expected that it would also prevent upgrading. I'm not the original author of that bit but I'm pretty sure it was meant for a world where nodes are recreated rather than updated in-place, so the upgrade use-case was not a factor.

Happy to drop that bit of hardening if you don't think it's needed and are not in a position to add cycling to the macOS nodes yet.

**Comment by nycnewman** [comment]
Closing as daily rebuild make this irrelevant
