### ISSUE TITLE
Tail call optimization

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#5767]
This brought a 1.06x performance improvement.

**Comment by nickchapman-da** [comment]
I believe a standard definition for CEK *is* optimized for tail-calls by default. Our Speedy implementation has lost the tail-call behaviour because it has changed from a _caller-saves_ to a _callee-saves_ strategy for managing the environment.

Caller-saves *(We don't do this)* : The `Env` would be pushed into the `KArg` continuation, with the environment restored when the continuation is entered.

Callee-saves *(we do this)* : The environment is not saved in `KArg`. When a function body is executed, it takes place in the environment of it's caller. New values are pushed onto the env-stack as required: the free-vars and args, and for any let-bindings which are made. When the function body finished, and needs to return, this extra stuff needs to be cleared, so restoring the env-sack to it's state before the call. This is achieved by pushing a `KPop` continuation on the kont-stack when the function body is first entered.

It is the `KPop` continuation which is responsible for Speedy not being tail-call optimized.

**Comment by hurryabit** [comment]
@nickchapman-da I've moved Rusty engine from "caller-saves" to "callee-saves" (the opposite direction of what you're suggesting) and it gave me a 1.2x improvement on my computation heavy benchmark: https://github.com/digital-asset/rusty-engine/pull/20

The profiling data suggest that allocating and freeing all these tiny environments has put quite some pressure on the allocator which is avoided by sharing one big environment which only needs to be resized occasionally.

Instead of putting environments into `KArg` we could probably put "stack pointers" in there.
