### ISSUE TITLE
DA.Text.splitOn "aa" "aaa" returns bad result

### ISSUE THREAD

**Issue by hurryabit** [digital-asset/daml#5786]
As a user, I _expect_ the following relationship between `splitOn` and `intercalate`:
```haskell
intercalate s (splitOn s t) == t
```
for all `s, t: Text`. However, with the current implementation
```haskell
splitOn "aa" "aaa" == ["", "a", ""]
```
and
```haskell
intercalate "aa" ["", "a", ""] == "aaaaa"
```
Since `intercalate` is _clearly_ right here, `splitOn` must be wrong. Instead, I would _expect_
```haskell
splitOn "aa" "aaa" == ["", "a"]
```

Even though fixing this is a breaking change, we should do it nevertheless IMO. I consider the current behavior for `splitOn` a bug.

Please weigh in with your opinion @bame-da.

*Update:* In DAML-LF 1.dev, we have
```haskell
unstableSplitOn "aa" "aaa" = ["", "a"]
```
what is exactly what I would expect.

**Comment by garyverhaegen-da** [comment]
Correcting a bug, i.e. changing the behaviour of the code to match the documentation, is a patch-level change per semver. That doesn't mean that's what we have to do, but you have to draw the line somewhere, otherwise everything becomes a breaking change.

Note that in this case the documentation clearly supports the "correct" behaviour described above (emphasis mine):
> Break a text into pieces separated by the first text argument (which cannot be empty), **consuming the delimiter**.

Also I'm not sure why "cannot be empty", though that is veering into minor-level change I suppose.

**Comment by bame-da** [comment]
I agree, sorry this slipped through during my staycation last week.
