### ISSUE TITLE
Allow exclusion of individual tests in ledger-api-test-tool

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#5837]
Currently, the ledger API test tool only allows excluding whole groups of tests. This is somewhat unfortunate for compatibility tests since it means that as soon as we introduce some incompatibility, we have to disable a whole group.

The ledger API test tool already has short names for tests, so it should be possible to specify `--exclude` in the form `groupName:testName`.

See https://discuss.daml.com/t/can-i-disable-individual-tests-in-the-ledger-api-test-tool/226/2 for more information.

This should probably also apply to `--include` and `--list`.

**Comment by dasormeter** [comment]
agree this is super useful when trying to debug a specific test failure, or if you want to exclude only one within a group of tests because it's problematic.  i started spelunking on this back in dec but have not had a chance to progress on it to completion https://github.com/digital-asset/daml/pull/3928/files

**Comment by garyverhaegen-da** [comment]
Fixed in #6458.
