### ISSUE TITLE
Visualize compatibility test results

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#5838]
The point of having these compatibility tests is to verify guarantees that we want to make. It would be great if we could visualize the results in way that a (technical) user can easily see what is being tested and which tests pass. This doesn’t need to be particularly fancy. Some script that turns the Bazel test log into a couple of tables is probably sufficient.

**Comment by garyverhaegen-da** [comment]
After discussion with @cocreature, we have decided not to proceed with this task. The reasoning is as follows: by construction, all of the tests we run are green, because we specifically exclude the tests that are not. Therefore the results of running the tests are not particularly interesting to look at.

What is useful is to have some idea of what gets tested, which is addressed by [the README](https://github.com/digital-asset/daml/blob/master/compatibility/README.md), and possibly to be able to check which tests are skipped for which version, which technical users can find out very easily by reading [the exclusion matrix](https://github.com/digital-asset/daml/blob/master/compatibility/bazel_tools/testing.bzl).

There are two additional pieces of information that could be made more easily accessible:
- Why was a given test excluded? This can be addressed by adding comments to the exclusion matrix directly.
- What does an excluded test do? This currently requires digging through the api-test-tool code, which is not ideal.

Still, neither of those can be addressed by visualization, and both of those are completely available from the static source code.
