### ISSUE TITLE
daml test error for project-root: Yaml file not found

### ISSUE THREAD

**Issue by richardkapolnai-da** [digital-asset/daml#6245]
`daml test` does not work outside of the project dir.

Reproduce:
```
...tmp$ daml new skeleton skeleton
Created a new project in "skeleton" based on the template "skeleton".
...tmp$ daml test --project-root skeleton
damlc: ConfigFileInvalid "project" (InvalidYaml (Just (YamlException "Yaml file not found: skeleton/daml.yaml")))
...tmp$ cd skeleton/
...tmp/skeleton$ daml test
daml/Main.daml:setup: ok, 1 active contracts, 3 transactions.
```

**Comment by sofiafaro-da** [comment]
Thank you for the bug report @richardkapolnai-da. I can reproduce. I even tried the recomended way (passing `DAML_PROJECT` env var instead of using `--project-root`) and got the same error.

Passing an absolute file path to  `daml test --project-root` works fine, and `daml build` works fine with relative or absolute file paths, so this is a bug with the handling of relative paths in `damlc test`.
