### ISSUE TITLE
Make codegen an optional part of `daml build`

### ISSUE THREAD

**Issue by anthonylusardi-da** [digital-asset/daml#6356]
Codegen is very much a build step in most cases and as such it should be able to be optionally run when `daml build` is run and can take advantage of `daml.yaml` allowing for codegen arguments to be specified in it.

Perhaps something like the following (not tied to it, just an idea): `build-codegen: True/False` in `daml.yaml` and a `daml build --no-codegen` to override the `build-codegen` option.

**Comment by cocreature** [comment]
In principle, this seems useful for development. I don’t think it’s useful to releases since there recompiling is somewhat dangerous since it can change your package ids.

However, in the current state this doesn’t help much since you still have other steps like the `yarn install --force --frozen-lockfile` during development and at that point you end up with a bash script or makefile anyway that captures these steps and including both codegen and build in there is fine.
