### ISSUE TITLE
Add a platform-version field to daml.yaml

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#6558]
Now that we provide a reasonable amount of compatibility between SDK and platform versions we should enable users to use different versions of platform components than the version of SDK components (primarily the compiler).

For the purposes of this issue, “platform components” includes the following components:

1. Sandbox next
2. Sandbox classic
3. The JSON API
4. Once it has stabilized, the trigger host

## Design goals

The assistant is in charge of managing versions so clearly it has to become aware of this. Given that the assistant needs to be at least backwards compatible and is also mostly agnostic to SDK tools this comes with a few challenges that I hope to address with the following goals.

1.  The only artifact consumed by the assistant is still the SDK tarball, we do not rely on separately released platform artifacts, e.g., fat JARs.
2. Which components are platform components is part of `sdk-config.yaml` so the assistant does not hardcode any assumptions about certain commands.
3. The definition of a platform command in `sdk-config.yaml` must not rely on the internal structure of the SDK tarball of another version. Otherwise this is not going to work across versions.

## Proposal

1. Extend `daml.yaml` with an optional `platform-version` field. Not setting this is equivalent to setting it to the value of `sdk-version`.
2. Extend the assistant to install both versions whenever we currently install the SDK version.
3. Extend the `sdk-config.yaml` field with a new `platform-commands` section with the same format as `commands`.
    Defining a command in both `commands` and `platform-commands` is an error.
4. The assistant handles commands:
    1. Check in the `sdk-config.yaml` if the command is an SDK command or a platform command. SDK commands are handled as before.
    2. Look for the `sdk-config.yaml` of the `platform-version` (instead of `sdk-version`).
    3. Look for a command of the same name in either `commands` or `platform-commands` (this is to keep backwards-compatibility with older SDK versions that do not have `platform-commands`).
    4. Run the corresponding path.
    5. The assistant will set both `DAML_SDK_VERSION` and `DAML_PLATFORM_VERSION` for _all_ commands (open question: what do we do for older SDK versions)
5. Tools can make use of the `DAML_PLATFORM_VERSION`. E.g., damlc could use this to select the latest supported DAML-LF version by default.

**Comment by garyverhaegen-da** [comment]
There is a bit of circularity there: point 4 cannot know if the command it's trying to execute is an SDK-command or a platform-command before point 4.i. It's not terribly hard to resolve, though: just change point 4 to always assume a command is a platform command until proven otherwise, i.e. always start by checking the sdk-config.yaml of the platform-version, and only fall back to the one in sdk-version if the current command is not a platform-command as of platform-version.

Regarding old versions, would it be acceptable to put a lower bound on versions accepted for the platform-version field? That should be the first version of the platform where we feel some confidence this is reasonably well implemented.

Another open question: what happens if a command is an sdk-command in platform-version, but a platform-command in sdk-version? Do we not run the risk of users ending up with version mismatches, and in that case would it not be better to just crash rather than run the command?

**Comment by cocreature** [comment]
I don’t think there is any circularity here at least in what i intended although it certainly sounds confusing. The idea was the following:
You run `daml command`. You first check `command` in the `sdk-config.yaml` of your `sdk-version`. If it is declared as a platform command you go to the `sdk-config.yaml` of the `platform-version`. I’ll try to clarify this.

As for older versions, yeah a lower-bound also seems acceptable.

If we do go for the lower bound, I think your last question also becomes easy. Allowing both `sdk-commands` and `platform-commands` in step 4.ii. is mainly useful for older versions that do not yet have a `platform-commands` field.

**Comment by sofiafaro-da** [comment]
This seems a bit problematic with respect to backward compatibility. The transition would be unsmooth in multiple places:

- Older versions of the assistant will know nothing about platform-version, so you would need to update the new platform tools to error out whenever they are called with an older assistant version that doesn't set DAML_PLATFORM. (This seems like a bad sort of logic to have to add ...)
- This will particularly problematic when someone first upgrades to a new sdk-version that has the platform-version feature. Ultimately, having behavior that depends on the assistant version is *really bad* and something I've tried to avoid as much as possible, unless the new behavior is completely backward/forward compatible, or a bugfix. I'm very wary about making large changes to the assistant.
- We can't use older "platform-versions" at all, but if we try to implement a lower bound on platform-version (gary's suggestion), it's a bit of a chicken-and-egg problem (which is the earliest version to support platform-version? Well, it depends on the development of this feature, which requires us to place the lower bound...). If we don't place a lower bound ... what happens when an older platform-version is used?

I'd like to suggest a different approach that I think solves these problems: Don't implement anything about `platform-version` in the assistant, but implement the correct re-routing behavior in `daml-helper` instead. This leaves the assistant to handle SDK installation only, and the daml-helper then chooses which commands are considered "platform" commands (presumably, all the commands that use `daml-sdk.jar` -- which we could rename to `daml-platform.jar` or something), and we perform this rerouting by invoking daml assistant (via `DAML_ASSISTANT_PATH`) by setting `DAML_SDK_VERSION` appropriately. This has the advantage that

1. only the new SDK versions need to know how to route platform tools
2. installation is already handled
3. can route to older platform-versions and adjust the lower bound as needed (based on our compatibility tests)

Question: Can we forbid platform-version > sdk-version? Or discourage it? That would make this even better, since then we don't have to worry about forward-compatibility for the daml-helper platform-version re-routing.

**Comment by cocreature** [comment]
1. Yes, older versions of the assistant will not support this but I don’t really see the issue here. IMHO the important piece of forwards-compatibility the assistant needs to provide is to be able to upgrade itself which involves installing new SDK versions and it even does that automatically. I don’t see a lot to be gained by trying to support invoking commands from new SDK versions with older assistants. Side note: installing shell completions already broke this to some degree although it is clearly a far less invasive change.
2. We could use older platform versions using the approach I described where we fall back to reading from `commands` and not `platform-commands`. I ’m not really following the chicken-and-egg problem. You wouldn’t even need to have any version-dependent logic here. You could just error out if the `sdk-config` does not have the corresponding command in `platform-versions` (although admittedly checking the version might produce better error messages).

As for your proposal, I considered this before but decided against it:

* Handling versions is fundamentally the main task the assistant was designed for. Moving that logic into daml-helper would mean that you now end up with the assistant installing an SDK version to call daml-helper which then calls the assistant to install another SDK version (the one for the platform) so it can invoke another command there. That seems like a pretty confusing control flow to me where no tool is clearly in charge.
* “Installation is already handled” doesn’t seem quite right. The platform version might not be installed so daml-helper needs to call into the assistant to install it.

I do think it’s still a reasonable option and we could probably make it work but I’m a bit worried that the confusing control flow with no tool being in charge ends up biting us down the line whereas moving it into the assistant keeps things cleanly separated.

**Comment by sofiafaro-da** [comment]
Regardless of how you do this, you're going to need to handle the dual versioning in `daml-helper`, because `daml start` calls `daml build` (an SDK command) and `daml sandbox` (a platform command) and also `daml script` (is this an SDK or platform command? My hunch is SDK).

Further, `daml-helper` already calls `daml-assistant` in multiple places.

> “Installation is already handled” doesn’t seem quite right. The platform version might not be installed so daml-helper needs to call into the assistant to install it.

Right, but daml assistant performs installation automatically, and all of that is already implemented, so in the event that daml-helper attempts to run a platform component from a different SDK version (due to `platform-version`), and that SDK version isn't installed, the assistant will either install it (default behavior) or fail and ask the user to install it (which is what happens if the user has disabled auto-installs). This seems like the correct behavior to me, in every case.

>  IMHO the important piece of forwards-compatibility the assistant needs to provide is to be able to upgrade itself ...

When the assistant updates itself through an auto install, prior to running a command, it does not use its own new version to run the command, it still uses the old interpretation, under the assumption that command interpretation is fixed. That's why big changes to command interpretation (which this is) can cause seemingly random and hard to reproduce errors. Arguably this is a strange edge case of the assistant that we could change, and is probably worth changing (although it's finnicky ...), but current assistant does have this behavior. (This might be a good change under improving inter-version compatibility...)

**Comment by cocreature** [comment]
> Regardless of how you do this, you're going to need to handle the dual versioning in `daml-helper`

I’m not following this. If `daml-helper` just calls `daml sandbox` won’t that pick up the `platform-version` automatically with my proposal and it doesn’t need to be aware of this?

> Right, but daml assistant performs installation automatically, and all of that is already implemented

That’s fair. It still seems weird to me that not everything that is needed is guaranteed to be installed once the assistant hands over control.

As for your last point, that is true (and that’s what broke when we added completions) but as you said changing this seems like a good idea so I don’t think we should use that to influence the decision here too much.

**Comment by sofiafaro-da** [comment]
> I’m not following this. If daml-helper just calls daml sandbox won’t that pick up the platform-version automatically with my proposal and it doesn’t need to be aware of this?

`daml-helper` does not call `daml sandbox`, both `daml sandbox` and `daml start` go through `daml-helper` which runs the `daml-sdk.jar`

**Comment by cocreature** [comment]
Oh good point but it could do that and then  we would sidestep the whole issue no?

**Comment by sofiafaro-da** [comment]
Point is that there is no clean separation of "SDK commands" and "platform commands", it has to be introduced somewhere, and adding a lot of logic to the assistant to do it seems like a bad idea to me.

>  It still seems weird to me that not everything that is needed is guaranteed to be installed once the assistant hands over control.

If this is th issue, then perhaps newer versions of the assistant could try to auto-install `platform-version` ahead of time as well, but it still runs commands through the SDK version's `daml-helper`? That way the helper never triggers a new install, and all the platform vs SDK logic can stay in the helper.

**Comment by sofiafaro-da** [comment]
I guess the thing I want to avoid is a sudden transition that breaks compatibility. The end goal could be having that kind of logic in the assistant itself, but as an intermediate step, that logic goes into the helper, and we later migrate some of it to the assistant if we think it would be better. (Although, this is perhaps a bit ingenuous, since if it works fine in the helper, we probably won't find a reason to move it to the assistant.)

**Comment by cocreature** [comment]
Alright that seems sensible, then let’s at least start with putting it in the helper (I really wish that executable hadn’t turned into the monster it is increasingly becoming :crying_cat_face:). Thanks a lot for your input!

**Comment by cocreature** [comment]
Fixes #6736
