### ISSUE TITLE
Unreadable text in DAML Studio / contract table view

### ISSUE THREAD

**Issue by gaborh-da** [digital-asset/daml#6718]
We experience the following with `1.3.0-snapshot.20200708.4686.0.95dfa18e`:
![Screenshot from 2020-07-14 11-47-07](https://user-images.githubusercontent.com/33900822/87411414-fce12a00-c5c7-11ea-9a56-10dfa6920e5b.png)

The checkbox "Show detailed disclosure" does not seem to do anything.

We used the following artificial example when the problem appeared.
```
module Main where

template Debrecen
  with
    party : Party
    o: Party
    o2: Party
  where
    signatory party
    observer [o, o2]
    controller party can
      Call : ContractId Budapest
        with
          c: ContractId Eger
          other: Party
        do
          exercise c Tx with other = other
          create Budapest with party

template Budapest
  with
    party : Party
  where
    signatory party

template Eger
  with
    party : Party
    party2 : Party
  where
    signatory party
    controller party can
      Tx : ContractId Eger
        with other : Party
        do
          create this with party2 = other

mini = scenario do
   party <- getParty "A"
   o <- getParty "B"
   o2 <- getParty "C"
   e <- party `submit` do
          e <- create Eger with party = party, party2 = party
          c <- create Debrecen with ..
          exercise c Call with
            c = e
            other = o2
   party `submit` (fetch e)
```

**Comment by garyverhaegen-da** [comment]
Hi @gaborh-da,

I did see a very similar issue while implementing this new feature. I believe this is due to a desynchronization between the VSCode extension and the SDK.

More specifically, the transaction view HTML is created by the SDK (by way of the `daml ide` process interacting with VSCode), while the corresponding JS and CSS files are embedded in the extension itself. What you are seeing is, I believe, the result of using this "new" HTML with the "old" CSS and JS. To double-check this, would you mind running `code --list-extensions --show-versions`? I'm hoping the result will be something like

```
DigitalAssetHoldingsLLC.daml@1.2.0
```

We only update the Marketplace extension for stable releases. If you want to test the full 1.3 experience, you can use the following command:

```
daml studio --replace=always
```

which should load the extension from the SDK instead of from the marketplace.

**Comment by gaborh-da** [comment]
@garyverhaegen-da thank you, using `daml studio --replace=always` fixes my issue. The table view looks nice.

**Comment by garyverhaegen-da** [comment]
I can confirm that under this condition:

```
$ code --list-extensions --show-versions
DigitalAssetHoldingsLLC.daml@1.2.0
```

the following steps end up reproducing the reported error:

```
$ cd $(mktemp -d)
$ daml install 1.3.0-snapshot.20200708.4686.0.95dfa18e
Installing SDK version 1.3.0-snapshot.20200708.4686.0.95dfa18e
Downloading SDK release.
[=====================================================================] 100%
$ daml new t
Created a new project in "t" based on the template "skeleton".
$ cd t
$ daml studio
```

And I can confirm that, at least for me, exiting VSCode and running:

```
$ daml studio --replace=always
```

fixes it. Afterwards, I get:

```
$ code --list-extensions --show-versions
DigitalAssetHoldingsLLC.daml-bundled@1.3.0-snapshot.20200708.4686.0.95dfa18e
```

Since it looks like it fixed it for you too, would you mind closing this issue? Or do you think we should take further action?

**Comment by gaborh-da** [comment]
Yes, it fixed the error for me, I think we can close it.
