### ISSUE TITLE
Make it easier to run pure functions in DAML REPL

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#6780]
Currently the only way to run a pure function in DAML REPL is to wrap it in `debug`. That’s rather annoying. There are a few options for improving this:

1. Keep requiring something of type `Script a` but print out the result automatically if `a` is an instance of `Show` and is not `()`. GHCi does this.
2. Also allow non-Script stuff and print out the result if it’s an instance of `Show`. GHCi does that but here it errors out if it’s not an instance of `Show`.
3. something else?

**Comment by garyverhaegen-da** [comment]
Regarding the options you lay out, I have a preference for 1, because it makes it very clear that every line could be having an effect on the ledger you are connected to, and that keeps users aware of it. I would be a bit concerned about having "native" support for pure expressions in the sense that it may give users a false sense of security, and they may end up executing a side-effect unintentionally. This is not a big issue when the side effect is to print something in the GHCi repl, but for the DAML repl, this means writing to a remote ledger with no undo function. I may be overcautious here, though. If we do go down that path, the error message when the expression is not of type `Script` should be improved, at the very least to append a `try return <EXPR>` at the end.

On printing, I think the GHCi behaviour is confusing. Specifically, I think we should always print "the result"; if it is `()`, we can just print `()`, there's no good reason to skip it. If it happens to be some type that does not have a `Show` instance, we should say that, e.g. `Return type does not have a Show instance: TYPE`, and maybe point out how to define one. We should also imo prefix the return value with some common symbol so it's easy to differentiate output from prints, e.g.

```
daml> debug $ 1
1
=> ()
daml>
```

Finally, I think this may be a good opportunity to bring back some idea we discussed a long time ago: what if instead of relying on Show instances, we printed out the JSON representation of the return value instead (or in addition)? Last time I brought it up it was incompatible with a technical limitation of the scenario service, but I don't think this applies here.

**Comment by cocreature** [comment]
Currently I still have a preference for the GHCi behavior but I’ve clearly gotten very used to it so I’m willing to be convinced here. Deleting a file in GHCi also has no easy undo function and we are only talking about allowing pure functions not allowing effects in cases where they were not be possible before.

As for the JSON representation, I find it very useful to get expressions that I can copy and paste back as valid DAML expressions so I would at least like the JSON representation to be optional.

**Comment by garyverhaegen-da** [comment]
> As for the JSON representation, I find it very useful to get expressions that I can copy and paste back as valid DAML expressions so I would at least like the JSON representation to be optional.

That is a good point, though I suppose there is no guarantee `Show` instances give you that. Maybe either print both or have a cli switch? Or drop it. I see theoretical value in having an easy way for people to play with JSON/DAML matchings when starting out with the JSON API, but I may be overestimating the value and this may not be the right place for it.

**Comment by cocreature** [comment]
Having thought about it for a bit and based on the feedback on discourse, I’m going to copy GHCis behavior for now.
