### ISSUE TITLE
Hard-coded party allocation timeout

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#6880]
Party allocation is subject to an hard-coded 30 seconds timeout.

Q: should this be made configurable?
Q: should the asynchronous party allocation process be subject to the same time model as commands (incl. skew)?

**Comment by dasormeter** [comment]
@stefanobaghino-da same hard-coded limitation also applies to package upload

**Comment by stefanobaghino-da** [comment]
@SamirTalwar-DA @gerolf-da If you have any detail to add, it could be worth adding it here.

**Comment by SamirTalwar-DA** [comment]
@gerolf-da and I discussed a bunch of potential approaches to this. I'll try and outline them here, along with potential downsides.

 1. **Increase the hard-coded timeouts.** This is the simplest solution, though I find it quite unsatisfying. The value of 30 seconds seems to have been chosen without too much thought to large projects or ledgers with long round-trip times. Simply increasing the timeouts to something much bigger (e.g. 15 minutes for party allocation, because there are DARs that can take minutes to process) would make requests that currently fail go through. This seems like a hack: at some point, we'll have to change it again, and I doubt there exists a value that will make everyone happy.

 2. **Add a request field for the timeout.** @dasormeter correctly points out that the config management service already supports this, although it's using the `maximum_record_time` field, which suggests that it's a holdover from the old time model and we're misusing it. (The comment on the field definitely suggests as much to me.) This seems like a more flexible approach than increasing the timeouts, but it adds a field that we may decide not to use in the future, and I am wary of modifying these APIs when there might be a solution that doesn't require making the message structure more complicated.

 3. **Push the timeout to the client.** GRPC already has a mechanism called [deadlines](https://grpc.io/blog/deadlines/) which we could expose somehow in our Scala bindings. This allows for flexible timeouts using an already-established interface, rather than adding a field to duplicate this behavior. Handling this would also mean that we would appropriately handle other forms of request failure, such as a disconnection or the user explicitly cancelling.

    It looks as if we can use [Context.current().addListener(CancellationListener, Executor)](https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html#addListener-io.grpc.Context.CancellationListener-java.util.concurrent.Executor-) to watch for a downstream cancellation and cancel the polling accordingly, but I'm not sure if this would work. We'd need to try it.

 4. **Rewrite the admin services to behave asynchronously.** The synchronous calls are useful for simple purposes, but customers will probably outgrow them eventually. I believe this is one of the reasons we provide both the CommandService, which lets you submit a command and wait for completion in one call, and the pair of CommandSubmissionService and CommandCompletionService, which allow you to be more flexible about waiting for completion. Similarly, we may want to provide a way to asynchronously upload a package or allocate a party, and then watch for it on a stream at the client's leisure.

    Personally, I favor _only_ offering asynchronous endpoints and adding behavior into the Scala bindings to join them up in a synchronous fashion. However, @gerolf-da rightly points out that if we do that, we will need to do so for any other languages we support as well.

    This would be a much bigger change and would require a lot of thought and design into how the API should look. The current admin endpoints are fairly haphazard, and I think I'd like to see them become more cohesive in the process of taking this approach.

The only one of these I am particularly against is (2), as it would add message fields for behavior that I think belongs in the client, not the server, and especially not in the protocol in which they communicate.

I propose we implement (1) as soon as possible, to unblock users reliant on these endpoints, and then implement (3) or (4) in the future. My preference would be to implement (3) soon, and (4) for the next version of the DAML API (which I guess would be v2.0).

**Comment by cocreature** [comment]
Maybe a small addition to of 3: The `daml ledger` commands already make the deadline configurable so as soon as this is handled on the server side things should work automagically (although the Haskell gRPC library is great at breaking my expectations).

**Comment by stefanobaghino-da** [comment]
Why implementing (1) at all? Is the severity so high that we can't afford to take a few days to implement and thoroughly test a more robust solution?

**Comment by SamirTalwar-DA** [comment]
My understanding is that users are already hitting timeouts during DAR uploads. Perhaps party allocation on certain ledgers too; @dasormeter, can you comment?

**Comment by stefanobaghino-da** [comment]
We do indeed, I'd like to understand whether that's so disrupting we cannot do otherwise but put a band-aid.

**Comment by SamirTalwar-DA** [comment]
Created a PR just in case we want this in for tomorrow's release. We can, of course, close it.

**Comment by dasormeter** [comment]
@stefanobaghino-da / @SamirTalwar the consistently failing thing today happens for any of the distributed ledgers (corda, fabric, besu and vmware) if you do not set the concurrent run to 2 or lower or (as is done with vmware) you explicitly run one test suite at a time

so it would be great if we have a fix for this in the next 1.4.0 release, ideally - as it would massively speed up integration test runs and allow us to up concurrency to use all available cores, and avoid blinks on 30s timeouts

**Comment by drewharding-da** [comment]
@stefanobaghino-da - I think it's not that disrupting, and a band-aid would be a quick fix at a later stage if needed. Probably solving this problem properly would be a good focus.

**Comment by SamirTalwar-DA** [comment]
@dasormeter: I'm not convinced increasing the timeout will actually speed you up. If the ledger can't allocate parties reliably within 30 seconds, I would have expected that the tests would just start timing out for different reasons. Have you tried patching the Ledger API and testing this with one of those distributed ledgers?

**Comment by stefanobaghino-da** [comment]
In the case of certain distributed ledgers, we also received feedback that the issue exists only when using H2 as the indexing database and that it goes away when using PostgreSQL.

**Comment by dasormeter** [comment]
> In the case of certain distributed ledgers, we also received feedback that the issue exists only when using H2 as the indexing database and that it goes away when using PostgreSQL.

@stefanobaghino-da think that is true for corda
for besu the timeouts are even with postgres.
for vdaml it is running with postgres now
for fabric i can try with or without postgres (it uses h2 by default in CI)

so i think it is more a function of how close to that 30s worst case threshold a distributed ledger is, and perhaps when running locally you become resource-constrained more readily with in memory h2, but just guessing

**Comment by dasormeter** [comment]
> @dasormeter: I'm not convinced increasing the timeout will actually speed you up. If the ledger can't allocate parties reliably within 30 seconds, I would have expected that the tests would just start timing out for different reasons. Have you tried patching the Ledger API and testing this with one of those distributed ledgers?

@SamirTalwar have not tried with changes to latest sdk head because besu is on 1.3.0 release and i think there are already a few breaking changes in 1.4.0-snapshot to deal with -- i can give it a go though

**Comment by cocreature** [comment]
There have been no changes. What @SamirTalwar is suggesting I beileve is that you patch the timeout locally and test things out.

**Comment by dasormeter** [comment]
> There have been no changes. What @SamirTalwar is suggesting I beileve is that you patch the timeout locally and test things out.

alright trying a daml-sdk-head build off `git checkout v1.3.0` but suspect this is going to take a while since it needs to rebuild the world

**Comment by mziolekda** [comment]
I would like to chip in favor of 2 but with a slight twist. I would like us to implement the same time model across all ledger requests. Latency is an un-erasable property of all ledgers and we have embraced this fact already by promoting it front and center in the CommandSubmission Service. It contains min_ledger_time_abs and min_ledger_time_rel fields that allows client applications to take full control of that aspect. We should add it symmetrically to all services that write to the ledger. It should not be hidden in the gRPC meta fields which might or might not be supported by specific ledger bindings and also don't carry a similar semantic load.

**Comment by gerolf-da** [comment]
I concur. Option 2 is purely an addition (in terms of API), should be fairly straight forward to implement, and gives enough flexibility to users so that we don't have to adjust regularly.

**Comment by dasormeter** [comment]
yeah #2 would help -- the real lack of parity we have on this now is that is configurable / controllable for transaction submission but not for party allocation and package upload, and usually those are the first two things you need, so configurable transaction submission on its own doesn't help

**Comment by SamirTalwar-DA** [comment]
I'm not convinced we can avoid supporting deadlines, even with option 2.

Let's say the user specifies a gigantic timeout (e.g. 1 day). They upload a package and for some reason, there's an error, and we never receive a completion.

Let's also imagine that the user themselves have an error, and they stop waiting after 5 minutes. Maybe they got bored, maybe there's a network connection failure, maybe they saw the error in the logs themselves and decided to cancel.

In this event, we will keep polling our index for the arrival of this package for the whole day. Even though the user doesn't care any more.

Implementing support for deadlines will also mean we implement support for other client-side cancellations, such as a network failure. This means we can stop polling as soon as they are unable to receive the response.

What I'm saying is: either way, we need it.

**Comment by stefanobaghino-da** [comment]
Fixed by https://github.com/DACH-NY/daml-on-kv-oem-integration-kit/commit/cad401653628c7e8489c86700f0cb26d4dcad9dd
