### ISSUE TITLE
Scenario context management in damlc integration tests is racy  

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#6910]
The way contexts are handled in damlc isn’t safe in a concurrent setting and occasionally leads to flaky issues of the form
```
2020-07-29T09:17:32.3056783Z       Message: 
2020-07-29T09:17:32.3057635Z         "Scenario service backend error: BErrorClient (ClientIOError
2020-07-29T09:17:32.3058173Z         (GRPCIOBadStatusCode StatusNotFound (StatusDetails {unStatusDetails = \"
2020-07-29T09:17:32.3058933Z         context 115 not found!\"})))"
```
This has been a problem for a while but the split into one test per LF versions seems to have resulted in us running into this issue more frequently.

**Comment by hurryabit** [comment]
After chatting with @cocreature, my current understanding of the issue is as follows:

Since the scenario service does not support canceling scenario runs, the IDE runs each scenario in a separate thread that keeps running even if we lose interest in the outcome of the scenario because something has changed. This loss of interest can lead to the scenario context for a scenario being garbage collected while the scenario is still running in the scenario service. This would lead to the error message documented above. The integration tests for `damlc` are particularly prone to this race condition since they change the files of interest with high frequency.
