### ISSUE TITLE
High-level API of triggers needs to reexport Message

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#6968]
It’s impossible to implement `updateState` without importing the low-level API which is a bit silly.

**Comment by S11001001** [comment]
I'm confused by this issue; as far as I can tell `Daml.Trigger` has reexported `Message` since #3226. Or is the goal to _not_ reexport `Message`?

**Comment by cocreature** [comment]
Good point, what we need is to transitively expose everything referenced by `Message`. In particular, we are missing `Command` I believe which is pretty crucial to inspect the `Message`.

**Comment by S11001001** [comment]
We have had `Command` since the beginning, but we appear to be missing `TransactionId`. We are also missing `Event`, its constructors, and their contents, but my interpretation is that it is desirable for `Event` to be opaque to the high-level API and queryable only with functions.

We can trivially constructively expose everything by moving all relevant `data` and `newtype` declarations to a separate module and reexporting that module from `Daml.Trigger`. If complete transparency is what we want then I think this is the only reasonable way to achieve it in a way that relieves the maintenance burden. However, it appears that we want some elements to be opaque, e.g. the `CommandId` data constructor.

**Comment by cocreature** [comment]
Apologies, somehow this slipped through. I think some way to access `Event` is required, otherwise you can’t really implement any useful `Update`. Keeping the various ids abstract seems fine. @S11001001 You mentioned that `Event` should be opaque. I definitely agree on `Created` and `Archived` and accessing that using `fromCreated`/`fromArchived`. How do you feel about exposing `Event` itself instead of 2 functions to match on it? Being able to match exhaustively here seems nice to me.

**Comment by S11001001** [comment]
@cocreature I think exposing `Event`'s data constructors makes sense, and keeping the `Created` and `Archived` records opaque.
