### ISSUE TITLE
Is the --application-id option in the JSON API unused?

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7162]
The JSON API has an `--application-id` option in its CLI. As far as I can tell, this option is only used to initialize the `LedgerClientConfiguration`.

However, if you look at what [this is used for](https://github.com/digital-asset/daml/blob/0e833c02a450f7ce6f5783328785c2081ced8ffc/ledger/ledger-api-client/src/main/scala/com/digitalasset/ledger/client/LedgerClient.scala#L51), it is only passed to the (asynchronous) `CommandClient`. As far as I know the JSON API purely relies on the `SynchronousCommandClient`.

This means that effectively the value of `--application-id` appears to be completely unused and the only relevant application-id is the one in the JWT which is used for command submissions.

Am I missing something here?

If not, I see two options:
1. Deprecate the option and turn it into a noop.
2. Enforce that the option matches up with the value in the token.

I think it’s perfectly reasonable to have multiple clients with different application ids running over the same JSON API so I’d prefer option 1. This is however slightly dangerous since we are relying on the current behavior of `LedgerClientConfiguration` which would in principle change. I think what this really points at is that the API for `LedgerClient` is very confusing and we should change if and how it uses the application id.

**Comment by cocreature** [comment]
cc @S11001001 @leo-da

**Comment by S11001001** [comment]
I think we would be trying to be too smart by doing anything else than what we are doing. If it is reasonable to have multiple applications with different application IDs, then it is also reasonable for yet another application ID to be passed in as `LedgerClientConfiguration`.

Regarding its being unused:

I don't like the "pattern" of using the same arguments for different functions, some ignored in each, just for some kind of symmetry or "consistency". Consistency should be a layer on top, not baked into the required interface. If it has different arguments, it should have a different type.

If supplying an application ID is what we demand of ordinary ledger clients under threat of using that data in the future, then we should obey that demand rather than exploiting unchecked dynamic facts about the current implementation that would produce no warning were they changed. If we do not wish to demand that in all circumstances where `LedgerClientConfiguration` is a required argument, then we should permit `LedgerClientConfiguration`'s type to vary. Perhaps by means of a type parameter, perhaps by other means.

**Comment by cocreature** [comment]
Yeah, agreed on not trying to be too smart here. What I’d like to avoid is having a parameter exposed to users without being able to tell them what they should use this parameter for.

I also agree that passing around arguments to lots of functions and having it be unused in most on them is a bad idea. If we were starting from scratch, I’m tempted to just rip out the application id from `LedgerClientConfiguration`. Given that the Scala bindings are not publically supported that wouldn’t be that unreasonable but we could also just make it optional for now. Then the JSON API doesn’t need to be smart or careful and can just not pass it and it’s clear that it’s not used.

**Comment by S11001001** [comment]
We should make the types make it clear that it is required for those specific use cases where it is required; I would rather not have an `Option` that suggests otherwise. In the opposite case, we can also make it clear that it doesn't matter, such as (for compatibility) by making the type `Any`, or `E forSome { type E }` if you think the former would make people suspicious, or `Unit` if we can just get clients to change right away.

**Comment by cocreature** [comment]
I’d like to make it never required. The option (or probably an overload, I forgot if you can do this in Scala) would just allow us to deprecate this in one release before we kill it in the next one.

**Comment by leo-da** [comment]
Application ID is a required field (at least it was) in `com.daml.ledger.client.configuration.LedgerClientConfiguration`

I don't know what the semantics of this field in the `LedgerClientConfiguration`.

You have to specify a valid `LedgerClientConfiguration` when instantiating a `LedgerClient`.

When we were designing the JSON API it seemed wrong not to allow overriding the default `ApplicationId("HTTP-JSON-API-Gateway"),`. We had to provide a way to override the default value if/when Sandbox/Ledger starts rejecting connections with invalid Application ID.

BTW the Application ID from the command line option only used when establishing the Ledger connection (we don't have JWT at this time). When sending commands and requests to the Ledger we are using Applciation ID from the JWT.

**Comment by leo-da** [comment]
> 1. Deprecate the option and turn it into a noop.

need to understand the semantics of the Application ID in the `LedgerClientConfiguration`.

> 2. Enforce that the option matches up with the value in the token.

Can't do this.... what JWT do you want to use? Every client has their own JWT with their own Application ID. We are re-using `LedgerClient` instance. It is supposed to be thread-safe

**Comment by cocreature** [comment]
> > 1.
> 
> need to understand the semantics of the Application ID in the `LedgerClientConfiguration`. What if Sandbox/Ledger starts enforcing some rules based on this Application ID.

As far as I can tell it is only used in the asynchronous command submission service which is not used by the JSON API (it uses the synchronous command service). So it literally never matters.



> > 2. Enforce that the option matches up with the value in the token.
> 
> Can't do this.... what JWT do you want to use? Every client has their own JWT with their own Application ID. We are re-using `LedgerClient` instance. It is supposed to be thread-safe

Not sure I’m following. Currently you just take the application id from the JWT and ignore the one from `LedgerClientConfiguration`. Failing requests if there is a mismatch seems possible. I don’t think it’s useful though. As you said, each client can have their own application id and I think that’s something we should keep.

**Comment by leo-da** [comment]
@cocreature just trace the usage of this `clientConfig` val:
https://github.com/digital-asset/daml/blob/3ecfcc918c4e9e49531affedde63f96d82d3cc36/ledger-service/http-json/src/main/scala/com/digitalasset/http/HttpService.scala#L102-L108

You cannot connect to the Ledger without LedgerClientConfiguration. However we create it with `ledgerIdRequirement = LedgerIdRequirement.none`, need to experiment what happens when `applicationId` is an empty string... it should have been Option[String] if it is really optiona.

**Comment by leo-da** [comment]
> Not sure I’m following. Currently you just take the application id from the JWT and ignore the one from `LedgerClientConfiguration`

that is exactly what we are doing. However you create ledger connection before you even have a JWT.

**Comment by cocreature** [comment]
I know you need to supply it atm. My point is there is zero value in supplying it for the JSON API and we should refactor `LedgerClient` to remove this. The only case where it is used is https://github.com/digital-asset/daml/blob/593664497025b572e25fef12d843f57a9def66f7/ledger/ledger-api-client/src/main/scala/com/digitalasset/ledger/client/LedgerClient.scala#L51 which is not used by the JSON API.

**Comment by leo-da** [comment]
sure, let's remove it and stick an empty string or a hardcoded "fooID" in the `LedgerClientConfiguration` if we know that it would never be used/enforced by the ledger.

**Comment by leo-da** [comment]
> we should refactor `LedgerClient` to remove this.

it is public API, I don't think we want to break it. Unless we provide LedgerClientV2 and LedgerClientConfigurationV2.
