### ISSUE TITLE
Codegen needs integrations with Maven, SBT and Gradle.

### ISSUE THREAD

**Issue by nicholassmith-da** [digital-asset/daml#72]
The developer community will expect that the java codegen integrates well with Maven, SBT and Gradle.

The goal should be that the build tool plugins should only call codegen if the generated Java sources are older than the DALF sources. Incremental code generation would be a possible optimisation that would benefit projects with very large DAML models.

**Comment by leo-da** [comment]
According to @francesco-da this story is low priority. We won't do it right now.

**Comment by leo-da** [comment]
max.deliso  
... Either way, the relevant piece is just:
```
managedSourceDirectories in Compile += baseDirectory.value / "scala-codegen" / "src" / "main" / "scala"
lazy val generateScalaCode = taskKey[Seq[File]]("Generates scala code from DAML models")
generateScalaCode := {
  val outputDirectory = baseDirectory.value / "scala-codegen"
  Process("daml" :: "build" :: Nil) ! ;
  Process("daml" :: "codegen" :: "scala" :: Nil) ! ;
  walkFiles(outputDirectory).filter(_.isFile).filter(_.name.toLowerCase.endsWith("scala"))
}
def walkFiles(dir: File): Seq[File] = {
  val these = dir.listFiles
  these ++ these.filter(_.isDirectory).flatMap(walkFiles)
}
sourceGenerators in Compile += generateScalaCode
```

max.deliso  < 1 minute ago
some caveats: this has some drawbacks because it doesn’t handle template renames nicely: it will fail to build because it won’t know how to delete the fields from the previous name scheme

max.deliso  < 1 minute ago
this can be worked around w/ some other build logic, cc @davin who was looking at it before

**Comment by gerolf-da** [comment]
Closing this issue as the example provided by Max is sufficient to quickly integrate scala codegen into SBT.
