### ISSUE TITLE
HasField instance for generic variant types used over a data-dependency is not found by LF typechecker.

### ISSUE THREAD

**Issue by jberthold-da** [digital-asset/daml#7284]
This is in a package dependency configuration where one package depends on two others, as a _data_ dependency.
```
        package 3
          /    \
    data /      \ data
        /        \
package 1       package 2
```
When defining a two-parameter class within package 3 and an instance of it that links a type from package 1 to one from package 2, the *LF* typecheck fails (after a successful GHC type check/inference).
Suspected cause: attempt to specialise the instance code. But note that no concrete instance is known in this code, all types still have type parameters.

Note that this compiles fine when the dependencies between the packages are _full_ (not data-) dependencies.
```
data-depend-triangle $ ll
total 20
drwxr-xr-x  5 jost jost 4096 Aug 31 18:03 ./
drwxr-xr-x 13 jost jost 4096 Aug 31 18:02 ../
drwxr-xr-x  4 jost jost 4096 Aug 31 18:10 package1/
drwxr-xr-x  4 jost jost 4096 Aug 31 18:10 package2/
drwxr-xr-x  4 jost jost 4096 Sep  1 09:41 package3/
data-depend-triangle $ more package?/daml.yaml
::::::::::::::
package1/daml.yaml
::::::::::::::
sdk-version: 1.4.0
name: package1
version: 0.0.1000
parties:
  - 00001
dependencies:
- daml-prim
- daml-stdlib
source: src
::::::::::::::
package2/daml.yaml
::::::::::::::
sdk-version: 1.4.0
name: package2
version: 0.0.1000
parties:
  - 00001
dependencies:
- daml-prim
- daml-stdlib
source: src/
::::::::::::::
package3/daml.yaml
::::::::::::::
sdk-version: 1.4.0
name: package3
version: 0.0.1000
parties:
  - 00001
dependencies:
- daml-prim
- daml-stdlib
data-dependencies:
- ../package1/.daml/dist/package1-0.0.1000.dar
- ../package2/.daml/dist/package2-0.0.1000.dar
source: src
data-depend-triangle $ more package?/src/*daml
::::::::::::::
package1/src/Package1File.daml
::::::::::::::
module Package1File where

data AVariant x y = V1 with theX: x
                  | V2 with theYs: [y]
::::::::::::::
package2/src/Package2File.daml
::::::::::::::
module Package2File where

-- identical to the definition in Package1File
data AVariant x y = V1 with theX: x
                  | V2 with theYs: [y]
::::::::::::::
package3/src/Package3File.daml
::::::::::::::
daml 1.2
module Package3File where

import Package1File qualified as P1
import Package2File qualified as P2

class Convert a b where
  convert : a -> b

instance Convert a a' => Convert [a] [a'] where
  convert = fmap convert

instance (Convert x x', Convert y y') =>
         Convert (P1.AVariant x y) (P2.AVariant x' y') where
  convert = \a -> case a of
            P1.V1{} ->
              P2.V1 with
                theX = convert a.theX
            P1.V2{} ->
              P2.V2 with
                theYs = convert a.theYs
data-depend-triangle $ for i in 1 2 3; do (cd package$i && daml build); done
Compiling package1 to a DAR.
Created .daml/dist/package1-0.0.1000.dar
Compiling package2 to a DAR.
Created .daml/dist/package2-0.0.1000.dar
Compiling package3 to a DAR.
File:     src/Package3File.daml
Hidden:   no
Range:    1:0-100001:0
Source:   DAML-LF typechecker
Severity: DsError
Message: 
  error type checking value Package3File.$cconvert1:
  unknown value:
  e196c7990292b3791ab23cab64be3c89edcd06e3707efa7896d504c5ab29f3b4:Package1File:$fHasField"theX"AVariantx_ait
ERROR: Creation of DAR file failed.
data-depend-triangle $ 
```

**Comment by sofiafaro-da** [comment]
The Convert class and multiple dependencies don't seem to be required here.
I've managed to reproduce this as follows.

Package 1 has code:

```
module P1 where
data T x y
   = A with a: x
   | B with b: y
```

Package 2 has data-dependency on Package 1, and has code:

```
module P2 where
import P1
getA : T x y -> x
getA t = t.a
```

Necessary ingredients to reproduce seem to be:

- using a field selector (i.e. HasField instance) for variant type
- over a data-dependency
- when the type has type parameters

**Comment by sofiafaro-da** [comment]
I've managed to track down the cause of this. Unfortunately, it points to a fundamental problem with our current approach to typeclass instances and data-dependencies. 

The problem is that the data-dependencies rely on the exact name for the dictionary function as generated by GHC. In the case of the `HasField` instance above, the dictionary function name `$fHasField"a"Tx` includes the variable name `x`, but after going through damlc we've lost the original variable name, so we get something like `$fHasField"a"Tx_ait` instead in the generated stub, which doesn't exist in the original package, so the LF ends up with a spurious reference (resulting in the error we see).

This shows up in other situations! For example, if we have a single type with multiple instances, e.g. a type `data T x = T x` with `instance Show (T Int)` and `instance Show (T Bool)`, we'll have apparently a 50% chance that the correct instance will be matched, because the name given to the dictionary function depends on the order of the original code, which we lose during compilation to LF -- `$fShowT` and `$fShowT0`. If we have a third instance, e.g. `instance Show (T Text)`, the chance that the compiler will give you the right instance is a mere 1/3! = 1/6 = 16%, if it were up to chance. With a fourth instance it becomes 1/4! = 1/24 = 4.2%. And so on. Point being, the order of instance declarations is not something we're controlling for, so it's almost impossible to get it right by chance.

**Comment by cocreature** [comment]
Does the renaming happen in the conversion to core or during renaming/typechecking? If it’s the atter, this is another indicator that generating interface files directly is probably a better option than going via source files.

**Comment by sofiafaro-da** [comment]
AFAICT from looking at GHC code, dictionary function names are determined during conversion to core.

**Comment by cocreature** [comment]
Probably easiest to use the various dump options provided by GHC to confirm that.

**Comment by sofiafaro-da** [comment]
Looks like the generated names are in the typechecked ast.

**Comment by hurryabit** [comment]
@jberthold-da In your specific example, there's an easy workaround for the issue:
```haskell
instance (Convert x x', Convert y y') =>
         Convert (P1.AVariant x y) (P2.AVariant x' y') where
  convert = \a -> case a of
            P1.V1 theX ->
              P2.V1 with
                theX = convert theX
            P1.V2 theYs ->
              P2.V2 with
                theYs = convert theYs
```
(I think, that's more idiomatic code anyway and it will run faster because you avoid a second pattern matching in `a.theX` resp. `a.theYs`. IMO, having record projections on variant types is a bit of a wart in DAML.)

Given that you have this simple workaround, how urgent is it for you that we fix this bug?

**Comment by jberthold-da** [comment]
I agree using patterns as above is more idiomatic, but we are _generating_ this code from a DAML LF representation where all variant constructors have exactly one argument, and the internal records are inlined afterwards.
It will be more complicated to generate/inline the respective code when there are multiple fields.
We can try this, though.

**Comment by hurryabit** [comment]
@jberthold-da We fixed this particular issue. It will be part of SDK 1.6.0.
