### ISSUE TITLE
LF: Mark nodes that correspond to "by key" operations.

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#7622]
This issue is concerned with: 
- marking `Exercise` and `Fetch` nodes in a transaction with a `byKey` flag to indicate if those nodes where created by a `ExerciseByKey` and `FetchByKey` respectively. (done)
- add the flag in the next transaction serialization format + transaction spec (done #9632 and #9642) 
- change validation to take into account the flag for newer version of LF/transaction. (done #9641)

**Comment by remyhaemmerle-da** [comment]
cc @hurryabit @sofiafaro-da

**Comment by hurryabit** [comment]
I assume the only way you can exercise by key is via the Ledger API since there's no primitive to do so in DAML-LF. Should we change that and add an actual `exerciseByKey` primitive to the next version of DAML-LF? This might improve transaction sizes since we won't have a `fetchByKey` node followed by an `exercise` node anymore. cc @andreaslochbihler-da

**Comment by andreaslochbihler-da** [comment]
We already have such a flag in the transaction metadata that's output by DAML engine. I'm happy if we can move this flag into the transaction tree itself. That saves in Canton a few consistency checks between the metadata and the transaction tree. I'm also in favor of adding the flag to exercise nodes in the tree. If the flag is set, this then corresponds to a `exercisebyKey` action just like a plain `Fetch` node with the flag represents a `fetchByKey` action.

Regarding `exerciseByKey`, we're re-experiencing the same story as for ordinary `fetch + exercise`. A while ago, every DAML `exercise` was compiled into `fetch + exercise` because the original semantics of `exercise` didn't check activeness. If we can remove the redundancy now for `byKey` as well, I'm for it.

**Comment by hurryabit** [comment]
@remyhaemmerle-da Given that @andreaslochbihler-da would be interested in us producing an `exercise` node with `byKey = true` for every `exerciseByKey` in the DAML code and it would probably make things clearer, shall we add such an `exerciseByKey` primitive to DAML-LF?

**Comment by remyhaemmerle-da** [comment]
> shall we add such an `exerciseByKey` primitive to DAML-LF?
I am fine with that. I do not expect this to be difficult.

**Comment by hurryabit** [comment]
> I am fine with that. I do not expect this to be difficult.

Cool. Let's do it then while we're at cleaning up things in this regard. Would DAML-LF 1.9 be a realistic target?

**Comment by cocreature** [comment]
fixed!
