### ISSUE TITLE
Transitive data-package dependency seems to not work

### ISSUE THREAD

**Issue by da-tanabe** [digital-asset/daml#7633]
The setup is a little involved, so I created a repo to illustrate the bug: https://github.com/da-tanabe/package-dep-test-case

But essentially, if B has a data-dependency on A, and C has attempts to take a _regular_ dependency on B, compilation fails with an error:

```
$ make
cd model && daml build
Compiling model to a DAR.
Created .daml/dist/model-1.0.0.dar
cd service && daml build
Compiling service to a DAR.
Created .daml/dist/service-1.0.0.dar
cd trigger && daml build
File:     
Hidden:   no
Range:    1:0-100001:0
Source:   compiler
Severity: DsError
Message: 
  <command line>: cannot satisfy --package "service-1.0.0(Service as
  Pkg_41ef1525f6daa2abb2581a0bd6efcd55e2ee83aa5abaeea30749434a3d2ed307.Service)":
  service-1.0.0 is unusable due to missing dependencies:
  model-1.0.0
  (use -v for more information)
Failed to compile interface for data-dependency: model-1.0.0
```

If I switch my example to use non-data-dependencies, the same dependency graph otherwise works fine. Additionally, C can take a _data_ dependency on B, and that also seems to work fine. 

Is this _supposed_ to work? It isn't clear from the docs how transitive dependencies, `data-dependencies`, and `dependencies` interact with each other or whether the import chain that I am attempting is supported.

**Comment by cocreature** [comment]
I think this is expected but we probably need clearer docs:
- `dependencies` is never transitive, you need to add the dependencies of your dependencies separately.
- `data-dependencies` is transitive.

Generally, maxing `dependencies` and `data-dependencies` is something that I’d only recommend if you need it. In your example, what is stopping you from having a data-dependency on `B`?

**Comment by da-tanabe** [comment]
A is comprised of essentially template definitions that I wish to change as little as possible; B is mostly role contracts that can change on a regular basis, but the upgrade for them is a little simpler (drop the old role, replace with the new one, and since they both operate on templates from A that I don't expect to change much, there's less going on); C are triggers, which I'd like to avoid deploying to the ledger.

I was getting a misleading error from VS Code complaining about a symbol not exported when I tried to exercise a choice defined in B from a test script in C, so I thought maybe I hit a dead end. But the command line told me different errors and when I restarted VS Code they went back in sync again, and I was eventually able to accomplish what I wanted to just with `data-dependencies`!

I agree the docs could be clearer…and related, when do I actually _need_ `dependencies` then?

(Separately happy for this issue to be closed, potentially in favor of one that clarifies `dependencies` and `data-dependencies`.)

**Comment by hurryabit** [comment]
`data-dependencies` have two significant downsides:

1. Initializing the package database is slower for `data-dependencies` than for regular `dependencies`. Depending on the size of the main DALF, this might be a problem or not.
1. `data-dependencies` do not support all DAML features. Most notable some advanced type level and type class features are not supported. If you write simple DAML, this should not be an issue for you. We're currently working on shrinking the list of unsupported features and issuing warnings for those we don't intend to support.

Regarding your spurious error: Did you change the `daml.yaml` while you were running DAML Studio? That generally does not work because we only initialize the package database on startup and hence changes to `dependencies` or `data-dependencies` are not picked up in the middle of a session. I'm aware that this is not ideal but at the same time there's not enough value in improving the situation in this regard since these sorts of changes tend to happen rather infrequently.

**Comment by da-tanabe** [comment]
Definitely changed `daml.yaml`, and I guess similarly not supported is rebuilding DARs of the "other" projects when one is open.

On (2) we've just started to use typeclasses in our code as our DAML codebase is growing, and hence, repetition. For now, our typeclass usage is restricted to DARs that are _not_ used as a dependencies by other DARs, though I expect we'd want this to change soon. We're experimenting with some design patterns now, but I wouldn't be surprised if we start to inch closer to experiencing some of the problems that our friends in Sydney are grappling with.

**Comment by hurryabit** [comment]
> and I guess similarly not supported is rebuilding DARs of the "other" projects when one is open.

You've guessed correctly!

> we've just started to use typeclasses

Please be careful! For your own sake and for the sake of compatibility with data-dependencies. I've pointed you to a document describing all the intricacies of typeclasses vs data-dependencies on Slack.

**Comment by akrmn** [comment]
This was fixed by https://github.com/digital-asset/daml/pull/13205
