### ISSUE TITLE
Align sandbox/json-api behaviour for already existing portfiles

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#7806]
The sandbox accepts and overwrites already existing port files. The JSON API server rejects them and fails. It would be good to align them. I prefer sandbox's behaviour because it allows for easy testing with temporarily created files.

**Comment by cocreature** [comment]
I’m fine with changing this. Tests are imho one of the primary reasons for this feature so optimizing for temporary files seems worth doing. And even if you don’t have a temporary file, you probably want successive runs to overwrite the previous value. The chance of accidentally overwriting something important here seems fairly low.

**Comment by S11001001** [comment]
For the record the reasons for the JSON API behavior are safety and more uses outside the testing case:

1. While the chances of accidentally overwriting something are fairly low as @cocreature says, it is far lower with the JSON API.
2. You can use the port-file as a simple exclusive lock, preventing launching the server when it is already up.
3. If a sysadmin is using the existence of the port file in a startup script to await the start of listening, they get an error for not arranging the sequence of events correctly, instead of simply proceeding as if everything's ok.

If the only complication for the testing case with JSON API behavior is that the test script must delete a file first, then I think we should align to the JSON API behavior. If it is more complicated than merely deleting a file, perhaps sacrificing the production use case is worth it.

> And even if you don’t have a temporary file, you probably want successive runs to overwrite the previous value.

JSON API also deletes on exit, so this is not an issue.

**Comment by cocreature** [comment]
In our Haskell tests, we usually do something like the following:

```
withTempFile $ \portFile ->do
  startJsonApi portFile
  waitAndReadPortFile portFile -- this waits until it can read the port from the file
```

This works fine with Sandbox but for obvious reasons it doesn’t work for the JSON API. You might rightfully point out that Sandbox doesn’t write the port atomatically so the above is not safe (e.g., you could end up reading `12` instead of `123`). The same holds for the JSON API.

Which makes me wonder if the correct behavior here might be a combination of the two:

1. Keep the JSON API’s port file behavior.
2. Write the port file atomically (write to a temp file and rename)
3. The tests could witch to `withTempDir $ \dir -> startJsonAPI (dir </> "port-file")`.

That doesn’t seem to complicate the tests significantly, it only has a very minor perf impact (creating a directory is probably more expensive but I would be surprised if you manage to measure this), it gives us the safety we want and it’s actually correct in the presence of non-atomic writes.

**Comment by cocreature** [comment]
@bame-da Would you be fine with changing the Sandbox behavior here to match the JSON API and calling it a bugfix? Otherwise, I think we’re stuck with the two different ones given that I find the arguments for keeping the JSON API one convincing in the presence of atomic writes.

**Comment by bame-da** [comment]
yes, I'm good with that. You can always get the old sandbox behaviour using `rm -f portfile; daml sandbox --port-file portfile`.
