### ISSUE TITLE
Erase type information from serialized DAML-LF values

### ISSUE THREAD

**Issue by meiersi-da** [digital-asset/daml#7824]
# Motivation

The majority of the data in a DAML ledger is represented as DAML-LF values. Therefore the size of the serialized values directly determines the amount of data an actual ledger needs to ship around. Removing the type information contained in DAML-LF values significantly reduces the amount of data shipped in workflows that use records, variants, and enums.

Note that types can be erased from DAML-LF values as the type of a DAML-LF value is always given by the surrounding context. For example, a contract instance's reference to the template identifier determines the type of the contract instance's argument, which is a DAML-LF value.

# Change

Build on #7788 and introduce a new DAML-LF language version whose associated values are encoded such that
- no `Identifier` field is stored for enums, variants, and records (see [value.proto](https://github.com/digital-asset/daml/blob/master/daml-lf/transaction/src/main/protobuf/com/daml/lf/value.proto#L85))
- records store their fields without labels in the order of the type definition

This change must be done in a backwards compatible way to avoid breaking ledger integrations. Concretely, the serialization of values from earlier DAML-LF language versions must not be affected by this change.

# Design

- [ ] @remyhaemmerle-da to attempt to make a PoC that gets all tests on `daml` repo working

## Proposal: Drop types on encoding and infer on conversion to Speedy Value

* introduce new DAML-LF version whose records, enums, and variants are serialized as per the above description
* drop types on encoding and infer on conversion to Speedy Value
* infer types where they are needed in the Ledger API

# Implementation Plan

TBD: @remyhaemmerle-da 

1. get DAML-LF versioning story resolved
2. release all other DAML-LF changes
3. implement and release this serialization change

# Test Plan

* TBD @remyhaemmerle-da 

# Postponed

* replacement of constructor names for variants and enums by their index

**Comment by remyhaemmerle-da** [comment]
I foresee the following problems: 

- The speedy representation requires all the dropped informations. We need either to  
 1. change `Machine#importValue` to infer the type when importing values from the legder. (I expect a bit of slow down here)
 2. rewrite speedy to not use this information (possible but not straightforward). I expected we will discover several places where this will be tricky.

- Hashing for contract keys uses variant and enum constructor.  We need either to
 3. use the type in the value hasher.
 4. create a new hashing scheme. This seems a bit problematic for backward compatibility. 

I think we should go for 1. and 3.

2. and 4. definitively requires independent issue.

**Comment by meiersi-da** [comment]
Thanks for the quick turnaround @remyhaemmerle-da . I'm curious as to what we use this type information for. We have a statically typed language, which should allow us to eliminate the types at runtime shouldn't it?

As for the hashing algorithm. This problem was actually what prompted me to think about binding versioning of DAML-LF values to templates in the first place. I would expect that we can make the way to hash a value dependent on its version. This way we can introduce a new version. 

I'm also wondering whether we actually need to change the hashing algorithm at all. We seem to neither be hashing the `Identifier`s nor the record labels: https://github.com/digital-asset/daml/blob/master/daml-lf/transaction/src/main/scala/com/digitalasset/daml/lf/crypto/Hash.scala#L216

**Comment by remyhaemmerle-da** [comment]
We completely agree that conceptually the interpreter does not need the type information. 
However, I do expect the effort to disentangle the two to not be completely negligible. 

Out of my mind, here are some examples where we use the dynamic information: 
- error message: dynamic type information are very valuable here.
- converting Speedy value to LF Value:  we guarantee those informations are always available at the output of the engine. This is usefull for the ledger API for instance. 

I expect to find some nasty corner cases as we are refactoring the code. 

Making the hash of contract key dependent on the template version is an interesting idea that needs to be dug. That still require to be addressed in a separate issue. 

For you last remark, we do use neither `Identifiers` nor the record label, however we use the **constructor** for [variant]( https://github.com/digital-asset/daml/blob/master/daml-lf/transaction/src/main/scala/com/digitalasset/daml/lf/crypto/Hash.scala#L218) and [enum]( https://github.com/digital-asset/daml/blob/master/daml-lf/transaction/src/main/scala/com/digitalasset/daml/lf/crypto/Hash.scala#L220).

**Comment by meiersi-da** [comment]
Thanks for the feedback. I believe the biggest win is to remove the identifiers. So, I'd suggest we focus on that first and split off the changes wrt constructors. What do you think?

What kind of error messages are these that you mention?

How are we using the type information in the Ledger API? And downstream of it?

**Comment by remyhaemmerle-da** [comment]
> I believe the biggest win is to remove the identifiers. So, I'd suggest we focus on that first and split off the changes wrt constructors. What do you think?

Probably a first good step. 

> What kind of error messages are these that you mention?
For instance most of the error message from [SBuiltin.scala](https://github.com/digital-asset/daml/blob/master/daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/SBuiltin.scala) include speedy value, without type information those error messages become much more obscure. 

> How are we using the type information in the Ledger API ? 
We guarantee the output of the ledger API contains all the type information. This simplifies the writing of client as it does not have to handle LF type.

**Comment by meiersi-da** [comment]
> > What kind of error messages are these that you mention?
> 
> For instance most of the error message from [SBuiltin.scala](https://github.com/digital-asset/daml/blob/master/daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/SBuiltin.scala) includes speedy value, without type information those error messages become much more obscure.

Yes and no. I wonder which errors can actually be thrown that involve records, variants, or enums provided we are evaluating a well-typed expression?

> 
> > How are we using the type information in the Ledger API ?
> 
> We guarantee the output of the ledger API contains all the type information. This simplifies the writing of client as it does not have to handle LF type.

o.O -- that's a bit of a snag. Piping all this information all the time is expensive. I don't believe we can afford it for high throughput workloads.

@moritzkiefer-da : what DAML Connect tools would break if removed this information from the Ledger API?

**Comment by cocreature** [comment]
We don’t pipe it all the time, you can request it with a `verbose` flag on the transaction stream and similar places.

In terms of breakage, I believe DAML Script, DAML Triggers and Extractor all use the verbose flag. I expect all of them are relatively easy to fix but it might require a bit of work.

**Comment by remyhaemmerle-da** [comment]
Another example of error messages where type information is useful are not found contract key. See for instance #4872.

I am completely fine to drop all the type informations (and not only inside speedy), however we have to be conscient the cost would be important.

**Comment by hurryabit** [comment]
I see a very fundamental question that will hugely impact the implementation: Assume we have a package in version 1.8 with definitions
```
data Payload = ...

template TemplateOld with
  payload: Payload
  ...
```
and another package in version 1.9 with a template
```
template TemplateNew with
  payload: Payload
  ...
```
What value representation would the `payload` field in `TemplateNew` use? The one of version 1.8 or the one of version 1.9? In this context, we also need to consider that we might create a single value of type `Payload` and use it for creating contracts of both `TemplateOld` and `TemplateNew`.

**Using the value representation of version 1.8 for the `payload` field in `TemplateNew`** might feel strange to people because we end up with "inhomogeneous" values. However, my gut feel says that this would be quite straightforward to implement. The DAML-LF version in which a type is defined determines how it is represented and which operations to use on it, regardless of the context it is used in. One could look at this as, say, records in 1.8 and 1.9 being completely separate things. This is probably what @meiersi-da meant with making the compiler emit different primitives for, say, record constructions and projection, depending on the DAML-LF version. I would not put that in `damlc` though but rather in the Speedy compiler.

If we want to **use the 1.9 representation for the `payload` field `TemplateNew`**, I don't see any way around doing some very light type inference. Imagine the scenario where we fetch a `TemplateNew` and want to use its `payload` field to create a `TemplateOld`. What we get from the ledger will come without any type information beyond the fact that we have a `TemplateNew`, what we write to the ledger needs to have the type information all the way down. Somewhere in the middle we need to add that type information. Starting from the fact that we have a `TemplateNew`, adding this information will be pretty straightforward but will also add some runtime cost. If we want to avoid this cost when we don't need the type information, the implementation would become significantly more complicated since we'd have to do the inference on demand. I would assume this is the route we'd have to take since pessimistically performing the inference always would hamper the performance for cases where only 1.9 is used unnecessarily. There are also situations where we would need to erase type information, but I'm convinced this is trivial in comparison and could probably be done at serialization time, avoiding the allocation of any intermediate structures.

In view of this, I would suggest that the first approach, namely **using the value representation of 1.8 for the `payload` field in `TemplateNew`**, is the easier way to introduce values without type information.

**Comment by hurryabit** [comment]
> Another example of error messages where type information is useful are not found contract key.

This could be solved by sticking the type information in the primitive for doing the key lookup and using that if the lookup fails.

**Comment by hurryabit** [comment]
> Yes and no. I wonder which errors can actually be thrown that involve records, variants, or enums provided we are evaluating a well-typed expression?

There are three types of errors that can happen:
1. Type errors. These should never happen since we're guarded behind a type checker. In case they happen, we're in trouble anyway and good error messages won't really help us. I would argue that stashing the pretty printed value in the error message should be enough information for debugging the issue.
1. Runtime errors from the _polymorphic_ comparison primitives. These primitives can only raise errors if we're trying to compare function values. If we put type information in closures or not is unaffected by this proposal since closures are not serializable.
1. Runtime errors such as arithmetic errors. Except for the errors mentioned under 2., all these errors are raised by _monomorphic_ primitives. A lack of type information does not affect error messages.

> We guarantee the output of the ledger API contains all the type information. This simplifies the writing of client as it does not have to handle LF type.

I would assume dropping this guarantee for newer DAML-LF versions _by default_ is not a breaking change, particularly not if add a flag to still provide fully typed values for people who care less about performance. I would also assume that users of the Java codegen would not be affected once we've updated the codegen to speak the new DAML-LF version. cc @bame-da

**Comment by meiersi-da** [comment]
> I see a very fundamental question that will hugely impact the implementation: Assume we have a package in version 1.8 with definitions
> [...elided...]
> In view of this, I would suggest that the first approach, namely **using the value representation of 1.8 for the `payload` field in `TemplateNew`**, is the easier way to introduce values without type information.

I agree with that proposal. You've captured my intuition well: conceptually we are introducing new kinds of records, variants, and enums. Practically, they can likely share most (if not all) of the runtime and protobuf representation of existing records, variants, and enums.

@remyhaemmerle-da : I have the impression that just trying out the codechange of setting all type identifiers of records, variants, and enums to `None` and seeing what breaks in CI would provide us a lot of insight where the problems lie at low cost. What do you think about trying this out on a throwaway branch?

**Comment by hurryabit** [comment]
@meiersi-da: @remyhaemmerle-da and I had another chat on this matter and arrived at the conclusion that the approach I summarized as *Using the value representation of version 1.8 for the `payload` field in `TemplateNew`* is not particularly desirable from a maintenance point of view. Worse than that, it does not cover the case where we want to change the representation of a built-in type. We wouldn't want to have two built-in types for, say, timestamps. I consider exposing two types at the surface level as bad UX and hiding the split somewhere in the compiler as too much magic and a potential maintenance nightmare.

Instead, we think that the `use the 1.9 representation for the `payload` field `TemplateNew`* approach offers better trade-offs. As mentioned above, its main downside is that we need to run some mild form of type inference somewhere in our pipeline. However, if we want to be able to expose fully typed values on the Ledger API, which uses a different value representation, there's no way around this sort of inference anyway. If we decide to add a mode to the Ledger API for values without types, then we will only run the inference during the transition phase. Once, everybody uses the DAML-LF version and the "untyped" Ledger API, there will be no more type inference in the pipeline.

When it comes to the Engine, we're confident that we can run with partial type information. That is, we can take typed or untyped values as inputs, proceed without any inference during the computations, and only run an inference on the outputs if the caller asks for typed values.

**Comment by cocreature** [comment]
DAML Script and DAML triggers do not depend on `verbose = true` and I’ve removed it in #7870. However, both the JSON API as well as extractor do depend on this to convert an LF value to the JSON output format of the JSON API without type information (we don’t need type information in records but we need record field names for this). It’s certainly possible to do inference in the JSON API and extractor as they both have access to packages but it’s at least somewhat annoying to have to do this.

It would be great if the inference you’re adding to the ledger could be made available as a generic library so we can plug that in fairly easily and don’t have to reimplement this on the client side.

**Comment by remyhaemmerle-da** [comment]
> It would be great if the inference you’re adding to the ledger could be made available as a generic library so we can plug that in fairly easily and don’t have to reimplement this on the client side.

:+1:

**Comment by hurryabit** [comment]
> It would be great if the inference you’re adding to the ledger could be made available as a generic library so we can plug that in fairly easily and don’t have to reimplement this on the client side.

That's a fantastic idea!

> It will be make available as a generic library, for client.

Cool!
