### ISSUE TITLE
Stop logging ws close events as errors

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7846]
Currently the Javascript client libraries log websocket closes as errors. This seems a bit weird. If you unmount the corresponding react component you will get a close event so this is not an error from a user pov..

**Comment by garyverhaegen-da** [comment]
This logging is done [in the daml-react](https://github.com/digital-asset/daml/blob/ebde049cc663450f3ac1466fdf681b34c17c3e98/language-support/ts/daml-react/createLedgerContext.ts#L207-L212) library. The logic in the underlying daml-ledger stream is that the user should probably do something when the stream closes unexpectedly. I can see a couple options here:
1. Leave things as they are. This may be annoying for some users, but there is a valuable message there: users should have a close handler, because in reality, their users will face stream failures. The handler should probably not do anything on a 4000, but may have to do extra work on 4001.
2. Change the default closeHandler to log the error only when the stream closes with a non-4000 message. This will be less noisy and will still give end-users some indication of what went wrong (if they open the console) when they notice their app has become unresponsive. The main drawback here is that developers will likely never see the error cases (they generally connect to a ledger on their own machine so network connectivity is not an issue) and thus they will less likely think of providing the `closeHandler`.
3. Change the underlying daml-ledger stream to only call the closeHandler on unexpected closes, i.e. not trigger when .close is called.
4. Keep current behaviour but change the default message to something that explicitly explains how to get rid of it and why it'd be a good thing for devs to supply a closeHandler. Sort of doubling down on 1.

My preference is actually 1 here: if devs are annoyed by the extra logging, it's a perfect incentive for them to actually handle errors. 2 is easy enough to do, though, if that's the prevalent opinion.

**Comment by cocreature** [comment]
My issue with the current state is less that we log it at all and more that we log it as an error. Unmounting a component is definitely not an error and we log the corresponding log message as debug. But the associated `close` is logged as an `error` which just seems confusing and inconsistent.

Looking at this again and reading your comment about error handling, maybe we should make `onError` customizable in addition to `onClose` and log there? Reading through the websocket spec it looks like this will be called before `onClose` for erroneous closes.

**Comment by garyverhaegen-da** [comment]
I don't think we can expose the `onError` callback of the underlying WebSocket at the moment, because we already try to reconnect in daml-ledger. If we succeed in reconnecting, that would be a false positive and I don't think it would be fun for our users to try and deal with that.

And even if we could, having an API with both `onClose` and `onError` seems a bit clunky, and there is no good way to deprecate `onClose` here because it's a positional parameter.
