### ISSUE TITLE
Access to transaction trees in DAML Script

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7847]
With multi-party submissions, we should in principle be able to query a transaction stream and turn that into a DAML Script (a “DAML Script dump” of a ledger)

However, that runs into issues around contract ids: Contract ids are not fixed so we clearly cannot simply copy over the ones that we found in the original transaction stream. Instead, we have to keep track of where they were created and use that in the DAML Script. This works fine for contracts that arise from bare creates or that are the result value of an exercise which we can bind as part of the `submit` and then use later. However, if the contract is created as part of an exercise and not returned via the return value, we have no way to access it.

If we provide access to the full transaction tree produced by a `submit`, we can access all created contracts and this might also be useful for implementing tests.

**Comment by bame-da** [comment]
Yes, this is a major problem with the current Ledger API that I've been discussing with @gerolf-da and @meiersi-da recently. We need access to divulged contracts in order to do this kind of thing. Until we do, I think we will just have to leave a hole when we encounter an input contract which we haven't seen a create node for. 

I'd imagine that whenever we encounter a `Create` root node, we will write something like this into the script:

```
myTemplateCid1 <- submit [...] do
  create MyTemplate with ...
```

Whenever we encounter an `Exercise` root node with the same cid, we use that variable. Now if we encounter an `Exercise` without the cid already in scope, I'd just emit an implicit create node just before the `exercise`, but leave the unknown information blank:

```
-- ERROR: Unknown contract encountered.
myTemplateCid1 <- submit (undefined : [Party]) do
  create MyTemplate with
    field1 = undefined
    ...
```

This allows the user to fill in the gap if known. If and when we get access to the "newly divulged contracts", via the API somehow, we can remove the ERROR and fill in the undefineds.

**Comment by bame-da** [comment]
Having reread your comment, you are pointing at yet another problem. I don't think you need the transaction stream, you just need to be able to get the created contracts _in order_. Ie you need the flat transaction stream. If `query` preserves order, you could already get your hands on the cids using a series of

```
[myTemplateCid1,...,myTemplateCidn] <- drop m <$> query submitters @MyTemplate
```

right after the `submit`.

**Comment by cocreature** [comment]
Divulged contracts are orthogonal to the issue I’m describing hereand I’m not this worried about this in the context of ledger API dumps. It only matters if you can’t also get a transaction stream for the party that created the divulged contract. Otherwise you’ll see the create. That’s clearly a limitation but far from making this useless if you think of it as an admin operation.

What I was thinking off doesn’t need divulgence, take the following:

```
choice C : ()
  controller p
  do create …
       pure ()
```

I see the `exerciseCmd` and I can translate that to `exerciseCmd`. But at the moment, I have no reliable way of getting access to the `ContractId` of the contract produced by the `create` because DAML Script does not give you access to the contract. `query` kind of works but afaik we don’t document the order the active contracts service returns its results and I don’t think we should.

**Comment by cocreature** [comment]
You are right that the flat transaction stream would be sufficient but that just seems less flexible than the tree.

**Comment by bame-da** [comment]
It is less flexible, and I'm not opposed to exposing it as long as the dumped script remains relatively concise. Ie I wouldn't inline the analysis of the transaction tree, but suggest helper functions like

```
newlyCreatedContracts : forall t . (Template t) => TransactionTree -> [ContractId t]
```
