### ISSUE TITLE
Signatures on template-level let bindings are completely ignored

### ISSUE THREAD

**Issue by cocreature** [digital-asset/daml#7902]
Minimal example:

```
template T
  with
    p : Party
  where
    signatory p
    let q : Int
        q = p
    choice C : ()
      controller q
      do pure ()
```

This clearly should not compile.

**Comment by hurryabit** [comment]
@nickchapman-da I think you'll be perfectly positioned to fix this one, once the choice observer work is done (or in parallel). The problem seems to be that we drop the type annotations when pushing the template-level `let`s into all the other expressions. If we preserve them, the bug should be fixed.

**Comment by nickchapman-da** [comment]
This bug is fixed by https://github.com/digital-asset/daml/pull/8136

(The fix highlights a related issue where we report the same error more than once. #2175 )
