### ISSUE TITLE
Using dedupe/unique on ContractId

### ISSUE THREAD

**Issue by neil-da** [digital-asset/daml#814]
Currently `ContractId` doesn't have an `Ord` instance, but all our `dedupe` and `unique` functions require it. There are two options:

* Add `Ord` for `ContractId`. CC @francesco-da for whether this is feasible.
* Add `dedupeEq` and `uniqueEq` to the stdlib.

**Comment by garyverhaegen-da** [comment]
There is another option: add a `dedupeContractID` and `uniqueContractID` that can see inside the opaque ContractIDs and use their internal structure to prove those properties. Obvious downside is the lack of uniformity in the API, but the upsides are:
- No performance compromise, and
- We don't expose more than intended, i.e. if we exposed Ord as an instance for ContractID users may expect the order to be significant in some way.

**Comment by bitonic** [comment]
We are keeping `ContractId`s intentionally opaque, since they are very implementation dependent. The most concrete issue with them is that `ContractId`s _referring to the same contract_ change, since they will be relative in the transaction in which the contract was created and absolute afterwards.

So my first reaction to adding an `Ord` instance is "no".

What @garyverhaegen-da proposes would work, but seems a bit ad-hoc. However if you have a very compelling use case we could do it.

I think the right solution to this problem is to use contract keys if you need to store sets of references to contracts.

**Comment by cocreature** [comment]
We have ordering for contract ids now.
