### ISSUE TITLE
Running multiple instances of navigator on the same port  does not complain. 

### ISSUE THREAD

**Issue by akalburgi** [digital-asset/daml#837]
On starting the multiple navigators on the same port it does not complain and terminate. But the logs indicate there is a problem but the process itself is not terminated.

```
07:16:15.095 [da-ui-backend-akka.actor.default-dispatcher-8] ERROR akka.io.TcpListener - Bind failed for TCP channel on endpoint [/0.0.0.0:4000] sourceThread=da-ui-backend-akka.actor.default-dispatcher-4, akkaSource=akka://da-ui-backend/system/IO-TCP/selectors/$a/0, sourceActorSystem=da-ui-backend, akkaTimestamp=11:16:15.093UTC
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)

```

```
503 87591 87590   0  7:15AM ttys001    0:12.13 /nix/store/3gridn0fc2nx4cwlip1nd40ir6ggy076-zulu1.8.0_121-8.20.0.5/bin/java -jar /Users/anupkalburgi/.daml/sdk/0.12.12/navigator/navigator.jar server
503 87615 87614   0  7:16AM ttys002    0:12.17 /nix/store/3gridn0fc2nx4cwlip1nd40ir6ggy076-zulu1.8.0_121-8.20.0.5/bin/java -jar /Users/anupkalburgi/.daml/sdk/0.12.12/navigator/navigator.jar server
~
```

**Comment by rautenrieth-da** [comment]
In general, Navigator does not terminate on exceptions or critical issues (e.g., when it gives up reconnecting to the ledger). We should:
- Handle the case when the HTTP server can not be started, and print a nice error message on screen.
- Consider terminating the application if there is a critical, non-recoverable error.

**Comment by arturpoor-da** [comment]
I would like to poke this issue. I can serve with a real-life experience when an error message from Navigator would have been helpful.
In <https://github.com/digital-asset/ex-cbdc> steps of launching the application are nicely packaged into scripts. One of the scripts occupies port 4000, the default port of Navigator:
```
exec daml json-api --ledger-host localhost --ledger-port 6865 --http-port 4000 --allow-insecure-tokens
```
Then starting navigator with `daml ledger navigator` seemingly goes well (no errors shown), except the browser displays the following:
```
{"errors":["HttpMethod(GET), uri: http://localhost:4000/"],"status":404}
```
instead of Navigator ui. Thus an error message from Navigator could have saved some time and spared me searching for what's wrong. :slightly_smiling_face:

**Comment by basvangijzel-DA** [comment]
Daml Navigator will be deprecated for 2.9.
