### ISSUE TITLE
No party in daml.yaml file

### ISSUE THREAD

**Issue by HarshMultani** [digital-asset/daml#8487]
Hi @digitalasset-cla, I am trying to run daml on fabric.

And for that I have fabric running in my system and also daml runtime is running. Now, I am trying to deploy daml contracts in daml runtime. 

Can I deploy the daml contract without specifying any party in the daml.yaml file.

That is can my daml.yaml file be :-

sdk-version: 1.7.0
name: daml_fabric
version: 0.1.0
source: daml
parties:
dependencies:
- daml-prim
- daml-stdlib
- daml-trigger
sandbox-options:
- --wall-clock-time
- --ledgerid=dt-task-sandbox
start-navigator: false

I don't want to register parties on the ledger through daml.yaml file, I want to register parties on the ledger dynamically, during runtime

**Comment by cocreature** [comment]
Hi @HarshMultani.  The parties listed in `daml.yaml` are only used as the parties in `daml navigator` (and the navigator instance started by `daml start`). It is perfectly fine to not have any parties listed there. In that case you can then use `daml ledger navigator` which will fetch the allocated parties from the ledger instead of reading them from `daml.yaml`. If you don’t use Navigator, then the parties field is completely ignored.

**Comment by HarshMultani** [comment]
Hi @cocreature,
But when I am deploying my smart contracts using the above mentioned yaml file.

It is giving me the following error

Deploying to localhost:6865
daml: Failed to read list of parties from project config
  details: Missing required parties field in project config.

**Comment by cocreature** [comment]
Ah I see, I’d consider that a bug in `daml deploy`, thanks for reporting. `daml deploy` does 2 things:

1. It allocates the parties listed in `daml.yaml`
2. It deploys the DAR.

If you don’t want to allocate parties, you can just run `daml ledger upload-dar` for now which should work without any parties in `daml.yaml`
