### ISSUE TITLE
daml package manager

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#8976]
This is an issue for the implementation of a package management command of `daml` assistant which uses `daml` ledger to query and install available packages.

I imagine having a `daml pkg` top-level command and the subcommands described in the following. 

1. The `ledger` stanza `daml.yaml` is extended with an optional `name` field, such that packages can be queried from multiple ledgers and listed under their ledger names. A new field `default` will indicate which ledger to use in commands when several ledger entries are present but no ledger name is given for the command.
2. `update` - query ledgers for available packages and update the local cache with a list of available packages, their name, a short description, and their providing ledger.
3. `list` - list packages in the local cache with package hash for unique identification, package name, description, and location.
4. `add` - adds the package to the `daml.yaml` file under the dependencies stanza. 
5. `install` - fetches all listed packages in `daml.yaml` from the ledger(s) and installs them into the package database for the project, unless they are already installed.

**Comment by cocreature** [comment]
Summarizing our discussion, `daml build` should walk through the following steps:

1. Look at the `daml.yaml` and figure out external dependencies (probably just names in `data-dependencies` that do not end in `.dar` and are not sdk packages). As a first step, we will only support package ids. As a second step, we will support names and versions.
2. Based on that, download all transitive dalfs into `.daml/dependencies` (or something like that). We explicitly sidestep `daml ledger fetch-dar` since it would download transitive dependencies multiple times potentially. Ideally, we also include local dependencies (note that those have more information than just the dalf namely interface files and package conf) and data-dependencies in there to use the same approach for all.
3. In addition to that, write out a lock file. This lock file is required to resolve package name + version to package id and could potentially also serve as a cache to get the dependencies of a dalf without having to decode it again. I think we might want to include local packages in this as well not just remote dependencies to unify the package management story.
4. Once we’ve downloaded/extracted everything, we now proceed similarly to how packaging works now. the dalfs in the database are more or less equivalent to a dalf specified in data-dependencies.

As a general guideline, if my lockfile is up2date and the database is up2date, no network connection should be made. The lockfile should also be generated outside of `.daml` and is expected to be checked in.

In terms of implementation, we decided to roughly proceed in the following steps:
1. Split the current packaging information into a step that extracts DARs and dalfs into the database and a second step which then builds based on that information.
2. Support package ids in daml.yaml.
3. Support package names and versions in daml.yaml.

@robin-da if anything in here doesn’t make sense or sounds different from what we discussed, please correct it.

**Comment by garyverhaegen-da** [comment]
This looks really good. I'd just add a little note to point 4 (`daml add`): it would be really nice if, in the course of this work, you paved the way for other ways to get Daml packages. At this stage it could be as simple as adding the dependencies in the form of URIs (say `daml://ledger-host:ledger-port/...`), so that we can later build on that and have other forms of dependencies: local paths (`file://`), direct download from the internet (`https://`), git clone & build (`git://`), etc.

I'm obviously not asking for implementing all of this right now, just that you think about that kind of future extension when designing the format in which `daml add` "adds to daml.yaml".

I also have a naïve question: why do we want/need a lockfile? The reason for lockfiles in other ecosystems is that:
1. The host system is unable to load multiple versions of the same "package" (namespace, module, etc.), and
2. Therefore, most packages "out there" specify their own dependencies using version ranges.
This leads to a situation where there is ambiguity about how to resolve all these version ranges and thus it makes sense to record that resolution. But (1) does not apply to Daml as far as I understand (with each package having its hash-based package id), and we don't have an ecosystem yet so we could easily avoid (2) ever happening by just not supporting version ranges. It seems like locking direct dependencies (either by packageid or by artifact hash) would be quite enough, as transitive dependencies would then be completely fixed anyway. What am I missing?

**Comment by cocreature** [comment]
> why do we want/need a lockfile?

To resolve (package name, version) -> package id. Specifying package ids everywhere is super annoying for humans and resolving this is slow and can later lead to conflicts. The lock file can resolve this once (erroring if ambiguous) and then later we can fetch it easily and avoid issues if it becomes ambiguous. The lock file can also store dependency information which can be relatively expensive to compute (fetch a dalf, decode it, find all references, …) so if you just delete your local package cache you can fetch packages faster.

>  it would be really nice if, in the course of this work, you paved the way for other ways to get Daml packages. At this stage it could be as simple as adding the dependencies in the form of URIs (say `daml://ledger-host:ledger-port/...`), so that we can later build on that and have other forms of dependencies: local paths (`file://`), direct download from the internet (`https://`), git clone & build (`git://`), etc.

Definitely agree with this. This is why the first step is to make sure that the exiting file dependencies fit into this framework.

**Comment by garyverhaegen-da** [comment]
Thanks, makes sense. I still would prefer at least having the option of having hashes in daml.yaml for direct dependencies; I assumed that was why we'd have a `daml add` command rather than just tell people to edit `daml.yaml` manually.

**Comment by cocreature** [comment]
>  I still would prefer at least having the option of having hashes in daml.yaml for direct dependencies

Absolutely and that’s probably the only thing we’ll support in the first version. But I don’t think that’s good enough long-term.

**Comment by cocreature** [comment]
Closing, let’s open separate issues for new requests.
