### ISSUE TITLE
find out what's going on with traits with state and bazel

### ISSUE THREAD

**Issue by francesco-da** [digital-asset/daml#9]
In tag broken-stateful-trait-inheritance , we have class `TestExecusionSequencerFactory` being a trait with a variable `executionSequencerFactory`.

Before this class was in the test code for `AbstractContractServiceIT` and . @gaboraranyossy-da moved it to `platform-test-utils` and stuff started breaking. Specifically, the setter for `executionSequencerFactory` in `AbstractContractServiceIT` is abstract, for some reason.

We suspect that this has to do with `ijar` files that bazel generates, but we're not entirely sure.

Right now the workaround is to duplicate the `TestExecusionSequencerFactory` in the tests that need it, but we clearly should fix it.

**Comment by stefanobaghino-da** [comment]
I've created a PR that re-arranges the order in which traits are stacked on failing tests (and removed the duplicates). The issue was due to stacking a `trait` with a `null` `var` with other subtypes of `BeforeAndAfterAll`. I decided to go for the easy work-around because these tests are scheduled for deletion anyhow. :wink:
