### ISSUE TITLE
JavaScript Libs ContractId type conversion regression

### ISSUE THREAD

**Issue by bame-da** [digital-asset/daml#9046]
A forum user [pointed out a regression](https://discuss.daml.com/t/da-marketplace-0-1-15-compilation-error-with-sdk-1-10-0/2222) when upgrading the [da-marketplace app](https://github.com/digital-asset/da-marketplace/) from Connect 1.7 to 1.10.

It looks like there used to be a successful type inference from `string` to `ContractId<AssetDeposit>` in https://github.com/digital-asset/da-marketplace/blob/master/ui/src/components/Broker/BrokerOrders.tsx#L163. However, this now fails.

A workaround is to manually cast the `string`:

```
    const handleAcceptBrokerOrderFill = async () => {
        const key = wrapDamlTuple([props.cdata.broker, props.cdata.brokerOrderId])
        const cid = depositCid as ContractId<AssetDeposit>
        const args = { depositCid: cid }
        await ledger.exerciseByKey(BrokerOrder.BrokerOrder_Fill, key, args);
        setDepositCid('');
    }
```

**Comment by cocreature** [comment]
Interestingly, the following fails even in 1.7.0
```
        const args : BrokerOrder_Fill = { depositCid }
```
I’m not quite sure why the exercise itself succeeds, afaik that should always have failed. I’ll look into it a bit more.

**Comment by cocreature** [comment]
So the problem boils down to
```
let c : Choice<BrokerOrder, { depositCid: string }, ContractId<DepositTransferRequest>, BrokerOrder.Key> = BrokerOrder.BrokerOrder_Fill;
```
In SDK 1.7.0, this succeeded. `Choice` only uses the choice argument type in a covariant position. However, SDK 1.8.0 added a step to encode the choice argument to handle generic maps https://github.com/digital-asset/daml/commit/4b191f81541c00eabaec152a7924048a04195eef#diff-0c99348b2b5b77ec97a5068b737d770139b2800fc753a98135ba4605dd22e7c4R68. The encoding function has the choice argument in a contravariant position. This means that the conversion above will now fail.

However: Allowing a supertype is wrong even in SDK 1.7.0, e.g., the following succeeds despite clearly missing the `depositCid` field.
```
        let x = {};
        await ledger.exerciseByKey(BrokerOrder.BrokerOrder_Fill, key, x);
```
(you cannot inline the empty object literal since typescript special cases those).

So at the risk of sounding silly, I think this is not a regression but a bugfix wtr to the variance at least.

Now you can argue that there should be an implicit conversion from string to contract id. However, the typescript bindings specifically statically type contract ids as more than just strings to make sure you don’t mix up contract ids of different template types.

So unfortunately, I think you just have to stop pretending contract ids are strings in all cases. I’d recommend the `as` cast for the cases where you want to do the conversion here, if you want something perhaps a bit safer but significantly uglier, I’d recommend
```
        let y: ContractId<AssetDeposit> = ContractId(AssetDeposit).decoder.runWithException(depositCid);
```

**Comment by garyverhaegen-da** [comment]
> if you want something perhaps a bit safer but significantly uglier, I’d recommend
> 
> ```
>         let y: ContractId<AssetDeposit> = ContractId(AssetDeposit).decoder.runWithException(depositCid);
> ```

Would it make sense to provide a slightly more convenient wrapper around that? Say (untested)
```
function cid<T extends object, K, I extends string>(template: Template<T, K, I>, s: string): ContractId<T> {
  return ContractId(template).decoder.runWithException(s);
}
```

**Comment by cocreature** [comment]
> function cid<T extends object, K, I extends string>(template: Template<T, K, I>, s: string): ContractId<T> {
>   return ContractId(template).decoder.runWithException(s);
> }

I thought about it but it doesn’t seem much better than the `as` version. The two advantages I see are:
1. You can’t accidentally use it on a non-string. However, you can absolutely us it on a string that is not a contract id so the safety here might be slightly misleading.
2. We add some slight decoupling between the internal representation and the API type. However, I don’t think we can actually move away from the string anyway. That’s definitely breaking if you use the bindings from JS and even in TS, I think you can come up with a decent amount of cases where it’s breaking. So I’m not sure it decouples things in a useful way.
Overall, not quite sure if it’s useful enough to add it but not strongly opposed either.

**Comment by bame-da** [comment]
Thanks for the detective work. Makes perfect sense. I guess the _correct_ solution would be to type the state properly:

```
    const [ brokerOrderId, setBrokerOrderId ] = useState<ContractId<AssetDeposit> | null>(null);
```

**Comment by cocreature** [comment]
I’d got for `ContractId<AssetDeposit> | undefined` but yeah something along those lines.
