### ISSUE TITLE
Wrong erasure of Nat type 

### ISSUE THREAD

**Issue by remyhaemmerle-da** [digital-asset/daml#9181]
The following Daml code does not compile :

```
data W = W { x: forall (n: Nat). Int } 
```  

with the error message during LF type checking: 

```
Message: 
  error type checking value DA.Numeric.$sel:x:W:
  kind mismatch:
  * expected kind:
  nat
  * found Kind:
  *
```

The LF produced in this case is : 

```
def $sel:x:Workaround : DA.Numeric:Workaround -> (forall (n : nat). Int64) =
  \(dk : DA.Numeric:Workaround).
    /\(n : nat).
      let ds : forall (n1 : nat). Int64 = DA.Numeric:Workaround.x dk
      in ds
           @76bf0fd12bd945762a01f8fc5bbcdfa4d0ff20f8762af490f8f41d6237c6524f:DA.Internal.Erased:Erased
```

**Comment by cocreature** [comment]
Note that this will fail in regular daml code for a different reason (the `HasField` instances are invalid). Here is a standalone example:


```
module Test where

import qualified GHC.Types

data W = W { x : forall (n : GHC.Types.Nat). Int }
```

You have to compile that with
```
daml damlc compile ~/tmp/Test.daml --generated-src
```
which disables the `HasField` crap.

**Comment by remyhaemmerle-da** [comment]
```
data W = W (forall (n: GHC.Types.Nat). Int)

w : W -> (forall (n: GHC.Types.Nat). Int)
w (W x) = x
```

is also broken. 

I get during LF type checking:
```
Range:    1:1-2:1
Source:   DAML-LF typechecker
Severity: DsError
Message:  error type checking value Test.w:kind mismatch:* expected kind:nat* found Kind:*
```

**Comment by cocreature** [comment]
If you look at the GHC core here, you can see the following
```
Test.$sel:x:W : W -> forall (n : GHC.Types.Nat). Int
[GblId[[RecSel]], Arity=1, Caf=NoCafRefs]
Test.$sel:x:W
  = \ (dk_aiM : W) (@ (n_ahG : GHC.Types.Nat)) ->
      src</home/moritz/tmp/Test.daml:5:14>
      case dk_aiM of { W ds_diP ->
      (src</home/moritz/tmp/Test.daml:5:14> ds_diP) @ GHC.Types.Any
      }
```
We translate `Any` to `Erased` which is where the error comes from. However, I don’t really see what else we could translate it to. Ideally GHC would use `n_ahG` in place of `Any` but it doesn’t. I forgot what GHC uses `Any` for. Something related to type zonking but I also forgot what type zonking is :shrug: 

I would suggest to ignore this until we hit it outside of artificial examples.

You can fix that example with the following:

```
module Test where

import qualified GHC.Types

data Proxy (n : GHC.Types.Nat) = Proxy

data W = W { x : forall (n : GHC.Types.Nat). Proxy n -> Int }
```

**Comment by sofiafaro-da** [comment]
(copied from slack)

My best guess is that GHC is generating the following code for field selectors:

```
\(x: W) -> 
   case x of
     W y -> y
```
     
And doing type inference on this, as usual. Normally this is good enough. But the higher rank polymorphism doesn't really agree with type inference. So when type inference runs, the "forall" gets handled at the highest level it can be, which is right after the lambda,

```
\(x: W) @(n: Nat) -> ...
```

and by the time we get to infer `y`, all we have to infer is something of type `Int`. So GHC creates a fresh metavariable to turn the `y : forall (i: Nat). Int` into an `Int`:

```
\(x: W) @(n: Nat) ->
   case x of
     W y -> y @m
```

This type checks, so it's "fine"! But the metavariable `m` is not unified with anything, meaning it could literally be any type of kind `Nat` and the code would still typecheck. So GHC zaps it to `Any`, because that's what it does with non-unified metavariables.

It doesn't get `@n` because there's no constraint that `m` and `n` be the same. That explains why you get `Any`.

Part 2 of the problem: `Any` has any kind in GHC, but it gets turned into an `Erased` by the LF conversion, which has only kind `*`. We could in theory be converting `Any` to `0` for kind `Nat`, or something like that. But this is actually a big mismatch between GHC and Daml LF, since GHC treats type-level things as not having an effect on values, and Daml LF doesn't.

**Comment by basvangijzel-DA** [comment]
Fix the erasure of the Nat type for Daml 3, and instead have a proxy argument that keeps track of the size.

**Comment by akrmn** [comment]
@basvangijzel-DA, I think #11679 subsumes and improves on this issue with concrete proposals. I've added that one to the language board backlog, so I'm closing this one.
