### ISSUE TITLE
Remove code duplication of driver names in HTTP JSON API

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml#9229]
_Originally posted by @stefanobaghino-da in https://github.com/digital-asset/daml/pull/9219#discussion_r600402508_

**Comment by stefanobaghino-da** [comment]
@cocreature @S11001001 I've started by putting `ContractDao` in `db-backend`, but this cascaded into a series of breaking down packages that ended up with me being stuck with utils and domain having a circular dependency. I can probably make it work but this is becoming exceedingly time-consuming to remove a one-line code duplication. Any suggestion on how to address this? I guess there is a better way.

**Comment by cocreature** [comment]
Let me try to summarize the current state since I don’t have all of it in my head:
1. `http-json-$edition` includes `ContractDao` which has `supportedJdbcDrivers`.
2. `http-json-cli-$edition` has `supportedJdbcDriverNames`.
3. `http-json-$edition` is also the main of the binary so it clearly needs to depend on the CLI.

Looking at this, there seems to be an easy way out of this: make `http-json-cli-$edition` accept the supported driver names as an argument and pass it from `http-json-$edition`. I’m sure I’m missing something and it’s not that simple so what am I missing?

**Comment by stefanobaghino-da** [comment]
Seems like a sensible approach, I'll try this, thanks.

**Comment by stefanobaghino-da** [comment]
It worked, thanks, I was completely driven off course in my reasoning.
