### ISSUE TITLE
Record dot updates

### ISSUE THREAD

**Issue by robin-da** [digital-asset/daml#9372]
Record updates
============

This writeup is for discussing the design of the planned extension of the record dot syntax and implementation in Daml.

The current state
-----------------------

Getters

Daml does have record ``dot`` getters:

```
module Current where

data Outer = Outer {
   inner : Inner,
   t : Text
}

data Inner = Inner {
  i : Int,
  t : Text
}

-- equally named record fields work

x : Outer
x = Outer {
  inner = Inner {
    i = 1,
    t = "hello"
  },
  t = "world"
}

-- nested record getField
x1 : Int
x1 = x.inner.i
```

This is implemented via the record preprocessor and added primitives `getFieldPrim`, `getField`.
The record preprocessor implements `HasField` instances defined in `DA.Internal.Record` automatically via these primitives for
record types.

Setters

The `HasField` instances also have a `setField` method. This is used analogously to implement record
setters.

```
-- simple record setField
x2 : Outer
x2 = x {t = "foo"}

-- nested record getField, setFields
x3 : Inner
x3 = x.inner{i = 3}
```

However, nested record-setting does not work currently:

```
-- nested record setField does not work
x4 : Outer
x4 = x {x.inner.i = 2}

```

GHC's record dot setter/getters
------------------------------------------

In GHC record dot setters/getters have been implement as described in this
[proposal](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0282-record-dot-syntax.rst)

The syntax is summarized in table 2.1.1:

======================= ==================================
Expression              Equivalent
======================= ==================================
``(.lbl)``              ``(\e -> e.lbl)``
``(.lbl₁.lbl₂)``        ``(\e -> e.lbl₁.lbl₂)``
``e.lbl``               ``getField @"lbl" e``
``e.lbl₁.lbl₂``         ``(e.lbl₁).lbl₂``
``e{lbl = val}``        ``setField @"lbl" e val``
``e{lbl₁.lbl₂ = val}``  ``e{lbl₁ = (e.lbl₁){lbl₂ = val}}``
``e.lbl₁{lbl₂ = val}``  ``(e.lbl₁){lbl₂ = val}``
``e{lbl₁ = val₁}.val₂`` ``(e{lbl₁ = val₁}).val₂``
======================= ==================================

In particular, the nested record ``setField`` is working. An update operator (such as ~=) has not been
implemented in this proposal.

An intermediate state
----------------------------

The following syntax has been implemented by Martin in a PoC via the record preprocessor in the
branch `record_updates`:

```
module Raw where

import DA.Assert

data Outer = Outer with
    int: Int
    text: Text
    inner: Inner

data Inner = Inner with
    int: Int
    text: Text

outer = Outer with
    int = 13
    text = "hello"
    inner = Inner with
        int = 42
        text = "world"

mkOuter () = outer

testSimpleSet = scenario do
    (outer # text .= "bye").text === "bye"

testSimpleUpd = scenario do
    (outer # int ~= (2*)).int === 26

testNestedSet = scenario do
    (outer # inner.int .= 5).inner.int === 5

testNestedUpd = scenario do
    (outer # inner.text ~= ("hello " <>)).inner.text === "hello world"

testSimpleSetAndUpdDifferent = scenario do
    let outer2 = outer
            # int .= 7
            # text ~= (<> " world")
    outer2.int === 7
    outer2.text === "hello world"

testSimpleUpdAndSetDifferent = scenario do
    let outer2 = outer
            # text ~= (<> " world")
            # int .= 7
    outer2.int === 7
    outer2.text === "hello world"

testSimpleSetAndUpdSame = scenario do
    let outer2 = outer
            # int .= 7
            # int ~= (2*)
    outer2.int === 14

testSimpleUpdAndSetSame = scenario do
    let outer2 = outer
            # text ~= (<> " world")
            # text .= "cheers"
    outer2.text === "cheers"

testNestedSetAndUpdDifferent = scenario do
    let outer2 = outer
            # inner.int .= 7
            # inner.text ~= ("hello " <>)
    outer2.inner.int === 7
    outer2.inner.text === "hello world"

testNestedUpdAndSetDifferent = scenario do
    let outer2 = outer
            # inner.text ~= ("hello " <>)
            # inner.int .= 7
    outer2.inner.int === 7
    outer2.inner.text === "hello world"

testNestedSetAndUpdSame = scenario do
    let outer2 = outer
            # inner.int .= 7
            # inner.int ~= (2*)
    outer2.inner.int === 14

testNestedUpdAndSetSame = scenario do
    let outer2 = outer
            # inner.text ~= (<> " world")
            # inner.text .= "cheers"
    outer2.inner.text === "cheers"

testMixedSetAndUpd = scenario do
    let outer2 = outer
            # inner .= Inner with int = 3; text = "hi"
            # inner.int ~= (1+)
    outer2.inner.int === 4
    outer2.inner.text === "hi"

testSetOnProj = scenario do
    (outer.inner # text .= "bla").text === "bla"

testUpdOnProj = scenario do
    (outer.inner # int ~= (/ 2)).int === 21

testSetToProj = scenario do
    (outer # text .= (outer.inner.text)).text === "world"

testUpWithProj = scenario do
    (outer # int ~= (+ outer.inner.int)).int === 55

testNestedSetOnComplexRecord = scenario do
    (mkOuter () # inner.text .= "blub").inner.text === "blub"

testNestedUpdOnComplexRecord = scenario do
    _ <- pure ()
    (mkOuter () # inner.int ~= (1+)).inner.int === 43

testSetSection = scenario do
    let change = (# inner.text .= "yay")
    (change outer).inner.text === "yay"

testUpdSection = scenario do
    let change = (# inner.int ~= (/ 3))
    (change outer).inner.int === 14

testSetSectionWithProj = scenario do
    let change = (# inner.text .= (outer.text))
    (change outer).inner.text === "hello"

testUpdSectionWithProj = scenario do
    let change = (# inner.int ~= (/ outer.int))
    (change outer).inner.int === 3
```

Proposed end state
--------------------------

Daml should have the same record dot getters and setters, as now implemented in the above GHC
proposal. In addition, an update operator ``(~=)`` will be added with the same precedence as the
setter ``(=)``, but taking a function expressions instead of a value as its second argument.

Implementation and open questions
------------------------------------------------

I can see two possible ways to catch up with GHC state:

a) Port the GHC implementation of the parser back to Damls ghc-lib. This could be fairly involved,
but would have the benefit of reusing well tested code and design and potentially less maintance
work in the future. The additional update operator (~=) would be implemented on top.

b) Extend the already existing work in the record preprocessor. This is clearly quicker, might
however be harder (or impossible?) to get to a state where we don't need the special operators (#,
.=) as in the PoC above.

**Comment by cocreature** [comment]
Thanks for writing this up! A few comments:

1. @sofiafaro-da had a proposal at some point (not written up afaik) that instead of adding builtin syntax but providing a very limited form of lenses in daml-stdlib that we make fast in the compiler. This deserves at least a mention here. I have a slight dislike for this option since I expect it to be less intuitive to most of our users and it makes the distinction between what you can do and what you can’t do with those lenses (we definitely won’t go all profunctor) a bit muddy. Nevertheless, we should include it and I’m happy to be convinced it’s the better option.
2. If you go the road of adding builtin syntax, you cannot do all of this in the preprocessor (as you already suggested). This works for getters because `x.y` is already valid syntax and the preprocessor “just” rewrites the meaning. `y{a.b = 1}` on the other hand is not valid syntax so it will never even get to the record dot preprocessor. I do think we want builtin syntax for this, so modifying the parser it is.

In terms of concrete steps here, I’d suggest the following:
1. Sync up with @sofiafaro-da on this.
2. Adapt the parser to handle nested record setters using the same syntax as GHC. Don’t worry about record modifiers and leave record getters untouched. Ideally, copy the corresponding code for this from GHC but doing this from scratch is probably also not too bad. The record setter part is much simpler in the parser than record getters so this shouldn’t be too bad. How much work you do here in the parser vs in a preprocessor or compiler (by having the parser desugar to special builtin functions) is up to you.
3. Then start thinking about modifiers by first defining the syntax & then implement it.

**Comment by sofiafaro-da** [comment]
RE: Lenses. It was not a full proposal, only an alternative idea that was discussed with Martin. The idea was to have simple getter/setter-style lenses in the standard library, with some built-in syntax (e.g. using field names to construct lenses) and composition. It solves the nested record update problem, and is a bit more flexible (though not to the extent of profunctor or Van Laarhoven lenses). The idea of supporting it in the standard library is so that it can be purposefully optimised away by damlc in common use cases.

I think we should only go down the lenses route if we find the additional flexibility to be necessary. I completely agree that a record dot approach is more accessible, and raises fewer questions. I suggest we leave lenses out for now, and revisit them in the future if needed.

I like the proposed plan of implementing nested record setters and going from there.

**Comment by cocreature** [comment]
This has been implemented, thanks @robin-da!
