### ISSUE TITLE
DAML-LF1 and Dev protos cause name conflict for C# generated classes

### ISSUE THREAD

**Issue by georg-da** [digital-asset/daml#95]
When using the C# plugin for protoc to generate .Net code from the DAML-LF protos, the resulting code doesn't compile due to two name clashes. Proto oneof types in C# are generated as `enum`s with a default case named `None`: https://developers.google.com/protocol-buffers/docs/reference/csharp-generated#oneof

So any case that's also named `none` in the source proto file will be generated as a duplicate case `None` on the resulting enum. The two cases where this happens are:

```
message Expr {
  ...
  oneof Sum {
    ..
    // empty optional valye ('ExpNone')
    // *Available since version 1.1*
    None none = 26;                                          <= clash
    ..
  }
  ...
}

...

message CaseAlt {
  ...
  oneof Sum {
    ...
    Unit none = 7; // * Available since version 1*           <= clash
    ...
  }
  ...
}
```

A simple solution is to rename the cases above into:
```
None nothing;
```
respectively
```
Unit nothing;
```

The issue is present in both `daml_lf_1.proto` and `daml_lf_dev.proto`.

**Comment by GeorgSchneider** [comment]
What's the current thinking on this issue on our side @francesco-da ? There have been numerous questions in the support channels about C# bindings. It's ok that we don't provide them, but currently even if people try to generate them by themselves they end up with non-compiling code, which is not trivial to work around. So we're shutting out the full .Net ecosystem from writing applications against the ledger.

@hurryabit rightly mentioned to a user that the issue is not inherently in our protos (as `none` is allowed as a field name). But it's an unsatisfactory answer to tell people to open an issue with the protobuf project to have a name override implemented (which won't happen anytime soon), or leave them with the option to implement it on their own.

I'd argue it's a small breaking change for the benefit that it provides. Note that user request #1332 is also blocked by this.

**Comment by hurryabit** [comment]
Renaming the constructor, eg. to `OptionalNone`, only breaks code that uses something generated via `protoc`. It does not change the DAML-LF format at all. That said, I think we should just rename the constructor.

**Comment by bitonic** [comment]
@GeorgSchneider is there no equivalent of the `json_name` directive, but for C#? That would let us solve the problem in a cleaner way.

If there is not, I think we should rename the constructor as @GeorgSchneider says.

**Comment by GeorgSchneider** [comment]
@bitonic I could not find such an option: https://developers.google.com/protocol-buffers/docs/reference/csharp-generated 

I agree @hurryabit 's suggestion seems to be the best option to resolve this.

**Comment by hurryabit** [comment]
I'll take care of this today then.

**Comment by AndrewDCDrummond** [comment]
Bummer - fixing this issue means that my beautiful solution using sed scripts is not needed anymore :-(

e.g. 

  <Target Name="ModifyGeneratedProtoSources" BeforeTargets="CoreCompile">
    <Exec Command="sed -ri &quot;/enum SumOneofCase \{$/{N; s/(enum SumOneofCase \{)\n([ ]*)(None = 0)/\1\n\2_\3/}&quot; $(MSBuildProjectDirectory)\$(IntermediateOutputPath)*.cs" />
    <Exec Command="sed -ri &quot;s/(SumOneofCase.)(None)/\1_\2/&quot; $(MSBuildProjectDirectory)\$(IntermediateOutputPath)\*.cs" />
    <Exec Command="del $(MSBuildProjectDirectory)\sed*" />
  </Target>

converts all the generated None enums to _None, which is fair enough as it is compiler generated so should look like a non-standard symbol...
